/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-12-29
**/
package com.yh.hr.res.gt.bo;

import com.yh.platform.core.bo.BaseBo;

public class GtOtherInfo extends BaseBo {
	private static final long serialVersionUID = -2932375397594112585L;

	private java.lang.Long  	jhgGtOtherInfo;	//JhgGtOtherInfo
	private java.lang.Long  	unitOid;	//UnitOid
	private java.lang.Long  	taskOid;	//TaskOid
	private java.lang.Long  	temporaryEmpNum;	//临时用工数量
	private java.lang.String	createdByCode;	//CreatedByCode
	private java.lang.String	createdByName;	//CreatedByName
	private java.util.Date  	createdDate;	//CreatedDate
	private java.lang.String	updatedByCode;	//UpdatedByCode
	private java.lang.String	updatedByName;	//UpdatedByName
	private java.util.Date  	updatedDate;	//UpdatedDate

	public GtOtherInfo() {
		
	}

	public void setJhgGtOtherInfo(java.lang.Long jhgGtOtherInfo){
		this.jhgGtOtherInfo = jhgGtOtherInfo;
	}

	public java.lang.Long getJhgGtOtherInfo(){
		return this.jhgGtOtherInfo;
	}

	public void setUnitOid(java.lang.Long unitOid){
		this.unitOid = unitOid;
	}

	public java.lang.Long getUnitOid(){
		return this.unitOid;
	}

	public void setTemporaryEmpNum(java.lang.Long temporaryEmpNum){
		this.temporaryEmpNum = temporaryEmpNum;
	}

	public java.lang.Long getTemporaryEmpNum(){
		return this.temporaryEmpNum;
	}

	public void setCreatedByCode(java.lang.String createdByCode){
		this.createdByCode = createdByCode;
	}

	public java.lang.String getCreatedByCode(){
		return this.createdByCode;
	}

	public void setCreatedByName(java.lang.String createdByName){
		this.createdByName = createdByName;
	}

	public java.lang.String getCreatedByName(){
		return this.createdByName;
	}

	public void setCreatedDate(java.util.Date createdDate){
		this.createdDate = createdDate;
	}

	public java.util.Date getCreatedDate(){
		return this.createdDate;
	}

	public void setUpdatedByCode(java.lang.String updatedByCode){
		this.updatedByCode = updatedByCode;
	}

	public java.lang.String getUpdatedByCode(){
		return this.updatedByCode;
	}

	public void setUpdatedByName(java.lang.String updatedByName){
		this.updatedByName = updatedByName;
	}

	public java.lang.String getUpdatedByName(){
		return this.updatedByName;
	}

	public void setUpdatedDate(java.util.Date updatedDate){
		this.updatedDate = updatedDate;
	}

	public java.util.Date getUpdatedDate(){
		return this.updatedDate;
	}

	public java.lang.Long getTaskOid() {
		return taskOid;
	}

	public void setTaskOid(java.lang.Long taskOid) {
		this.taskOid = taskOid;
	}

}
