/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-12-21
**/
package com.yh.hr.res.gt.bo;

import com.yh.platform.core.bo.BaseBo;

public class GtPostPercent extends BaseBo {
	private static final long serialVersionUID = 8761989317308496633L;

	private java.lang.Long  	jhgGtPostPercentOid;	//JhgGtPostPercentOid
	private java.lang.Long  	utUnitOid;	//UtUnitOid
	private java.lang.String	postType;	//岗位类别
	private java.lang.String	postLevel;	//岗位级别
	private java.lang.Integer	percent;	//百分比
	private java.lang.String	createdByCode;	//CreatedByCode
	private java.lang.String	createdByName;	//CreatedByName
	private java.util.Date  	createdDate;	//CreatedDate
	private java.lang.String	updatedByCode;	//UpdatedByCode
	private java.lang.String	updatedByName;	//UpdatedByName
	private java.util.Date  	updatedDate;	//UpdatedDate

	public GtPostPercent() {
		
	}

	public void setJhgGtPostPercentOid(java.lang.Long jhgGtPostPercentOid){
		this.jhgGtPostPercentOid = jhgGtPostPercentOid;
	}

	public java.lang.Long getJhgGtPostPercentOid(){
		return this.jhgGtPostPercentOid;
	}

	public void setUtUnitOid(java.lang.Long utUnitOid){
		this.utUnitOid = utUnitOid;
	}

	public java.lang.Long getUtUnitOid(){
		return this.utUnitOid;
	}

	public void setPostType(java.lang.String postType){
		this.postType = postType;
	}

	public java.lang.String getPostType(){
		return this.postType;
	}

	public void setPostLevel(java.lang.String postLevel){
		this.postLevel = postLevel;
	}

	public java.lang.String getPostLevel(){
		return this.postLevel;
	}

	public void setPercent(java.lang.Integer percent){
		this.percent = percent;
	}

	public java.lang.Integer getPercent(){
		return this.percent;
	}

	public void setCreatedByCode(java.lang.String createdByCode){
		this.createdByCode = createdByCode;
	}

	public java.lang.String getCreatedByCode(){
		return this.createdByCode;
	}

	public void setCreatedByName(java.lang.String createdByName){
		this.createdByName = createdByName;
	}

	public java.lang.String getCreatedByName(){
		return this.createdByName;
	}

	public void setCreatedDate(java.util.Date createdDate){
		this.createdDate = createdDate;
	}

	public java.util.Date getCreatedDate(){
		return this.createdDate;
	}

	public void setUpdatedByCode(java.lang.String updatedByCode){
		this.updatedByCode = updatedByCode;
	}

	public java.lang.String getUpdatedByCode(){
		return this.updatedByCode;
	}

	public void setUpdatedByName(java.lang.String updatedByName){
		this.updatedByName = updatedByName;
	}

	public java.lang.String getUpdatedByName(){
		return this.updatedByName;
	}

	public void setUpdatedDate(java.util.Date updatedDate){
		this.updatedDate = updatedDate;
	}

	public java.util.Date getUpdatedDate(){
		return this.updatedDate;
	}

}
