/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-13
**/
package com.yh.hr.info.ver.unit.comm.facade;

import java.util.List;

import com.yh.component.taglib.TableTagBean;
import com.yh.hr.res.pb.dto.PbDeathInfoDTO;
import com.yh.hr.res.pb.service.PbDeathInfoService;
import com.yh.platform.core.exception.ServiceException;

public class PbDeathInfoFacade {

	private PbDeathInfoService pbDeathInfoService;

	public void setPbDeathInfoService(PbDeathInfoService pbDeathInfoService) {
		this.pbDeathInfoService = pbDeathInfoService;
	}

	/**
	 * 新增PbDeathInfo详细信息
	 * 
	 * @param 
	 * @return
	 * @throws ServiceException
	 */
	public void create(PbDeathInfoDTO pbDeathInfoDto) throws ServiceException {
		pbDeathInfoService.create(pbDeathInfoDto);
	}
	
	    /**
	 * 删除多PbDeathInfo信息
	 * 
	 * @param 
	 * @return
	 * @throws ServiceException
	 */
	public void delete(java.lang.Long pbDeathInfoId) throws ServiceException {
		pbDeathInfoService.delete(pbDeathInfoId);
	}



	/**
	 * 查找PbDeathInfo详细信息
	 * 
	 * @param 
	 * @return
	 * @throws ServiceException
	 */
	public PbDeathInfoDTO get(java.lang.Long pbDeathInfoId) throws ServiceException {
		return pbDeathInfoService.get(pbDeathInfoId);
	}
	
	/**
	 * 列出多条PbDeathInfo信息
	 * 
	 * @param 
	 * @return
	 * @throws ServiceException
	 */
	public List<PbDeathInfoDTO> find(TableTagBean ttb) throws ServiceException {
		return pbDeathInfoService.find(ttb);
	}
    
    /**
	 * 更新&修改PbDeathInfo详细信息
	 * 
	 * @param 
	 * @return
	 * @throws ServiceException
	 */
	public void update(PbDeathInfoDTO pbDeathInfoDto) throws ServiceException {
		pbDeathInfoService.update(pbDeathInfoDto);
	}
	
	/**
	 * 根据人员id查询该人员所有的自然减员记录
	 * @param personOid
	 * @return
	 * @throws ServiceException
	 */
	public List<PbDeathInfoDTO> listPbDeathInfoByPersonOid(Long personOid) throws ServiceException{
		return pbDeathInfoService.listPbDeathInfoByPersonOid(personOid);
	}

}