/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-13
**/
package com.yh.hr.info.ver.unit.comm.facade;

import com.yh.component.taglib.TableTagBean;
import com.yh.hr.res.pb.dto.PbResumeInfoDTO;
import com.yh.hr.res.pb.service.PbResumeInfoService;
import com.yh.platform.core.exception.ServiceException;

import java.util.List;

public class PbResumeInfoFacade {

	private PbResumeInfoService pbResumeInfoService;

	public void setPbResumeInfoService(PbResumeInfoService pbResumeInfoService) {
		this.pbResumeInfoService = pbResumeInfoService;
	}

	/**
	 * 新增PbResumeInfo详细信息
	 * 
	 * @param 
	 * @return
	 * @throws ServiceException
	 */
	public void create(PbResumeInfoDTO pbResumeInfoDto) throws ServiceException {
		pbResumeInfoService.create(pbResumeInfoDto);
	}
	
	    /**
	 * 删除多PbResumeInfo信息
	 * 
	 * @param 
	 * @return
	 * @throws ServiceException
	 */
	public void delete(java.lang.Long pbResumeInfoId) throws ServiceException {
		pbResumeInfoService.delete(pbResumeInfoId);
	}



	/**
	 * 查找PbResumeInfo详细信息
	 * 
	 * @param 
	 * @return
	 * @throws ServiceException
	 */
	public PbResumeInfoDTO get(java.lang.Long pbResumeInfoId) throws ServiceException {
		return pbResumeInfoService.get(pbResumeInfoId);
	}
	
	/**
	 * 列出多条PbResumeInfo信息
	 * 
	 * @param 
	 * @return
	 * @throws ServiceException
	 */
	public List<PbResumeInfoDTO> find(TableTagBean ttb) throws ServiceException {
		return pbResumeInfoService.find(ttb);
	}
    
    /**
	 * 更新&修改PbResumeInfo详细信息
	 * 
	 * @param 
	 * @return
	 * @throws ServiceException
	 */
	public void update(PbResumeInfoDTO pbResumeInfoDto) throws ServiceException {
		pbResumeInfoService.update(pbResumeInfoDto);
	}

	/**
	 * 列出多条PbResumeInfo信息
	 *
	 * @param
	 * @return
	 * @throws ServiceException
	 */
	public List<PbResumeInfoDTO> listPbResumeInfoByPersonOid(Long personOid) throws ServiceException {
		return pbResumeInfoService.listPbResumeInfoByPersonOid(personOid);
	}

}