SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for yha_dic_item
-- ----------------------------
DROP TABLE IF EXISTS `yha_dic_item`;
CREATE TABLE `yha_dic_item` (
  `DIC_ITEM_OID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'DIC_ITEM_OID',
  `DIC_ITEM_CODE` varchar(20) DEFAULT NULL COMMENT '字典代码_CODE',
  `DIC_ITEM_NAME` varchar(100) DEFAULT NULL COMMENT '字典代码_NAME',
  `VIEW_NAME` varchar(100) DEFAULT NULL COMMENT '简写',
  `DISPLAY_ORDER` decimal(10,2) DEFAULT NULL COMMENT '显示序号',
  `IS_ACTIVE` varchar(2) DEFAULT NULL COMMENT '是否激活',
  `IS_GENERAL` varchar(2) DEFAULT NULL COMMENT 'IS_GENERAL',
  `CODE_RESOURCE` varchar(2) DEFAULT NULL COMMENT '代码来源',
  `DISABLED_DATE` date DEFAULT NULL COMMENT '失效日期',
  `PARENT_CODE` varchar(20) DEFAULT NULL COMMENT '父编码',
  `CREATED_BY_CODE` varchar(50) DEFAULT NULL COMMENT '创建人CODE',
  `CREATED_BY_NAME` varchar(30) DEFAULT NULL COMMENT '创建人',
  `CREATED_DATE` datetime DEFAULT NULL COMMENT '创建日期',
  `LAST_MODIFIER_CODE` varchar(50) DEFAULT NULL COMMENT '修改人CODE',
  `LAST_MODIFIER_NAME` varchar(30) DEFAULT NULL COMMENT '修改人姓名',
  `LAST_MODIFY_DATE` datetime DEFAULT NULL COMMENT '修改日期',
  `REMARK` varchar(500) DEFAULT NULL COMMENT '备注',
  `DIC_TYPE_OID` bigint(20) NOT NULL COMMENT '外键',
  PRIMARY KEY (`DIC_ITEM_OID`),
  KEY `YHA_DIC_ITEM_YHA_DIC_TYPE_FK` (`DIC_TYPE_OID`),
  CONSTRAINT `YHA_DIC_ITEM_YHA_DIC_TYPE_FK` FOREIGN KEY (`DIC_TYPE_OID`) REFERENCES `yha_dic_type` (`DIC_TYPE_OID`)
) ENGINE=InnoDB AUTO_INCREMENT=17337 DEFAULT CHARSET=utf8 COMMENT='字典代码表';

-- ----------------------------
-- Table structure for yha_dic_type
-- ----------------------------
DROP TABLE IF EXISTS `yha_dic_type`;
CREATE TABLE `yha_dic_type` (
  `DIC_TYPE_OID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '类别OID',
  `DIC_TYPE_CODE` varchar(20) DEFAULT NULL COMMENT '类别编码',
  `DIC_TYPE_NAME` varchar(50) DEFAULT NULL COMMENT '类别名称',
  `DISPLAY_ORDER` decimal(10,2) DEFAULT NULL COMMENT '类别序号',
  `IS_ACTIVE` varchar(2) DEFAULT NULL COMMENT '是否激活',
  `REMARK` varchar(500) DEFAULT NULL COMMENT '备注',
  `DISABLED_DATE` date DEFAULT NULL COMMENT '失效日期',
  `CREATED_BY_CODE` varchar(50) DEFAULT NULL COMMENT '创建人CODE',
  `CREATED_BY_NAME` varchar(30) DEFAULT NULL COMMENT '创建人姓名',
  `CREATED_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  `LAST_MODIFIER_CODE` varchar(50) DEFAULT NULL COMMENT '修改人CODE',
  `LAST_MODIFIER_NAME` varchar(30) DEFAULT NULL COMMENT '修改人姓名',
  `LAST_MODIFY_DATE` datetime DEFAULT NULL COMMENT '修改日期',
  PRIMARY KEY (`DIC_TYPE_OID`)
) ENGINE=InnoDB AUTO_INCREMENT=1133 DEFAULT CHARSET=utf8 COMMENT='字典表';
