package org.apache.jsp.features;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import jade.util.*;

public final class dic_005fselect_005ftag_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/WEB-INF/tlds/jade.tld");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjade_005fdicSelect_0026_005fselected_005fnameField_005fname_005fidField_005femptyText_005fdicTable_005fnobody;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fjade_005fdicSelect_0026_005fselected_005fnameField_005fname_005fidField_005femptyText_005fdicTable_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fjade_005fdicSelect_0026_005fselected_005fnameField_005fname_005fidField_005femptyText_005fdicTable_005fnobody.release();
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html; charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>dicSelect</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=GBK\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#FFFFFF\" text=\"#000000\">\r\n");
      out.write("<p>平台提供了dicSelect标签，可以自动从字典表中取出数据显示为html的select，使用方法例如：</p>\r\n");
      out.write("<h4>&lt;jade:dicSelect name=\"field\" dicTable=\"DEMO_PRODUCT\" idField=\"id\" nameField=\"name\" \r\n");
      out.write("  emptyText=\"请选择...\" selected=\"2\"/&gt;</h4>\r\n");
      out.write("<br>\r\n");
      out.write("<table width=\"500\" border=\"1\" cellspacing=\"0\" cellpadding=\"5\">\r\n");
      out.write("  <tr> \r\n");
      out.write("    <td colspan=\"2\">参数说明：</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr> \r\n");
      out.write("    <td width=\"30%\">name</td>\r\n");
      out.write("    <td width=\"70%\">form field name</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr> \r\n");
      out.write("    <td>dicTable</td>\r\n");
      out.write("    <td>字典表表名</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr> \r\n");
      out.write("    <td>idField</td>\r\n");
      out.write("    <td>ID字段名</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr> \r\n");
      out.write("    <td>nameField</td>\r\n");
      out.write("    <td>显示字段名</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr> \r\n");
      out.write("    <td>emptyText</td>\r\n");
      out.write("    <td>空选择项显示文字</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr> \r\n");
      out.write("    <td>selected</td>\r\n");
      out.write("    <td>当前选中项的ID</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr> \r\n");
      out.write("    <td colspan=\"2\">另外，此标签接受其他标准html属性，例如onchange等</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("<p>运行效果： ");
      if (_jspx_meth_jade_005fdicSelect_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("</p>\r\n");
      out.write("<p>此数据库表结构为</p>\r\n");
      out.write("<p>create table DEMO_PRODUCT(<br>\r\n");
      out.write("  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,<br>\r\n");
      out.write("  name VARCHAR(255),<br>\r\n");
      out.write("  price DOUBLE<br>\r\n");
      out.write("  );</p>\r\n");
      out.write("<hr>\r\n");
      out.write("源代码：web/features/dic_select_tag.jsp\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_jade_005fdicSelect_005f0(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  jade:dicSelect
    jade.core.taglib.DicSelectTag _jspx_th_jade_005fdicSelect_005f0 = (jade.core.taglib.DicSelectTag) _005fjspx_005ftagPool_005fjade_005fdicSelect_0026_005fselected_005fnameField_005fname_005fidField_005femptyText_005fdicTable_005fnobody.get(jade.core.taglib.DicSelectTag.class);
    _jspx_th_jade_005fdicSelect_005f0.setPageContext(_jspx_page_context);
    _jspx_th_jade_005fdicSelect_005f0.setParent(null);
    _jspx_th_jade_005fdicSelect_005f0.setName("field");
    _jspx_th_jade_005fdicSelect_005f0.setDicTable("DEMO_PRODUCT");
    _jspx_th_jade_005fdicSelect_005f0.setIdField("id");
    _jspx_th_jade_005fdicSelect_005f0.setNameField("name");
    _jspx_th_jade_005fdicSelect_005f0.setEmptyText("请选择...");
    _jspx_th_jade_005fdicSelect_005f0.setSelected("2");
    int _jspx_eval_jade_005fdicSelect_005f0 = _jspx_th_jade_005fdicSelect_005f0.doStartTag();
    if (_jspx_th_jade_005fdicSelect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjade_005fdicSelect_0026_005fselected_005fnameField_005fname_005fidField_005femptyText_005fdicTable_005fnobody.reuse(_jspx_th_jade_005fdicSelect_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fjade_005fdicSelect_0026_005fselected_005fnameField_005fname_005fidField_005femptyText_005fdicTable_005fnobody.reuse(_jspx_th_jade_005fdicSelect_005f0);
    return false;
  }
}
