/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-10-09
**/
package com.yh.hr.res.pt.dto;

public class PtFamilyInfoDTO {

	private java.lang.Long  	bizPersonOid;	//BizPersonOid
	private java.lang.Long  	ptFamilyOid;	//主键
	private java.lang.Long  	familyOid;	//基础库记录OID
    /**
     *成员姓名
     **/
	private java.lang.String name;
    /**
     *与本人关系
     **/
	private java.lang.String relationship;
    /**
     *证件类别
     **/
	private java.lang.String idType;
    /**
     *身份证号
     **/
	private java.lang.String idNo;
    /**
     *政治面貌
     **/
	private java.lang.String politicsVisage;
    /**
     *出生日期
     **/
	private java.util.Date birthday;
    /**
     *单位
     **/
	private java.lang.String unit;
    /**
     *职务
     **/
	private java.lang.String duty;
    /**
     *现住址
     **/
	private java.lang.String address;
    /**
     *联系电话
     **/
	private java.lang.String phone;
    /**
     *创建人ID
     **/
	private java.lang.String createBy;
    /**
     *创建人名称
     **/
	private java.lang.String createName;
    /**
     *创建时间
     **/
	private java.util.Date createDate;
    /**
     *修改人ID
     **/
	private java.lang.String updateBy;
    /**
     *修改人名称
     **/
	private java.lang.String updateName;
    /**
     *修改时间
     **/
	private java.util.Date updateDate;

	public PtFamilyInfoDTO() {
		
	}

	public void setPtFamilyOid(java.lang.Long ptFamilyOid){
		this.ptFamilyOid = ptFamilyOid;
	}

	public java.lang.Long getPtFamilyOid(){
		return this.ptFamilyOid;
	}

	public void setBizPersonOid(java.lang.Long bizPersonOid){
		this.bizPersonOid = bizPersonOid;
	}

	public java.lang.Long getBizPersonOid(){
		return this.bizPersonOid;
	}

	public void setFamilyOid(java.lang.Long familyOid){
		this.familyOid = familyOid;
	}

	public java.lang.Long getFamilyOid(){
		return this.familyOid;
	}

	public void setName(java.lang.String name){
		this.name = name;
	}

	public java.lang.String getName(){
		return this.name;
	}

	public void setIdType(java.lang.String idType){
		this.idType = idType;
	}

	public java.lang.String getIdType(){
		return this.idType;
	}

	public void setIdNo(java.lang.String idNo){
		this.idNo = idNo;
	}

	public java.lang.String getIdNo(){
		return this.idNo;
	}

	public void setRelationship(java.lang.String relationship){
		this.relationship = relationship;
	}

	public java.lang.String getRelationship(){
		return this.relationship;
	}

	public void setBirthday(java.util.Date birthday){
		this.birthday = birthday;
	}

	public java.util.Date getBirthday(){
		return this.birthday;
	}

	public void setPoliticsVisage(java.lang.String politicsVisage){
		this.politicsVisage = politicsVisage;
	}

	public java.lang.String getPoliticsVisage(){
		return this.politicsVisage;
	}
	public java.lang.String getUnit() {
		return unit;
	}

	public void setUnit(java.lang.String unit) {
		this.unit = unit;
	}

	public java.lang.String getDuty() {
		return duty;
	}

	public void setDuty(java.lang.String duty) {
		this.duty = duty;
	}

	public java.lang.String getAddress() {
		return address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getPhone() {
		return phone;
	}

	public void setPhone(java.lang.String phone) {
		this.phone = phone;
	}

	public java.lang.String getCreateBy() {
		return createBy;
	}

	public void setCreateBy(java.lang.String createBy) {
		this.createBy = createBy;
	}

	public java.lang.String getCreateName() {
		return createName;
	}

	public void setCreateName(java.lang.String createName) {
		this.createName = createName;
	}

	public java.util.Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(java.util.Date createDate) {
		this.createDate = createDate;
	}

	public java.lang.String getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(java.lang.String updateBy) {
		this.updateBy = updateBy;
	}

	public java.lang.String getUpdateName() {
		return updateName;
	}

	public void setUpdateName(java.lang.String updateName) {
		this.updateName = updateName;
	}

	public java.util.Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(java.util.Date updateDate) {
		this.updateDate = updateDate;
	}

}
