/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-11-23
**/
package com.yh.hr.res.pt.dto;

public class PtPersonOutDTO {

	private java.lang.Long  	ptPersonOutOid;	//主键
	private java.lang.Long  	bizPersonOid;	//BizPersonOid
	private java.lang.String	dutyName;	//职务名称
	private java.lang.String	dutyAttribute;	//职务属性
	private java.lang.String	dutyLevel;	//职务级别
	private java.lang.String	beforeLeaveUnitType;	//离开前单位类别
	private java.lang.String	beforeLeaveUnitName;	//离开前单位名称
	private java.lang.Long  	beforeLeaveUnitOid;	//离开前单位OID
	private java.lang.String	moveOutUnitType;	//调离去往单位类别
	private java.lang.String	moveOutReason;	//调离原因
	private java.lang.String	moveOutUnitName;	//调离去往单位
	private java.lang.Long  	moveOutUnitOid;	//调离去往单位ID
	private java.lang.String	createdByCode;	//CreatedByCode
	private java.lang.String	createdByName;	//CreatedByName
	private java.util.Date  	createdDate;	//CreatedDate
	private java.lang.String	updatedByCode;	//UpdatedByCode
	private java.lang.String	updatedByName;	//UpdatedByName
	private java.util.Date  	updatedDate;	//UpdatedDate
	private java.util.Date      outDate;  //调出生效日期
	private java.lang.String    fileNo;//文号

	public java.lang.String getFileNo() {
		return fileNo;
	}

	public void setFileNo(java.lang.String fileNo) {
		this.fileNo = fileNo;
	}

	public java.util.Date getOutDate() {
		return outDate;
	}

	public void setOutDate(java.util.Date outDate) {
		this.outDate = outDate;
	}
	public PtPersonOutDTO() {
		
	}

	public void setPtPersonOutOid(java.lang.Long ptPersonOutOid){
		this.ptPersonOutOid = ptPersonOutOid;
	}

	public java.lang.Long getPtPersonOutOid(){
		return this.ptPersonOutOid;
	}

	public void setBizPersonOid(java.lang.Long bizPersonOid){
		this.bizPersonOid = bizPersonOid;
	}

	public java.lang.Long getBizPersonOid(){
		return this.bizPersonOid;
	}

	public void setDutyName(java.lang.String dutyName){
		this.dutyName = dutyName;
	}

	public java.lang.String getDutyName(){
		return this.dutyName;
	}

	public void setDutyAttribute(java.lang.String dutyAttribute){
		this.dutyAttribute = dutyAttribute;
	}

	public java.lang.String getDutyAttribute(){
		return this.dutyAttribute;
	}

	public void setDutyLevel(java.lang.String dutyLevel){
		this.dutyLevel = dutyLevel;
	}

	public java.lang.String getDutyLevel(){
		return this.dutyLevel;
	}

	public void setBeforeLeaveUnitType(java.lang.String beforeLeaveUnitType){
		this.beforeLeaveUnitType = beforeLeaveUnitType;
	}

	public java.lang.String getBeforeLeaveUnitType(){
		return this.beforeLeaveUnitType;
	}

	public void setBeforeLeaveUnitName(java.lang.String beforeLeaveUnitName){
		this.beforeLeaveUnitName = beforeLeaveUnitName;
	}

	public java.lang.String getBeforeLeaveUnitName(){
		return this.beforeLeaveUnitName;
	}

	public void setBeforeLeaveUnitOid(java.lang.Long beforeLeaveUnitOid){
		this.beforeLeaveUnitOid = beforeLeaveUnitOid;
	}

	public java.lang.Long getBeforeLeaveUnitOid(){
		return this.beforeLeaveUnitOid;
	}

	public void setMoveOutUnitType(java.lang.String moveOutUnitType){
		this.moveOutUnitType = moveOutUnitType;
	}

	public java.lang.String getMoveOutUnitType(){
		return this.moveOutUnitType;
	}

	public void setMoveOutReason(java.lang.String moveOutReason){
		this.moveOutReason = moveOutReason;
	}

	public java.lang.String getMoveOutReason(){
		return this.moveOutReason;
	}

	public void setMoveOutUnitName(java.lang.String moveOutUnitName){
		this.moveOutUnitName = moveOutUnitName;
	}

	public java.lang.String getMoveOutUnitName(){
		return this.moveOutUnitName;
	}

	public void setMoveOutUnitOid(java.lang.Long moveOutUnitOid){
		this.moveOutUnitOid = moveOutUnitOid;
	}

	public java.lang.Long getMoveOutUnitOid(){
		return this.moveOutUnitOid;
	}

	public void setCreatedByCode(java.lang.String createdByCode){
		this.createdByCode = createdByCode;
	}

	public java.lang.String getCreatedByCode(){
		return this.createdByCode;
	}

	public void setCreatedByName(java.lang.String createdByName){
		this.createdByName = createdByName;
	}

	public java.lang.String getCreatedByName(){
		return this.createdByName;
	}

	public void setCreatedDate(java.util.Date createdDate){
		this.createdDate = createdDate;
	}

	public java.util.Date getCreatedDate(){
		return this.createdDate;
	}

	public void setUpdatedByCode(java.lang.String updatedByCode){
		this.updatedByCode = updatedByCode;
	}

	public java.lang.String getUpdatedByCode(){
		return this.updatedByCode;
	}

	public void setUpdatedByName(java.lang.String updatedByName){
		this.updatedByName = updatedByName;
	}

	public java.lang.String getUpdatedByName(){
		return this.updatedByName;
	}

	public void setUpdatedDate(java.util.Date updatedDate){
		this.updatedDate = updatedDate;
	}

	public java.util.Date getUpdatedDate(){
		return this.updatedDate;
	}

}
