/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-10
**/
package com.yh.hr.res.pt.dto;

import org.apache.commons.lang.StringUtils;

import com.yh.platform.core.util.DateUtil;


public class PtProfTechQualifInfoDTO {

	private Long bizPersonOid;
	private Long baseProfTechQualifOid;
	
	private java.lang.Long profTechQualifOid;
	private java.lang.String certificateNo;
	private java.lang.String profTechCode;
	private java.lang.String profTechName;
	private java.lang.String profTechLevel;
	private java.lang.String profTechLevelName;
	private java.lang.String specialityName;
	private java.util.Date procureDate;
    private String procureDateStr;
	private java.util.Date validityDate;
    private String validityDateStr;
	private java.lang.String acquireApproachCode;
	private java.lang.String issueOrgan;
	private java.lang.String approveOrganName;
	private java.lang.String isHighestLevel;
	private java.lang.String remark;
	private java.lang.String createBy;
	private java.lang.String createName;
	private java.util.Date createDate;
    private String createDateStr;
	private java.lang.String updateBy;
	private java.lang.String updateName;
	private java.util.Date updateDate;
    private String updateDateStr;

    public Long getBizPersonOid() {
		return bizPersonOid;
	}

	public void setBizPersonOid(Long bizPersonOid) {
		this.bizPersonOid = bizPersonOid;
	}

	public Long getBaseProfTechQualifOid() {
		return baseProfTechQualifOid;
	}

	public void setBaseProfTechQualifOid(Long baseProfTechQualifOid) {
		this.baseProfTechQualifOid = baseProfTechQualifOid;
	}

	public void setProfTechQualifOid(java.lang.Long profTechQualifOid){
		this.profTechQualifOid = profTechQualifOid;
	}

	public java.lang.Long getProfTechQualifOid(){
		return this.profTechQualifOid;
	}
    public void setCertificateNo(java.lang.String certificateNo){
		this.certificateNo = certificateNo;
	}

	public java.lang.String getCertificateNo(){
		return this.certificateNo;
	}
    public void setProfTechCode(java.lang.String profTechCode){
		this.profTechCode = profTechCode;
	}

	public java.lang.String getProfTechCode(){
		return this.profTechCode;
	}
    public void setProfTechName(java.lang.String profTechName){
		this.profTechName = profTechName;
	}

	public java.lang.String getProfTechName(){
		return this.profTechName;
	}
    public void setProfTechLevel(java.lang.String profTechLevel){
		this.profTechLevel = profTechLevel;
	}

	public java.lang.String getProfTechLevel(){
		return this.profTechLevel;
	}
    public void setProfTechLevelName(java.lang.String profTechLevelName){
		this.profTechLevelName = profTechLevelName;
	}

	public java.lang.String getProfTechLevelName(){
		return this.profTechLevelName;
	}
    public void setSpecialityName(java.lang.String specialityName){
		this.specialityName = specialityName;
	}

	public java.lang.String getSpecialityName(){
		return this.specialityName;
	}
    public void setProcureDate(java.util.Date procureDate){
		this.procureDate = procureDate;
		if(null != procureDate){
			this.procureDateStr = DateUtil.format(procureDate, "yyyy-MM-dd");
         }
	}

	public java.util.Date getProcureDate(){
		return this.procureDate;
	}
    public void setProcureDateStr(String procureDateStr){
        this.procureDateStr = procureDateStr;
        if(StringUtils.isNotEmpty(procureDateStr)){
               this.procureDate = DateUtil.parse(procureDateStr, "yyyy-MM-dd");
        }
    }

    public String getProcureDateStr(){
        return this.procureDateStr;
    }
    public void setValidityDate(java.util.Date validityDate){
		this.validityDate = validityDate;
		if(null != validityDate){
			this.validityDateStr = DateUtil.format(validityDate, "yyyy-MM-dd");
         }
	}

	public java.util.Date getValidityDate(){
		return this.validityDate;
	}
    public void setValidityDateStr(String validityDateStr){
        this.validityDateStr = validityDateStr;
        if(StringUtils.isNotEmpty(validityDateStr)){
               this.validityDate = DateUtil.parse(validityDateStr, "yyyy-MM-dd");
        }
    }

    public String getValidityDateStr(){
        return this.validityDateStr;
    }
    public void setAcquireApproachCode(java.lang.String acquireApproachCode){
		this.acquireApproachCode = acquireApproachCode;
	}

	public java.lang.String getAcquireApproachCode(){
		return this.acquireApproachCode;
	}
    public void setIssueOrgan(java.lang.String issueOrgan){
		this.issueOrgan = issueOrgan;
	}

	public java.lang.String getIssueOrgan(){
		return this.issueOrgan;
	}
    public void setApproveOrganName(java.lang.String approveOrganName){
		this.approveOrganName = approveOrganName;
	}

	public java.lang.String getApproveOrganName(){
		return this.approveOrganName;
	}
    public void setIsHighestLevel(java.lang.String isHighestLevel){
		this.isHighestLevel = isHighestLevel;
	}

	public java.lang.String getIsHighestLevel(){
		return this.isHighestLevel;
	}
    public void setRemark(java.lang.String remark){
		this.remark = remark;
	}

	public java.lang.String getRemark(){
		return this.remark;
	}
    public void setCreateBy(java.lang.String createBy){
		this.createBy = createBy;
	}

	public java.lang.String getCreateBy(){
		return this.createBy;
	}
    public void setCreateName(java.lang.String createName){
		this.createName = createName;
	}

	public java.lang.String getCreateName(){
		return this.createName;
	}
    public void setCreateDate(java.util.Date createDate){
		this.createDate = createDate;
		if(null != createDate){
			this.createDateStr = DateUtil.format(createDate, "yyyy-MM-dd");
         }
	}

	public java.util.Date getCreateDate(){
		return this.createDate;
	}
    public void setCreateDateStr(String createDateStr){
        this.createDateStr = createDateStr;
        if(StringUtils.isNotEmpty(createDateStr)){
               this.createDate = DateUtil.parse(createDateStr, "yyyy-MM-dd");
        }
    }

    public String getCreateDateStr(){
        return this.createDateStr;
    }
    public void setUpdateBy(java.lang.String updateBy){
		this.updateBy = updateBy;
	}

	public java.lang.String getUpdateBy(){
		return this.updateBy;
	}
    public void setUpdateName(java.lang.String updateName){
		this.updateName = updateName;
	}

	public java.lang.String getUpdateName(){
		return this.updateName;
	}
    public void setUpdateDate(java.util.Date updateDate){
		this.updateDate = updateDate;
		if(null != updateDate){
			this.updateDateStr = DateUtil.format(updateDate, "yyyy-MM-dd");
         }
	}

	public java.util.Date getUpdateDate(){
		return this.updateDate;
	}
    public void setUpdateDateStr(String updateDateStr){
        this.updateDateStr = updateDateStr;
        if(StringUtils.isNotEmpty(updateDateStr)){
               this.updateDate = DateUtil.parse(updateDateStr, "yyyy-MM-dd");
        }
    }

    public String getUpdateDateStr(){
        return this.updateDateStr;
    }

}
