/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-10-09
**/
package com.yh.hr.res.pt.dto;

import com.yh.platform.core.util.DateUtil;

public class PtResumeInfoDTO {

	private java.lang.Long  	ptResumeOid;	//主键
	private java.lang.Long  	bizPersonOid;	//BizPersonOid
	private java.lang.Long  	resumeOid;	//基础库记录OID
	private java.util.Date  	startDate;	//工作起始日期
	private String startDateStr;
	private java.util.Date endDate;        //截止时间
	private String endDateStr;
	private java.lang.String	unit;	//所在单位
	private java.lang.String	duty;	//从事工作或担任职务
	private java.lang.String	remark;	//备注
	private java.lang.String	createBy;	//CreatedByCode
	private java.lang.String	createByName;	//CreatedByName
	private java.util.Date  	createDate;	//CreatedDate
	private java.lang.String	updateBy;	//UpdatedByCode
	private java.lang.String	updateByName;	//UpdatedByName
	private java.util.Date  	updateDate;	//UpdatedDate

	public PtResumeInfoDTO() {
		
	}

	public void setPtResumeOid(java.lang.Long ptResumeOid){
		this.ptResumeOid = ptResumeOid;
	}

	public java.lang.Long getPtResumeOid(){
		return this.ptResumeOid;
	}

	public void setBizPersonOid(java.lang.Long bizPersonOid){
		this.bizPersonOid = bizPersonOid;
	}

	public java.lang.Long getBizPersonOid(){
		return this.bizPersonOid;
	}

	public void setResumeOid(java.lang.Long resumeOid){
		this.resumeOid = resumeOid;
	}

	public java.lang.Long getResumeOid(){
		return this.resumeOid;
	}

	public void setStartDate(java.util.Date startDate){
		this.startDate = startDate;
		this.startDateStr =DateUtil.formatDate(startDate);
	}

	public java.util.Date getStartDate(){
		return this.startDate;
	}

	public String getStartDateStr() {
		return startDateStr;
	}

	public void setStartDateStr(String startDateStr) {
		this.startDateStr = startDateStr;
		this.startDate =DateUtil.parseDate(startDateStr);
	}

	public void setEndDate(java.util.Date endDate){
		this.endDate = endDate;
		this.endDateStr =DateUtil.formatDate(endDate);
	}

	public java.util.Date getEndDate(){
		return this.endDate;
	}

	public String getEndDateStr() {
		return endDateStr;
	}

	public void setEndDateStr(String endDateStr) {
		this.endDateStr = endDateStr;
		this.endDate =DateUtil.parseDate(endDateStr);
	}

	public void setUnit(java.lang.String unit){
		this.unit = unit;
	}

	public java.lang.String getUnit(){
		return this.unit;
	}

	public void setDuty(java.lang.String duty){
		this.duty = duty;
	}

	public java.lang.String getDuty(){
		return this.duty;
	}

	public void setRemark(java.lang.String remark){
		this.remark = remark;
	}

	public java.lang.String getRemark(){
		return this.remark;
	}

	public java.lang.String getCreateBy() {
		return createBy;
	}

	public void setCreateBy(java.lang.String createBy) {
		this.createBy = createBy;
	}

	public java.lang.String getCreateByName() {
		return createByName;
	}

	public void setCreateByName(java.lang.String createByName) {
		this.createByName = createByName;
	}

	public java.util.Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(java.util.Date createDate) {
		this.createDate = createDate;
	}

	public java.lang.String getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(java.lang.String updateBy) {
		this.updateBy = updateBy;
	}

	public java.lang.String getUpdateByName() {
		return updateByName;
	}

	public void setUpdateByName(java.lang.String updateByName) {
		this.updateByName = updateByName;
	}

	public java.util.Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(java.util.Date updateDate) {
		this.updateDate = updateDate;
	}


}
