<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ page import="com.yh.platform.core.constant.Constant"%>
<%@ page import="com.yh.hr.res.dictionary.DicConstants"%>
<%@ include file="/include/jsp_headers.jsp"%>

<!--
 * @function    奖励信息修改页面
 * @page name   /hrinfo/ver/unit/comm/pbRewardInfo/verpb_pbRewardInfo_update.jsp
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-14
-->




<!DOCTYPE html>
<html lang="cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>奖励信息修改页面</title>
<script type="text/javascript"
	src="hrinfo/ver/unit/comm/pbrewardinfo/js/check_reward_info.js"></script>
<script type="text/javascript" src="js/comm/customJs.js"></script>
</head>

<body>
<form id="rewardInfoForm" class="form-inline" action="updatePbRewardInfo.do?method=update" method="post" onsubmit="return false">
  <div id="transaction_modal_box" class="transaction_modal_box">
    <div class="modal-dialog-container">
      <div class="md-title">奖励信息&gt;修改<a href="#" class="md-close close-popdown"></a></div>
      <div class="md-error" style="display: none">
        <p>以下信息有误,请重新输入</p>
      </div>
      <div class="md-main-content">
				<input type="hidden" id="rewardOid" name="rewardOid" value="${pbRewardInfoForm.rewardOid}" />
				<input type="hidden" id="personOid" name="personOid" value="${pbRewardInfoForm.personOid}" />
				<input type="hidden" id="url_id" value="${urlId}" />
        <div class="md-units md-three-column clearfix">
					<dl class="updown-dl">
						<dt>
							<b class="Required">* </b>奖励名称：
						</dt>
						<dd>
							<label><input type="text" id="rewardName" name="rewardName" class="modal_iput" value="${pbRewardInfoForm.rewardName}" maxlength="100" />
							</label>
						</dd>
					</dl>
					<dl class="updown-dl">
						<dt>
							<b class="Required">* </b>奖励类别：
						</dt>
						<dd>
							<%-- <label><input type="text" id="rewardTypeCode" name="rewardTypeCode" class="modal_iput" value="${pbRewardInfoForm.rewardTypeCode}" maxlength="100" /></label> --%>
							<label><dictionary:dicItemSelect name="rewardTypeCode" styleClass="modal_select" selected="${pbRewardInfoForm.rewardTypeCode}" emptyText="<%=Constant.EMPTY_SELECT %>" dicTypeCode="<%=DicConstants.YHRS0076%>" />
							</label>
						</dd>
					</dl>
					<dl class="updown-dl">
						<dt>
							<b class="Required">* </b>授予荣誉称号级别：
						</dt>
						<dd>
							<%-- <label><input type="text" id="honourLevel" name="honourLevel" class="modal_iput" value="${pbRewardInfoForm.honourLevel}" maxlength="100" /></label> --%>
							<label><dictionary:dicItemSelect name="honourLevel" styleClass="modal_select" selected="${pbRewardInfoForm.honourLevel}" emptyText="<%=Constant.EMPTY_SELECT %>" dicTypeCode="<%=DicConstants.YHRS0077%>" />
							</label>
						</dd>
					</dl>
					<dl class="updown-dl">
						<dt>
							<b class="Required"></b>奖励原因：
						</dt>
						<dd>
							<label><input type="text" id="encouragementReason" name="encouragementReason" class="modal_iput" value="${pbRewardInfoForm.encouragementReason}" maxlength="100" />
							</label>
						</dd>
					</dl>
					<dl class="updown-dl">
						<dt>
							<b class="Required">* </b>奖励批准单位：
						</dt>
						<dd>
							<label><input type="text" id="rewardUnit" name="rewardUnit" class="modal_iput" value="${pbRewardInfoForm.rewardUnit}" maxlength="100" />
							</label>
						</dd>
					</dl>
					<dl class="updown-dl">
						<dt>
							<b class="Required">* </b>奖励批准日期：
						</dt>
						<dd>
							<label><input type="text" id="rewardDateStr" name="rewardDateStr" class="modal_iput" value="${pbRewardInfoForm.rewardDateStr}"  onfocus="WdatePicker({dateFmt:'yyyy-MM-dd'});" />
							</label>
							<%-- <label><input type="text" id="rewardDateStr" name="rewardDateStr" class="modal_iput" value="${pbRewardInfoForm.rewardDateStr}" maxlength="100" /></label> --%>
						</dd>
					</dl>
					<dl class="updown-remark">
						<dt>备注：</dt>
						<dd>
							<label><textarea id="remark" name="remark"maxlength="1000">${pbRewardInfoForm.remark}</textarea>
							</label>
						</dd>
					</dl>
					<div class="clear"></div>
				</div>
      </div>
    </div>
    <div class="md-btn">
        <button id="saveReward" type="button" class="md-btn-save">保  存</button>
        <button type="button" class="md-btn-cancel close-popdown" data-dismiss="modal">取 消</button>
    </div>
  </div>
</form>
</body>
</html>