/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-09-01
**/
package com.yh.hr.component.bt.dto;

import com.yh.platform.core.bo.BaseBo;

public class BtWorkFlowRefDto extends BaseBo {
	private static final long serialVersionUID = 5359627827934217680L;
	private java.lang.String	itemCode;	//
	private java.lang.String	flowNodeCode;	//
	private java.lang.String	workFlowNodeCode;	//
	private java.lang.String	createdByCode;	//CreatedByCode
	private java.lang.String	createdByName;	//CreatedByName
	private java.util.Date	createdDate;	//CreatedDate
	private java.lang.String	updatedByCode;	//UpdatedByCode
	private java.lang.String	updatedByName;	//UpdatedByName
	private java.util.Date	updatedDate;	//UpdatedDate

	
	public java.lang.String getItemCode() {
		return itemCode;
	}

	public void setItemCode(java.lang.String itemCode) {
		this.itemCode = itemCode;
	}

	public java.lang.String getFlowNodeCode() {
		return flowNodeCode;
	}

	public void setFlowNodeCode(java.lang.String flowNodeCode) {
		this.flowNodeCode = flowNodeCode;
	}

	public java.lang.String getWorkFlowNodeCode() {
		return workFlowNodeCode;
	}

	public void setWorkFlowNodeCode(java.lang.String workFlowNodeCode) {
		this.workFlowNodeCode = workFlowNodeCode;
	}

	public void setCreatedByCode(java.lang.String createdByCode){
		this.createdByCode = createdByCode;
	}

	public java.lang.String getCreatedByCode(){
		return this.createdByCode;
	}

	public void setCreatedByName(java.lang.String createdByName){
		this.createdByName = createdByName;
	}

	public java.lang.String getCreatedByName(){
		return this.createdByName;
	}

	public void setCreatedDate(java.util.Date createdDate){
		this.createdDate = createdDate;
	}

	public java.util.Date getCreatedDate(){
		return this.createdDate;
	}

	public void setUpdatedByCode(java.lang.String updatedByCode){
		this.updatedByCode = updatedByCode;
	}

	public java.lang.String getUpdatedByCode(){
		return this.updatedByCode;
	}

	public void setUpdatedByName(java.lang.String updatedByName){
		this.updatedByName = updatedByName;
	}

	public java.lang.String getUpdatedByName(){
		return this.updatedByName;
	}

	public void setUpdatedDate(java.util.Date updatedDate){
		this.updatedDate = updatedDate;
	}

	public java.util.Date getUpdatedDate(){
		return this.updatedDate;
	}

}
