/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-09-01
 **/
package com.yh.hr.component.bt.bo;

import com.yh.platform.core.bo.BaseBo;

public class BtItem extends BaseBo {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4371422996521438232L;
	private java.lang.String itemCode; //
	private java.lang.String flowCode; //
	private java.lang.String ITEM_NAME; //
	private java.lang.Integer displayOrder;
	private java.lang.String isActive;
	private java.lang.String createdByCode; // CreatedByCode
	private java.lang.String createdByName; // CreatedByName
	private java.util.Date createdDate; // CreatedDate
	private java.lang.String updatedByCode; // UpdatedByCode
	private java.lang.String updatedByName; // UpdatedByName
	private java.util.Date updatedDate; // UpdatedDate

	public BtItem() {

	}

	public void setCreatedByCode(java.lang.String createdByCode) {
		this.createdByCode = createdByCode;
	}

	public java.lang.String getCreatedByCode() {
		return this.createdByCode;
	}

	public void setCreatedByName(java.lang.String createdByName) {
		this.createdByName = createdByName;
	}

	public java.lang.String getCreatedByName() {
		return this.createdByName;
	}

	public void setCreatedDate(java.util.Date createdDate) {
		this.createdDate = createdDate;
	}

	public java.util.Date getCreatedDate() {
		return this.createdDate;
	}

	public void setUpdatedByCode(java.lang.String updatedByCode) {
		this.updatedByCode = updatedByCode;
	}

	public java.lang.String getUpdatedByCode() {
		return this.updatedByCode;
	}

	public void setUpdatedByName(java.lang.String updatedByName) {
		this.updatedByName = updatedByName;
	}

	public java.lang.String getUpdatedByName() {
		return this.updatedByName;
	}

	public void setUpdatedDate(java.util.Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public java.util.Date getUpdatedDate() {
		return this.updatedDate;
	}

	public java.lang.String getItemCode() {
		return itemCode;
	}

	public void setItemCode(java.lang.String itemCode) {
		this.itemCode = itemCode;
	}

	public java.lang.String getFlowCode() {
		return flowCode;
	}

	public void setFlowCode(java.lang.String flowCode) {
		this.flowCode = flowCode;
	}

	public java.lang.String getITEM_NAME() {
		return ITEM_NAME;
	}

	public void setITEM_NAME(java.lang.String iTEM_NAME) {
		ITEM_NAME = iTEM_NAME;
	}

	public java.lang.Integer getDisplayOrder() {
		return displayOrder;
	}

	public void setDisplayOrder(java.lang.Integer displayOrder) {
		this.displayOrder = displayOrder;
	}

	public java.lang.String getIsActive() {
		return isActive;
	}

	public void setIsActive(java.lang.String isActive) {
		this.isActive = isActive;
	}

}
