INSERT INTO `yhc_cf_query_condition_sym` VALUES (2000, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2000, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2000, 5);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2001, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2001, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2001, 5);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2002, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2002, 5);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2003, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2003, 5);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2005, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2005, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2005, 5);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2006, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2007, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2008, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2009, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2010, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2011, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2012, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2013, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2016, 1);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (2017, 1);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (2017, 4);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (2018, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2019, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2019, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2020, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2022, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2023, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2023, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2024, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2024, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2026, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2031, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2032, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2032, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2033, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2033, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2035, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2040, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2040, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2041, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2041, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2042, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2043, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2043, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2044, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2044, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2045, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2048, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1000, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1000, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1000, 5);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1001, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1001, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1001, 5);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1002, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1002, 5);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1003, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1003, 5);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1005, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1005, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1005, 5);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1006, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1007, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1008, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1009, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1010, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1011, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1012, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1013, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1016, 1);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (1017, 1);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (1017, 4);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (1018, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1019, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1019, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1020, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1022, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1023, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1023, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1024, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1024, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1026, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1031, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1032, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1032, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1033, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1033, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1035, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1040, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1040, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1041, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1041, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1042, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1043, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1043, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1044, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1044, 4);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1045, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1048, 1);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (1060, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1061, 1);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (2060, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2061, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1016, 2);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1016, 3);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1016, 6);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1016, 7);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (1018, 2);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (1018, 3);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (1018, 6);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (1018, 7);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1020, 2);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1020, 3);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1020, 6);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1020, 7);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1008, 2);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1008, 3);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1008, 6);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1008, 7);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1042, 2);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1042, 3);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1042, 6);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1042, 7);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2016, 2);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2016, 3);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2016, 6);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2016, 7);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (2018, 2);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (2018, 3);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (2018, 6);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (2018, 7);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2020, 2);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2020, 3);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2020, 6);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2020, 7);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2008, 2);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2008, 3);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2008, 6);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2008, 7);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2042, 2);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2042, 3);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2042, 6);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2042, 7);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (1062, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2062, 1);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (1063, 1);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (1063, 2);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (1063, 3);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (1063, 6);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (1063, 7);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (2063, 1);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (2063, 2);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (2063, 3);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (2063, 6);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (2063, 7);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (1064, 1);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (1065, 1);
insert into yhc_cf_query_condition_sym values 
(1066, 1);
insert into yhc_cf_query_condition_sym values 
(1066, 2);
insert into yhc_cf_query_condition_sym values 
(1066, 3);
insert into yhc_cf_query_condition_sym values 
(1066, 6);
insert into yhc_cf_query_condition_sym values 
(1066, 7);
#INSERT INTO `yhc_cf_query_condition_sym` VALUES (2064, 1);
INSERT INTO `yhc_cf_query_condition_sym` VALUES (2065, 1);
insert into yhc_cf_query_condition_sym values 
(2066, 1);
insert into yhc_cf_query_condition_sym values 
(2066, 2);
insert into yhc_cf_query_condition_sym values 
(2066, 3);
insert into yhc_cf_query_condition_sym values 
(2066, 6);
insert into yhc_cf_query_condition_sym values 
(2066, 7);
insert into yhc_cf_query_condition_sym values (1061, 5);
insert into yhc_cf_query_condition_sym values (2061, 5);
