/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-08-17
**/
package com.yh.component.dictionary.bo;

import com.yh.platform.core.bo.BaseBo;

public class DicItem extends BaseBo {
	private static final long serialVersionUID = 2183995611453770544L;
	
	private java.lang.Long		dicItemOid;			// DIC_ITEM_OID
	private java.lang.String	dicItemCode;		// 字典代码_CODE
	private java.lang.String	dicItemName;		// 字典代码_NAME
	private java.lang.String	viewName;			// 简写
	private java.lang.Double	displayOrder;		// 显示序号
	private java.lang.String	isActive;			// 是否激活
	private java.lang.String	isGeneral;			// IS_GENERAL
	private java.lang.String	codeResource;		// 代码来源
	private java.util.Date		disabledDate;		// 失效日期
	private java.lang.String	parentCode;			// 父编码
	private java.lang.String	createdByCode;		// 创建人CODE
	private java.lang.String	createdByName;		// 创建人
	private java.util.Date		createdDate;		// 创建日期
	private java.lang.String	lastModifierCode;	// 修改人CODE
	private java.lang.String	lastModifierName;	// 修改人姓名
	private java.util.Date		lastModifyDate;		// 修改日期
	private java.lang.String	remark;				// 备注
	private java.lang.Long		dicTypeOid;			// 外键

	public DicItem() {

	}

	public void setDicItemOid(java.lang.Long dicItemOid) {
		this.dicItemOid = dicItemOid;
	}

	public java.lang.Long getDicItemOid() {
		return this.dicItemOid;
	}

	public void setDicItemCode(java.lang.String dicItemCode) {
		this.dicItemCode = dicItemCode;
	}

	public java.lang.String getDicItemCode() {
		return this.dicItemCode;
	}

	public void setDicItemName(java.lang.String dicItemName) {
		this.dicItemName = dicItemName;
	}

	public java.lang.String getDicItemName() {
		return this.dicItemName;
	}

	public void setViewName(java.lang.String viewName) {
		this.viewName = viewName;
	}

	public java.lang.String getViewName() {
		return this.viewName;
	}

	public void setDisplayOrder(java.lang.Double displayOrder) {
		this.displayOrder = displayOrder;
	}

	public java.lang.Double getDisplayOrder() {
		return this.displayOrder;
	}

	public void setIsActive(java.lang.String isActive) {
		this.isActive = isActive;
	}

	public java.lang.String getIsActive() {
		return this.isActive;
	}

	public void setIsGeneral(java.lang.String isGeneral) {
		this.isGeneral = isGeneral;
	}

	public java.lang.String getIsGeneral() {
		return this.isGeneral;
	}

	public void setCodeResource(java.lang.String codeResource) {
		this.codeResource = codeResource;
	}

	public java.lang.String getCodeResource() {
		return this.codeResource;
	}

	public void setDisabledDate(java.util.Date disabledDate) {
		this.disabledDate = disabledDate;
	}

	public java.util.Date getDisabledDate() {
		return this.disabledDate;
	}

	public void setParentCode(java.lang.String parentCode) {
		this.parentCode = parentCode;
	}

	public java.lang.String getParentCode() {
		return this.parentCode;
	}

	public void setCreatedByCode(java.lang.String createdByCode) {
		this.createdByCode = createdByCode;
	}

	public java.lang.String getCreatedByCode() {
		return this.createdByCode;
	}

	public void setCreatedByName(java.lang.String createdByName) {
		this.createdByName = createdByName;
	}

	public java.lang.String getCreatedByName() {
		return this.createdByName;
	}

	public void setCreatedDate(java.util.Date createdDate) {
		this.createdDate = createdDate;
	}

	public java.util.Date getCreatedDate() {
		return this.createdDate;
	}

	public void setLastModifierCode(java.lang.String lastModifierCode) {
		this.lastModifierCode = lastModifierCode;
	}

	public java.lang.String getLastModifierCode() {
		return this.lastModifierCode;
	}

	public void setLastModifierName(java.lang.String lastModifierName) {
		this.lastModifierName = lastModifierName;
	}

	public java.lang.String getLastModifierName() {
		return this.lastModifierName;
	}

	public void setLastModifyDate(java.util.Date lastModifyDate) {
		this.lastModifyDate = lastModifyDate;
	}

	public java.util.Date getLastModifyDate() {
		return this.lastModifyDate;
	}

	public void setRemark(java.lang.String remark) {
		this.remark = remark;
	}

	public java.lang.String getRemark() {
		return this.remark;
	}

	public void setDicTypeOid(java.lang.Long dicTypeOid) {
		this.dicTypeOid = dicTypeOid;
	}

	public java.lang.Long getDicTypeOid() {
		return this.dicTypeOid;
	}

}
