<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="com.yh.platform.core.constant.Constant"%>
<%@ page import="com.yh.hr.res.dictionary.DicConstants"%>
<%@ include file="/include/jsp_headers.jsp"%>

<!--
 * @function    PbEducationTrainingInfo新增页面
 * @page name   /hrinfo/ver/verPb_PbEducationTrainingInfo_create.jsp
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-14
-->

<!DOCTYPE html>
<html lang="cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>教育培训信息新增页面</title>
<script type="text/javascript" src="hrinfo/ver/unit/comm/pbeducationtraininginfo/js/check_training_info.js"></script>
<script type="text/javascript" src="js/comm/customJs.js"></script>
</head>

<body>

	<form id="educationTrainingInfoForm" class="form-inline" action="createPbEducationTrainingInfo.do?method=create" method="post" onsubmit="return false">
		<div id="transaction_modal_box" class="transaction_modal_box">
			<div class="modal-dialog-container">
				<div class="md-title">
					教育培训信息&gt;新增 <a href="#" class="md-close close-popdown"></a>
				</div>
				<div class="md-error" style="display: none">
					<p>以下信息有误,请重新输入</p>
				</div>
				<div class="md-main-content">
					<input type="hidden" id="personOid" name="personOid" value="${personOid}" /> <input type="hidden" id="url_id" value="${urlId}" />


					<div class="md-units md-three-column clearfix">
						<dl class="updown-dl">
							<dt>
								<b class="Required">* </b>教育培训性质：
							</dt>
							<dd>
								<dictionary:dicItemSelect id="educationTrainingKinkCode" name="educationTrainingKinkCode" styleClass="modal_select" emptyText="<%=Constant.EMPTY_SELECT %>" dicTypeCode="<%=DicConstants.YHRS0050%>" />
							</dd>
						</dl>
						<dl class="updown-dl">
							<dt>
								<b class="Required"> </b>培训离岗状态：
							</dt>
							<dd>
								<dictionary:dicItemSelect id="trainingStatus" name="trainingStatus" styleClass="modal_select" emptyText="<%=Constant.EMPTY_SELECT %>" dicTypeCode="<%=DicConstants.YHRS0051%>" />
							</dd>
						</dl>
						<dl class="updown-dl">
							<dt>
								<b class="Required"> </b>从学单位：
							</dt>
							<dd>
								<label><input type="textarea" id="trainingUnitName" name="trainingUnitName" class="modal_iput" maxlength="200" />
								</label>
							</dd>
						</dl>
						<dl class="updown-dl">
							<dt>
								<b class="Required">* </b>培训类别：
							</dt>
							<dd>
								<dictionary:dicItemSelect id="trainingType" name="trainingType" styleClass="modal_select" emptyText="<%=Constant.EMPTY_SELECT %>" dicTypeCode="<%=DicConstants.YHRS0053%>" />
							</dd>
						</dl>
						<dl class="updown-dl">
							<dt>
								<b class="Required"> </b>培训名称：
							</dt>
							<dd>
								<label><input type="textarea" id="trainingName" name="trainingName" class="modal_iput" maxlength="100" />
								</label>
							</dd>
						</dl>
						<dl class="updown-dl">
							<dt>
								<b class="Required"> </b>培训内容：
							</dt>
							<dd>
								<label><input type="textarea" id="trainingContent" name="trainingContent" class="modal_iput" maxlength="1000" />
								</label>
							</dd>
						</dl>
						<dl class="updown-dl">
							<dt>
								<b class="Required">* </b>起始时间：
							</dt>
							<dd>
								<label><input type="text" id="trainingBeginDateStr" name="trainingBeginDateStr" class="modal_iput" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd'});" />
								</label>
							</dd>
						</dl>

						<dl class="updown-dl">
							<dt>
								<b class="Required">* </b>终止时间：
							</dt>
							<dd>
								<label><input type="text" id="trainingEndDateStr" name="trainingEndDateStr" class="modal_iput" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd'});" />
								</label>
							</dd>
						</dl>

						<dl class="updown-dl">
							<dt>
								<b class="Required"> </b>考核成绩：
							</dt>
							<dd>
								<label><input type="text" id="trainingGrade" name="trainingGrade" class="modal_iput" maxlength="20" />
								</label>
							</dd>
						</dl>
						<dl class="updown-dl">
							<dt>培训结果：</dt>
							<dd>
								<label><input type="text" id="trainingResult" name="trainingResult" class="modal_iput" maxlength="20" />
								</label>
							</dd>
						</dl>
						<dl class="updown-dl">
							<dt>是否出国（出境）培训：</dt>
							<dd>
								<dictionary:dicItemSelect id="isAbroadStatus" name="isAbroadStatus" styleClass="modal_select" emptyText="<%=Constant.EMPTY_SELECT %>" dicTypeCode="<%=DicConstants.YHRS0003%>" />
							</dd>
						</dl>
						<dl class="updown-dl">
							<dt>批准机构名称：</dt>
							<dd>
								<label><input type="textarea" id="approveOfficeName" name="approveOfficeName" class="modal_iput" maxlength="200" />
								</label>
							</dd>
						</dl>
						<dl class="updown-dl">
							<dt>批准日期：</dt>
							<dd>
								<label><input type="text" id="approveDateStr" name="approveDateStr" class="modal_iput" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd'});" />
								</label>
							</dd>
						</dl>
						<dl class="updown-dl updown-remark">
							<dt title="备注">备注：</dt>
							<dd style="width: 83%;">
								<label> <textarea id="remark" name="remark" rows="3" class="modal_textarea" maxlength="1000"></textarea> </label>
							</dd>
						</dl>
					</div>
				</div>
				<div class="modal-footer">
					<button id="saveEducationTrainingInfo" type="button" class="btn btn-primary">保 存</button>
					<button type="button" class="btn btn-default close-popdown" data-dismiss="modal">取 消</button>
				</div>
			</div>
		</div>

	</form>
</body>
</html>