DROP TABLE IF EXISTS `yhg_gb_yn_info`;
CREATE TABLE `yhg_gb_yn_info` (
  `POSITION_OID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `POSITION_NAME` varchar(100) DEFAULT NULL COMMENT '岗位名称',
  `PARENT_POSITION_OID` bigint(20) DEFAULT NULL,
  `PARENT_POSITION_NAME` varchar(100) DEFAULT NULL COMMENT '上级岗位名称',
  `HIS_WORK_TYPE` varchar(20) DEFAULT NULL COMMENT '工作类别',
  `HIS_POSITION_TYPE` varchar(20) DEFAULT NULL COMMENT '岗位类别',
  `HIS_POSITION_LEVEL` varchar(20) DEFAULT NULL COMMENT '岗位级别',
  `HIS_POSITION_OBLIGATION` varchar(1000) DEFAULT NULL COMMENT '岗位职责',
  `HIS_POSITION_QUALIFICATIONS` varchar(1000) DEFAULT NULL COMMENT '岗位任职条件',
  `REMARK` varchar(1000) DEFAULT NULL COMMENT '备注',
  `CREATED_BY_CODE` varchar(20) DEFAULT NULL COMMENT '创建人ID',
  `CREATED_BY_NAME` varchar(100) DEFAULT NULL COMMENT '创建人姓名',
  `CREATED_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATED_BY_CODE` varchar(20) DEFAULT NULL COMMENT '修改人ID',
  `UPDATED_BY_NAME` varchar(100) DEFAULT NULL COMMENT '修改人姓名',
  `UPDATED_DATE` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`POSITION_OID`)
) ENGINE=InnoDB AUTO_INCREMENT=1308 DEFAULT CHARSET=utf8;
