/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-10
**/
package com.yh.hr.res.pb.bo;

import com.yh.platform.core.bo.BaseBo;

public class PbEducationTrainingInfo extends BaseBo {
	private static final long serialVersionUID = 2515516587055227706L;

    /**
     *主键OID
     **/
	private java.lang.Long educationTrainingOid;
    /**
     *PersonOid
     **/
	private java.lang.Long personOid;
    /**
     *教育培训性质
     **/
	private java.lang.String educationTrainingKinkCode;
    /**
     *培训离岗状态
     **/
	private java.lang.String trainingStatus;
    /**
     *从学单位
     **/
	private java.lang.String trainingUnitName;
    /**
     *培训类别
     **/
	private java.lang.String trainingType;
    /**
     *培训名称
     **/
	private java.lang.String trainingName;
    /**
     *培训内容
     **/
	private java.lang.String trainingContent;
    /**
     *起始时间
     **/
	private java.util.Date trainingBeginDate;
    /**
     *终止时间
     **/
	private java.util.Date trainingEndDate;
    /**
     *考核成绩
     **/
	private java.lang.String trainingGrade;
    /**
     *培训结果
     **/
	private java.lang.String trainingResult;
    /**
     *是否出国（出境）培训
     **/
	private java.lang.String isAbroadStatus;
    /**
     *批准机构名称
     **/
	private java.lang.String approveOfficeName;
    /**
     *批准日期
     **/
	private java.util.Date approveDate;
    /**
     *Remark
     **/
	private java.lang.String remark;
    /**
     *创建人ID
     **/
	private java.lang.String createBy;
    /**
     *创建人名称
     **/
	private java.lang.String createName;
    /**
     *创建时间
     **/
	private java.util.Date createDate;
    /**
     *修改人ID
     **/
	private java.lang.String updateBy;
    /**
     *修改人名称
     **/
	private java.lang.String updateName;
    /**
     *修改时间
     **/
	private java.util.Date updateDate;

	public PbEducationTrainingInfo() {}

    public PbEducationTrainingInfo(java.lang.Long educationTrainingOid) {
        this.educationTrainingOid = educationTrainingOid;
    }

	public void setEducationTrainingOid(java.lang.Long educationTrainingOid){
		this.educationTrainingOid = educationTrainingOid;
	}

	public java.lang.Long getEducationTrainingOid(){
		return this.educationTrainingOid;
	}

	public void setPersonOid(java.lang.Long personOid){
		this.personOid = personOid;
	}

	public java.lang.Long getPersonOid(){
		return this.personOid;
	}

	public void setEducationTrainingKinkCode(java.lang.String educationTrainingKinkCode){
		this.educationTrainingKinkCode = educationTrainingKinkCode;
	}

	public java.lang.String getEducationTrainingKinkCode(){
		return this.educationTrainingKinkCode;
	}

	public void setTrainingStatus(java.lang.String trainingStatus){
		this.trainingStatus = trainingStatus;
	}

	public java.lang.String getTrainingStatus(){
		return this.trainingStatus;
	}

	public void setTrainingUnitName(java.lang.String trainingUnitName){
		this.trainingUnitName = trainingUnitName;
	}

	public java.lang.String getTrainingUnitName(){
		return this.trainingUnitName;
	}

	public void setTrainingType(java.lang.String trainingType){
		this.trainingType = trainingType;
	}

	public java.lang.String getTrainingType(){
		return this.trainingType;
	}

	public void setTrainingName(java.lang.String trainingName){
		this.trainingName = trainingName;
	}

	public java.lang.String getTrainingName(){
		return this.trainingName;
	}

	public void setTrainingContent(java.lang.String trainingContent){
		this.trainingContent = trainingContent;
	}

	public java.lang.String getTrainingContent(){
		return this.trainingContent;
	}

	public void setTrainingBeginDate(java.util.Date trainingBeginDate){
		this.trainingBeginDate = trainingBeginDate;
	}

	public java.util.Date getTrainingBeginDate(){
		return this.trainingBeginDate;
	}

	public void setTrainingEndDate(java.util.Date trainingEndDate){
		this.trainingEndDate = trainingEndDate;
	}

	public java.util.Date getTrainingEndDate(){
		return this.trainingEndDate;
	}

	public void setTrainingGrade(java.lang.String trainingGrade){
		this.trainingGrade = trainingGrade;
	}

	public java.lang.String getTrainingGrade(){
		return this.trainingGrade;
	}

	public void setTrainingResult(java.lang.String trainingResult){
		this.trainingResult = trainingResult;
	}

	public java.lang.String getTrainingResult(){
		return this.trainingResult;
	}

	public void setIsAbroadStatus(java.lang.String isAbroadStatus){
		this.isAbroadStatus = isAbroadStatus;
	}

	public java.lang.String getIsAbroadStatus(){
		return this.isAbroadStatus;
	}

	public void setApproveOfficeName(java.lang.String approveOfficeName){
		this.approveOfficeName = approveOfficeName;
	}

	public java.lang.String getApproveOfficeName(){
		return this.approveOfficeName;
	}

	public void setApproveDate(java.util.Date approveDate){
		this.approveDate = approveDate;
	}

	public java.util.Date getApproveDate(){
		return this.approveDate;
	}

	public void setRemark(java.lang.String remark){
		this.remark = remark;
	}

	public java.lang.String getRemark(){
		return this.remark;
	}

	public void setCreateBy(java.lang.String createBy){
		this.createBy = createBy;
	}

	public java.lang.String getCreateBy(){
		return this.createBy;
	}

	public void setCreateName(java.lang.String createName){
		this.createName = createName;
	}

	public java.lang.String getCreateName(){
		return this.createName;
	}

	public void setCreateDate(java.util.Date createDate){
		this.createDate = createDate;
	}

	public java.util.Date getCreateDate(){
		return this.createDate;
	}

	public void setUpdateBy(java.lang.String updateBy){
		this.updateBy = updateBy;
	}

	public java.lang.String getUpdateBy(){
		return this.updateBy;
	}

	public void setUpdateName(java.lang.String updateName){
		this.updateName = updateName;
	}

	public java.lang.String getUpdateName(){
		return this.updateName;
	}

	public void setUpdateDate(java.util.Date updateDate){
		this.updateDate = updateDate;
	}

	public java.util.Date getUpdateDate(){
		return this.updateDate;
	}

}
