/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-03-20
**/
package com.yh.hr.res.pb.bo;

import com.yh.platform.core.bo.BaseBo;

public class PbPersonOut extends BaseBo {
	private static final long serialVersionUID = 2515516587055227706L;

    /**
     *主键ID
     **/
	private java.lang.Long personOutOid;
    /**
     *人员ID
     **/
	private java.lang.Long personOid;
    /**
     *减员类型：1-辞职；2-辞退；3-调离；4-开除
     **/
	private java.lang.String personOutType;
    /**
     *离开日期
     **/
	private java.util.Date outDate;
    /**
     *离开后去向
     **/
	private java.lang.String personOutTo;
    /**
     *备注
     **/
	private java.lang.String remark;
    /**
     *创建人ID
     **/
	private java.lang.String createBy;
    /**
     *创建人名称
     **/
	private java.lang.String createName;
    /**
     *创建时间
     **/
	private java.util.Date createDate;
    /**
     *修改人ID
     **/
	private java.lang.String updateBy;
    /**
     *修改人名称
     **/
	private java.lang.String updateName;
    /**
     *修改时间
     **/
	private java.util.Date updateDate;

	public PbPersonOut() {}

    public PbPersonOut(java.lang.Long personOutOid) {
        this.personOutOid = personOutOid;
    }

	public void setPersonOutOid(java.lang.Long personOutOid){
		this.personOutOid = personOutOid;
	}

	public java.lang.Long getPersonOutOid(){
		return this.personOutOid;
	}

	public void setPersonOid(java.lang.Long personOid){
		this.personOid = personOid;
	}

	public java.lang.Long getPersonOid(){
		return this.personOid;
	}

	public void setPersonOutType(java.lang.String personOutType){
		this.personOutType = personOutType;
	}

	public java.lang.String getPersonOutType(){
		return this.personOutType;
	}

	public void setOutDate(java.util.Date outDate){
		this.outDate = outDate;
	}

	public java.util.Date getOutDate(){
		return this.outDate;
	}

	public void setPersonOutTo(java.lang.String personOutTo){
		this.personOutTo = personOutTo;
	}

	public java.lang.String getPersonOutTo(){
		return this.personOutTo;
	}

	public void setRemark(java.lang.String remark){
		this.remark = remark;
	}

	public java.lang.String getRemark(){
		return this.remark;
	}

	public void setCreateBy(java.lang.String createBy){
		this.createBy = createBy;
	}

	public java.lang.String getCreateBy(){
		return this.createBy;
	}

	public void setCreateName(java.lang.String createName){
		this.createName = createName;
	}

	public java.lang.String getCreateName(){
		return this.createName;
	}

	public void setCreateDate(java.util.Date createDate){
		this.createDate = createDate;
	}

	public java.util.Date getCreateDate(){
		return this.createDate;
	}

	public void setUpdateBy(java.lang.String updateBy){
		this.updateBy = updateBy;
	}

	public java.lang.String getUpdateBy(){
		return this.updateBy;
	}

	public void setUpdateName(java.lang.String updateName){
		this.updateName = updateName;
	}

	public java.lang.String getUpdateName(){
		return this.updateName;
	}

	public void setUpdateDate(java.util.Date updateDate){
		this.updateDate = updateDate;
	}

	public java.util.Date getUpdateDate(){
		return this.updateDate;
	}

}
