/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-08-24
 **/
package com.yh.hr.res.pb.bo;

import com.yh.platform.core.bo.BaseBo;

public class PbPositioningInfo extends BaseBo {
	private static final long serialVersionUID = 2515516587055227706L;

	private Long positioningOid; // 主键
	private Long personOid; // PersonOid
	private String positioningStatus; // 任(聘)状态YHRS0026
	private String dutyUnitName; // 任职(聘任)单位名称
	private Long dutyUnitOid; // 任职单位OID
	private String deptName; // 任职(聘任)内设机构
	private Long deptOid; // 任职内设机构OID
	private String dutyType; // 职务类别YHRS0027
	private String dutyAttribute; // 职务属性YHRS0028
	private String dutyName; // 任职(聘任)职务名称
	private String profTechCode; // 专业技术资格编码
	private String qualificationsCode; // 职业资格编码
	private String dutyLevel; // 任职(聘任)职务级别YHRS0015
	private String wageDutyLevel; // 工资职级，用于兑现工资待遇事业单位依据岗位级别转职务级别，可修改YHRS0015
	private String positioningReason; // 任职(聘任)原因YHRS0033
	private String positioningTypeCode; // 任职方式YHRS0032
	private String dutyChangeType; // 任职(聘任)变动类型YHRS0034
	private String dutyChangeTypeName; // 任职(聘任)变动类型描述
	private String positioningFileno; // 任职(聘任)文号
	private String positioningUnitDesc; // 任命(聘任)单位名称
	private java.util.Date dutyDate; // 任职(聘任)开始日期
	private java.util.Date endDate; // 任职(聘任)拟终止日期
	private java.util.Date endDateActual; // 任职(聘任)终止日期
	private String disposalReason; // 免职(解聘)原因类别YHRS0035
	private String disposalReasonDesc; // 免职(解聘)原因类别描述
	private String disposalFileno; // 免职(解聘)文号
	private String disposalUnit; // 免职(解聘)单位名称
	private String dutyRecordType; // 职务类型YHRS0036
	private String createdByCode; // CreatedByCode
	private String createdByName; // CreatedByName
	private java.util.Date createdDate; // CreatedDate
	private String updatedByCode; // UpdatedByCode
	private String updatedByName; // UpdatedByName
	private java.util.Date updatedDate; // UpdatedDate
	private java.lang.String wageDutyAttribute; // 工资职务属性
	private String             positioningReasonDesc; //任职原因描述
	private String             isVirtual;//是否虚拟任职
	private Long refPositioningOid;
	
	public Long getRefPositioningOid() {
		return refPositioningOid;
	}

	public void setRefPositioningOid(Long refPositioningOid) {
		this.refPositioningOid = refPositioningOid;
	}

	public java.lang.String getWageDutyAttribute() {
		return wageDutyAttribute;
	}

	public void setWageDutyAttribute(java.lang.String wageDutyAttribute) {
		this.wageDutyAttribute = wageDutyAttribute;
	}

	public PbPositioningInfo() {

	}

	public void setPositioningOid(Long positioningOid) {
		this.positioningOid = positioningOid;
	}

	public Long getPositioningOid() {
		return this.positioningOid;
	}

	public void setPersonOid(Long personOid) {
		this.personOid = personOid;
	}

	public Long getPersonOid() {
		return this.personOid;
	}

	public void setPositioningStatus(String positioningStatus) {
		this.positioningStatus = positioningStatus;
	}

	public String getPositioningStatus() {
		return this.positioningStatus;
	}

	public void setDutyUnitName(String dutyUnitName) {
		this.dutyUnitName = dutyUnitName;
	}

	public String getDutyUnitName() {
		return this.dutyUnitName;
	}

	public void setDutyUnitOid(Long dutyUnitOid) {
		this.dutyUnitOid = dutyUnitOid;
	}

	public Long getDutyUnitOid() {
		return this.dutyUnitOid;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptOid(Long deptOid) {
		this.deptOid = deptOid;
	}

	public Long getDeptOid() {
		return this.deptOid;
	}

	public void setDutyType(String dutyType) {
		this.dutyType = dutyType;
	}

	public String getDutyType() {
		return this.dutyType;
	}

	public void setDutyAttribute(String dutyAttribute) {
		this.dutyAttribute = dutyAttribute;
	}

	public String getDutyAttribute() {
		return this.dutyAttribute;
	}

	public void setDutyName(String dutyName) {
		this.dutyName = dutyName;
	}

	public String getDutyName() {
		return this.dutyName;
	}

	public String getProfTechCode() {
		return profTechCode;
	}

	public void setProfTechCode(String profTechCode) {
		this.profTechCode = profTechCode;
	}

	public String getQualificationsCode() {
		return qualificationsCode;
	}

	public void setQualificationsCode(String qualificationsCode) {
		this.qualificationsCode = qualificationsCode;
	}

	public void setDutyLevel(String dutyLevel) {
		this.dutyLevel = dutyLevel;
	}

	public String getDutyLevel() {
		return this.dutyLevel;
	}

	public void setWageDutyLevel(String wageDutyLevel) {
		this.wageDutyLevel = wageDutyLevel;
	}

	public String getWageDutyLevel() {
		return this.wageDutyLevel;
	}

	public void setPositioningReason(String positioningReason) {
		this.positioningReason = positioningReason;
	}

	public String getPositioningReason() {
		return this.positioningReason;
	}

	public void setPositioningTypeCode(String positioningTypeCode) {
		this.positioningTypeCode = positioningTypeCode;
	}

	public String getPositioningTypeCode() {
		return this.positioningTypeCode;
	}

	public void setDutyChangeType(String dutyChangeType) {
		this.dutyChangeType = dutyChangeType;
	}

	public String getDutyChangeType() {
		return this.dutyChangeType;
	}

	public void setDutyChangeTypeName(String dutyChangeTypeName) {
		this.dutyChangeTypeName = dutyChangeTypeName;
	}

	public String getDutyChangeTypeName() {
		return this.dutyChangeTypeName;
	}

	public void setPositioningFileno(String positioningFileno) {
		this.positioningFileno = positioningFileno;
	}

	public String getPositioningFileno() {
		return this.positioningFileno;
	}

	public void setPositioningUnitDesc(String positioningUnitDesc) {
		this.positioningUnitDesc = positioningUnitDesc;
	}

	public String getPositioningUnitDesc() {
		return this.positioningUnitDesc;
	}

	public void setDutyDate(java.util.Date dutyDate) {
		this.dutyDate = dutyDate;
	}

	public java.util.Date getDutyDate() {
		return this.dutyDate;
	}

	public void setEndDate(java.util.Date endDate) {
		this.endDate = endDate;
	}

	public java.util.Date getEndDate() {
		return this.endDate;
	}

	public void setEndDateActual(java.util.Date endDateActual) {
		this.endDateActual = endDateActual;
	}

	public java.util.Date getEndDateActual() {
		return this.endDateActual;
	}

	public void setDisposalReason(String disposalReason) {
		this.disposalReason = disposalReason;
	}

	public String getDisposalReason() {
		return this.disposalReason;
	}

	public void setDisposalReasonDesc(String disposalReasonDesc) {
		this.disposalReasonDesc = disposalReasonDesc;
	}

	public String getDisposalReasonDesc() {
		return this.disposalReasonDesc;
	}

	public void setDisposalFileno(String disposalFileno) {
		this.disposalFileno = disposalFileno;
	}

	public String getDisposalFileno() {
		return this.disposalFileno;
	}

	public void setDisposalUnit(String disposalUnit) {
		this.disposalUnit = disposalUnit;
	}

	public String getDisposalUnit() {
		return this.disposalUnit;
	}

	public void setDutyRecordType(String dutyRecordType) {
		this.dutyRecordType = dutyRecordType;
	}

	public String getDutyRecordType() {
		return this.dutyRecordType;
	}

	public void setCreatedByCode(String createdByCode) {
		this.createdByCode = createdByCode;
	}

	public String getCreatedByCode() {
		return this.createdByCode;
	}

	public void setCreatedByName(String createdByName) {
		this.createdByName = createdByName;
	}

	public String getCreatedByName() {
		return this.createdByName;
	}

	public void setCreatedDate(java.util.Date createdDate) {
		this.createdDate = createdDate;
	}

	public java.util.Date getCreatedDate() {
		return this.createdDate;
	}

	public void setUpdatedByCode(String updatedByCode) {
		this.updatedByCode = updatedByCode;
	}

	public String getUpdatedByCode() {
		return this.updatedByCode;
	}

	public void setUpdatedByName(String updatedByName) {
		this.updatedByName = updatedByName;
	}

	public String getUpdatedByName() {
		return this.updatedByName;
	}

	public void setUpdatedDate(java.util.Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public java.util.Date getUpdatedDate() {
		return this.updatedDate;
	}

	public String getPositioningReasonDesc() {
		return positioningReasonDesc;
	}

	public void setPositioningReasonDesc(String positioningReasonDesc) {
		this.positioningReasonDesc = positioningReasonDesc;
	}

	public String getIsVirtual() {
		return isVirtual;
	}

	public void setIsVirtual(String isVirtual) {
		this.isVirtual = isVirtual;
	}

	
}
