/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-13
**/
package com.yh.hr.res.pb.bo;

import com.yh.platform.core.bo.BaseBo;

public class PbPunishmentInfo extends BaseBo {
	private static final long serialVersionUID = 2515516587055227706L;

    /**
     *主键
     **/
	private java.lang.Long punishmentOid;
    /**
     *PersonOid
     **/
	private java.lang.Long personOid;
    /**
     *处分名称
     **/
	private java.lang.String punishmentName;
    /**
     *处分原因
     **/
	private java.lang.String punishmentReason;
    /**
     *处分期限（月）
     **/
	private java.lang.Long punishmentMonth;
    /**
     *处分截止日期
     **/
	private java.util.Date punishmentEndDate;
    /**
     *处分批准机关名称
     **/
	private java.lang.String punishmentApprovalUnit;
    /**
     *处分批准日期
     **/
	private java.util.Date punishmentDate;
    /**
     *处分是否撤销标识
     **/
	private java.lang.String isCancalPunishment;
    /**
     *备注
     **/
	private java.lang.String remark;
    /**
     *创建人ID
     **/
	private java.lang.String createBy;
    /**
     *创建人名称
     **/
	private java.lang.String createName;
    /**
     *创建时间
     **/
	private java.util.Date createDate;
    /**
     *修改人ID
     **/
	private java.lang.String updateBy;
    /**
     *修改人名称
     **/
	private java.lang.String updateName;
    /**
     *修改时间
     **/
	private java.util.Date updateDate;

	public PbPunishmentInfo() {}

    public PbPunishmentInfo(java.lang.Long punishmentOid) {
        this.punishmentOid = punishmentOid;
    }

	public void setPunishmentOid(java.lang.Long punishmentOid){
		this.punishmentOid = punishmentOid;
	}

	public java.lang.Long getPunishmentOid(){
		return this.punishmentOid;
	}

	public void setPersonOid(java.lang.Long personOid){
		this.personOid = personOid;
	}

	public java.lang.Long getPersonOid(){
		return this.personOid;
	}

	public void setPunishmentName(java.lang.String punishmentName){
		this.punishmentName = punishmentName;
	}

	public java.lang.String getPunishmentName(){
		return this.punishmentName;
	}

	public void setPunishmentReason(java.lang.String punishmentReason){
		this.punishmentReason = punishmentReason;
	}

	public java.lang.String getPunishmentReason(){
		return this.punishmentReason;
	}

	public void setPunishmentMonth(java.lang.Long punishmentMonth){
		this.punishmentMonth = punishmentMonth;
	}

	public java.lang.Long getPunishmentMonth(){
		return this.punishmentMonth;
	}

	public void setPunishmentEndDate(java.util.Date punishmentEndDate){
		this.punishmentEndDate = punishmentEndDate;
	}

	public java.util.Date getPunishmentEndDate(){
		return this.punishmentEndDate;
	}

	public void setPunishmentApprovalUnit(java.lang.String punishmentApprovalUnit){
		this.punishmentApprovalUnit = punishmentApprovalUnit;
	}

	public java.lang.String getPunishmentApprovalUnit(){
		return this.punishmentApprovalUnit;
	}

	public void setPunishmentDate(java.util.Date punishmentDate){
		this.punishmentDate = punishmentDate;
	}

	public java.util.Date getPunishmentDate(){
		return this.punishmentDate;
	}

	public void setIsCancalPunishment(java.lang.String isCancalPunishment){
		this.isCancalPunishment = isCancalPunishment;
	}

	public java.lang.String getIsCancalPunishment(){
		return this.isCancalPunishment;
	}

	public void setRemark(java.lang.String remark){
		this.remark = remark;
	}

	public java.lang.String getRemark(){
		return this.remark;
	}

	public void setCreateBy(java.lang.String createBy){
		this.createBy = createBy;
	}

	public java.lang.String getCreateBy(){
		return this.createBy;
	}

	public void setCreateName(java.lang.String createName){
		this.createName = createName;
	}

	public java.lang.String getCreateName(){
		return this.createName;
	}

	public void setCreateDate(java.util.Date createDate){
		this.createDate = createDate;
	}

	public java.util.Date getCreateDate(){
		return this.createDate;
	}

	public void setUpdateBy(java.lang.String updateBy){
		this.updateBy = updateBy;
	}

	public java.lang.String getUpdateBy(){
		return this.updateBy;
	}

	public void setUpdateName(java.lang.String updateName){
		this.updateName = updateName;
	}

	public java.lang.String getUpdateName(){
		return this.updateName;
	}

	public void setUpdateDate(java.util.Date updateDate){
		this.updateDate = updateDate;
	}

	public java.util.Date getUpdateDate(){
		return this.updateDate;
	}

}
