/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-10
**/
package com.yh.hr.info.ver.unit.comm.web.action;

import jade.workflow.utils.ObjectUtil;

import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang.StringUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yh.component.dictionary.utils.DicHelper;
import com.yh.component.taglib.TableTagBean;
import com.yh.hr.info.ver.unit.comm.facade.PbCertificateHistInfoFacade;
import com.yh.hr.info.ver.unit.comm.web.form.PbCertificateHistInfoForm;
import com.yh.hr.res.dictionary.DicConstants;
import com.yh.hr.res.pb.dto.PbCertificateHistInfoDTO;
import com.yh.platform.core.exception.ServiceException;
import com.yh.platform.core.util.BeanHelper;
import com.yh.platform.core.util.JSONHelper;
import com.yh.platform.core.util.SpringBeanUtil;
import com.yh.platform.core.util.StringUtil;
import com.yh.platform.core.web.action.BaseAction;

public class PbCertificateHistInfoAction extends BaseAction {
	private PbCertificateHistInfoFacade pbCertificateHistInfoFacade = (PbCertificateHistInfoFacade) SpringBeanUtil.getBean("pbCertificateHistInfoFacade");

	//dto属性字典转换
	private void dtoDicMap(PbCertificateHistInfoDTO dto) throws ServiceException {
		dto.setCertificateType(DicHelper.viewName(DicConstants.YHRS0118,dto.getCertificateType()));
	}
	/**
	 * 列出所有 PbCertificateHistInfo信息
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward listPbCertificateHistInfo(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
		TableTagBean ttb = TableTagBean.getFromRequest(request);
		if (request.getMethod().equals("POST")) {
	        @SuppressWarnings("rawtypes")
			Map map = BeanUtils.describe(form);
	        ttb.getCondition().copyFrom(map, true);
	    } else {
	        BeanUtils.populate(form, ttb.getCondition());
	        request.setAttribute("pbCertificateHistInfoForm", form);
	    }
        try {
        	List<PbCertificateHistInfoDTO> list = pbCertificateHistInfoFacade.find(ttb);
	        if(CollectionUtils.isNotEmpty(list)){
		        for(PbCertificateHistInfoDTO dto : list){
		        	dtoDicMap(dto);
		        }
		        request.setAttribute("list", list);
	        }
        } catch (Exception se) {
			this.handleException(request, se, null);
			return mapping.findForward("fail");
		}
        return mapping.findForward("success");
	}
	
	/**
	 * 查找单个PbCertificateHistInfo信息
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward show(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
        String certificateHistOid = request.getParameter("certificateHistOid");
        if (StringUtil.isBlank(certificateHistOid)) {
            certificateHistOid = ObjectUtil.getValue(request.getAttribute("certificateHistOid"), String.class);
        }
		try {
            if (StringUtils.isEmpty(certificateHistOid)) {
				throw new ServiceException("error.pk.invalid", "pbCertificateHistInfo certificateHistOid is null");
			}
            PbCertificateHistInfoDTO pbCertificateHistInfoDto = pbCertificateHistInfoFacade.get(ObjectUtil.getValue(certificateHistOid, java.lang.Long.class));
			if (null == pbCertificateHistInfoDto) {
				throw new ServiceException(null, "查询不到相关信息");
			}
			dtoDicMap(pbCertificateHistInfoDto);
			PbCertificateHistInfoForm pbCertificateHistInfoForm = BeanHelper.copyProperties(pbCertificateHistInfoDto, PbCertificateHistInfoForm.class);
			request.setAttribute("pbCertificateHistInfoForm", pbCertificateHistInfoForm);
            request.setAttribute("certificateHistOid", certificateHistOid);
		} catch (Exception se) {
			this.handleException(request, se, "certificateHistOid=" + certificateHistOid);
			return mapping.getInputForward();
		}
		return mapping.findForward("success");
	}

	/**
	 * 跳转到 PbCertificateHistInfo信息添加页面
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward goCreate(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
		//参数校验，可根据实际情况修改
		try
		{
			String personOid = request.getParameter("personOid");
			String urlId = request.getParameter("urlId");
			if(StringUtils.isEmpty(personOid))
			{
				throw new ServiceException("personOid is null");
			}
			if(StringUtils.isEmpty(urlId))
			{
				throw new ServiceException("urlId is null");
			}
			request.setAttribute("personOid", personOid);
			request.setAttribute("urlId", urlId);
		}
		catch(Exception se)
		{
			this.handleException(request, se, null);
			return mapping.getInputForward();
		}
		return mapping.findForward(FORWARD_SUCCESS);
	}

	/**
	 * 添加 PbCertificateHistInfo信息
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward create(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
		if (this.isCancelled(request)) {
			return mapping.findForward("cancel");
		}
		PbCertificateHistInfoForm pbCertificateHistInfoForm = (PbCertificateHistInfoForm) form;
		try {
//			if(StringUtils.isEmpty(${fkOid}))
//			{
//				throw new ServiceException("${fkOid} is null");
//			}
			PbCertificateHistInfoDTO pbCertificateHistInfoDto = BeanHelper.copyProperties(pbCertificateHistInfoForm, PbCertificateHistInfoDTO.class);
//			pbCertificateHistInfoDto.setPersonOid(NumberUtils.longValue(personOid));
			pbCertificateHistInfoFacade.create(pbCertificateHistInfoDto);
			response.getWriter().write(JSONHelper.fromObject(true, null).toString());
		} catch (Exception se) {
			this.handleException(request, se, null);
			response.getWriter().write(JSONHelper.fromObject(false, StringUtils.defaultIfEmpty(se.getMessage(), "修改失败")).toString());
		}

		return null;
	}


	/**
	 * 跳转到 PbCertificateHistInfo信息修改（编辑）页面前的查询回显
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward goUpdate(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
		if(this.isCancelled(request)) {
			return mapping.findForward("cancel");
		}

        String certificateHistOid = request.getParameter("certificateHistOid");
        String urlId = request.getParameter("urlId");

		try {
            if (StringUtils.isBlank(certificateHistOid)) {
				throw new ServiceException("error.pk.invalid", "pbCertificateHistInfo certificateHistOid is null");
			}
            PbCertificateHistInfoDTO pbCertificateHistInfoDto = pbCertificateHistInfoFacade.get(ObjectUtil.getValue(certificateHistOid, java.lang.Long.class));
			if (null == pbCertificateHistInfoDto) {
				throw new ServiceException("error.object.notfound", "pbCertificateHistInfo not found by certificateHistOid");
			}
			PbCertificateHistInfoForm pbCertificateHistInfoForm = BeanHelper.copyProperties(pbCertificateHistInfoDto, PbCertificateHistInfoForm.class);
			request.setAttribute("pbCertificateHistInfoForm", pbCertificateHistInfoForm);
            request.setAttribute("certificateHistOid", certificateHistOid);
            request.setAttribute("urlId", urlId);
		} catch (Exception se) {
			this.handleException(request, se, "certificateHistOid=" + certificateHistOid);
			return mapping.getInputForward();
		}
		return goUpdateView(mapping, form, request, response);
	}

	/**
	 * 跳转到 PbCertificateHistInfo信息修改（编辑）页面
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
    public ActionForward goUpdateView(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
        //add jsp init values
        @SuppressWarnings("unused")
		PbCertificateHistInfoForm pbCertificateHistInfoForm = (PbCertificateHistInfoForm) form;
        return mapping.findForward("success");
    }

	/**
	 * 更新 PbCertificateHistInfo信息
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward update(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
		if(this.isCancelled(request)) {
			return mapping.findForward("cancel");
		}
        String certificateHistOid = request.getParameter("certificateHistOid");
		PbCertificateHistInfoForm pbCertificateHistInfoForm = (PbCertificateHistInfoForm) form;
		try {
            if (StringUtils.isBlank(certificateHistOid)) {
				throw new ServiceException("error.pk.invalid", "pbCertificateHistInfo certificateHistOid is null");
			}
//			if(StringUtils.isEmpty(${fkOid}))
//			{
//				throw new ServiceException("${fkOid} is null");
//			}
			PbCertificateHistInfoDTO pbCertificateHistInfoDto = new PbCertificateHistInfoDTO();
			BeanHelper.copyProperties(pbCertificateHistInfoForm, pbCertificateHistInfoDto);
			pbCertificateHistInfoFacade.update(pbCertificateHistInfoDto);
			response.getWriter().write(JSONHelper.fromObject(true, null).toString());
		} catch (Exception se) {
			this.handleException(request, se, pbCertificateHistInfoForm);
			response.getWriter().write(JSONHelper.fromObject(false, StringUtils.defaultIfEmpty(se.getMessage(), "修改失败")).toString());
		}

		return null;
	}



	/**
	 * 删除 PbCertificateHistInfo信息
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
    public ActionForward delete(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
           String certificateHistOid = request.getParameter("certificateHistOid");
        try {
           if(StringUtils.isEmpty(certificateHistOid))
			{
				throw new ServiceException(null, "certificateHistOid is null");
			}
            pbCertificateHistInfoFacade.delete(ObjectUtil.getValue(certificateHistOid, java.lang.Long.class));
            response.getWriter().write(JSONHelper.fromObject(true, null).toString());
        } catch (Exception se) {
            this.handleException(request, se, "certificateHistOid=" + certificateHistOid);
            return mapping.getInputForward();
        }
        return null;
    }

}
