/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-13
**/
package com.yh.hr.info.ver.unit.comm.web.action;

import jade.workflow.utils.ObjectUtil;

import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang.StringUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yh.component.dictionary.utils.DicHelper;
import com.yh.component.taglib.TableTagBean;
import com.yh.hr.info.ver.unit.comm.facade.PbDeathInfoFacade;
import com.yh.hr.info.ver.unit.comm.web.form.PbDeathInfoForm;
import com.yh.hr.res.dictionary.DicConstants;
import com.yh.hr.res.pb.dto.PbDeathInfoDTO;
import com.yh.platform.core.exception.ServiceException;
import com.yh.platform.core.util.BeanHelper;
import com.yh.platform.core.util.JSONHelper;
import com.yh.platform.core.util.SpringBeanUtil;
import com.yh.platform.core.util.StringUtil;
import com.yh.platform.core.web.action.BaseAction;

public class PbDeathInfoAction extends BaseAction {
	private PbDeathInfoFacade pbDeathInfoFacade = (PbDeathInfoFacade) SpringBeanUtil.getBean("pbDeathInfoFacade");

	//dto属性字典转换
	private void dtoDicMap(PbDeathInfoDTO dto) throws ServiceException {
		dto.setDeathType(DicHelper.viewName(DicConstants.YHRS0103,dto.getDeathType()));
    	dto.setDeathReason(DicHelper.viewName(DicConstants.YHRS0104,dto.getDeathReason()));
	}
	/**
	 * 列出所有 PbDeathInfo信息
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward listPbDeathInfo(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
		TableTagBean ttb = TableTagBean.getFromRequest(request);
		if (request.getMethod().equals("POST")) {
	        @SuppressWarnings("rawtypes")
			Map map = BeanUtils.describe(form);
	        ttb.getCondition().copyFrom(map, true);
	    } else {
	        BeanUtils.populate(form, ttb.getCondition());
	        request.setAttribute("pbDeathInfoForm", form);
	    }
        try {
	        List<PbDeathInfoDTO> list = pbDeathInfoFacade.find(ttb);
	        if(CollectionUtils.isNotEmpty(list)){
		        for(PbDeathInfoDTO dto : list){
		        	dtoDicMap(dto);
		        }
		        request.setAttribute("list", list);
	        }
        } catch (Exception se) {
			this.handleException(request, se, null);
			return mapping.findForward("fail");
		}
        return mapping.findForward("success");
	}
	
	/**
	 * 查找单个PbDeathInfo信息
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward show(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
        String personOid = request.getParameter("personOid");
        if (StringUtil.isBlank(personOid)) {
            personOid = ObjectUtil.getValue(request.getAttribute("personOid"), String.class);
        }
		try {
            if (StringUtils.isEmpty(personOid)) {
				throw new ServiceException("error.pk.invalid", "pbDeathInfo personOid is null");
			}
            PbDeathInfoDTO pbDeathInfoDto = pbDeathInfoFacade.get(ObjectUtil.getValue(personOid, java.lang.Long.class));
			if (null == pbDeathInfoDto) {
				throw new ServiceException(null, "查询不到相关信息");
			}
			dtoDicMap(pbDeathInfoDto);
			PbDeathInfoForm pbDeathInfoForm = BeanHelper.copyProperties(pbDeathInfoDto, PbDeathInfoForm.class);
			request.setAttribute("pbDeathInfoForm", pbDeathInfoForm);
            request.setAttribute("personOid", personOid);
		} catch (Exception se) {
			this.handleException(request, se, "personOid=" + personOid);
			return mapping.getInputForward();
		}
		return mapping.findForward("success");
	}

	/**
	 * 跳转到 PbDeathInfo信息添加页面
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward goCreate(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
		//参数校验，可根据实际情况修改
		try
		{
			String personOid = request.getParameter("personOid");
			String urlId = request.getParameter("urlId");
			if(StringUtils.isEmpty(personOid))
			{
				throw new ServiceException("personOid is null");
			}
			if(StringUtils.isEmpty(urlId))
			{
				throw new ServiceException("urlId is null");
			}
			request.setAttribute("personOid", personOid);
			request.setAttribute("urlId", urlId);
		}
		catch(Exception se)
		{
			this.handleException(request, se, null);
			return mapping.getInputForward();
		}
		return mapping.findForward(FORWARD_SUCCESS);
	}

	/**
	 * 添加 PbDeathInfo信息
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward create(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
		if (this.isCancelled(request)) {
			return mapping.findForward("cancel");
		}
		PbDeathInfoForm pbDeathInfoForm = (PbDeathInfoForm) form;
		try {
			TableTagBean ttb = TableTagBean.getFromRequest(request);
			ttb.getCondition().put("personOid", pbDeathInfoForm.getPersonOid().toString());
			@SuppressWarnings("rawtypes")
			List list = pbDeathInfoFacade.find(ttb);
			if(list!=null && list.size()>0) {
				throw new Exception("新增失败，该人员的自然减员信息已存在");
			}
//			if(StringUtils.isEmpty(${fkOid}))
//			{
//				throw new ServiceException("${fkOid} is null");
//			}
			PbDeathInfoDTO pbDeathInfoDto = BeanHelper.copyProperties(pbDeathInfoForm, PbDeathInfoDTO.class);
//			pbDeathInfoDto.setPersonOid(NumberUtils.longValue(personOid));
			pbDeathInfoFacade.create(pbDeathInfoDto);
			response.getWriter().write(JSONHelper.fromObject(true, null).toString());
		} catch (Exception se) {
			this.handleException(request, se, null);
			response.getWriter().write(JSONHelper.fromObject(false, StringUtils.defaultIfEmpty(se.getMessage(), "新增失败")).toString());
			return null;
		}

		return null;
	}


	/**
	 * 跳转到 PbDeathInfo信息修改（编辑）页面前的查询回显
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward goUpdate(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
		if(this.isCancelled(request)) {
			return mapping.findForward("cancel");
		}

        String personOid = request.getParameter("personOid");
        String urlId = request.getParameter("urlId");

		try {
            if (StringUtils.isBlank(personOid)) {
				throw new ServiceException("error.pk.invalid", "pbDeathInfo personOid is null");
			}
            PbDeathInfoDTO pbDeathInfoDto = pbDeathInfoFacade.get(ObjectUtil.getValue(personOid, java.lang.Long.class));
			if (null == pbDeathInfoDto) {
				throw new ServiceException("error.object.notfound", "pbDeathInfo not found by personOid");
			}
			PbDeathInfoForm pbDeathInfoForm = BeanHelper.copyProperties(pbDeathInfoDto, PbDeathInfoForm.class);
			request.setAttribute("pbDeathInfoForm", pbDeathInfoForm);
            request.setAttribute("personOid", personOid);
            request.setAttribute("urlId", urlId);
		} catch (Exception se) {
			this.handleException(request, se, "personOid=" + personOid);
			return mapping.getInputForward();
		}
		return goUpdateView(mapping, form, request, response);
	}

	/**
	 * 跳转到 PbDeathInfo信息修改（编辑）页面
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
    public ActionForward goUpdateView(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
        //add jsp init values
        @SuppressWarnings("unused")
		PbDeathInfoForm pbDeathInfoForm = (PbDeathInfoForm) form;
        return mapping.findForward("success");
    }

	/**
	 * 更新 PbDeathInfo信息
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward update(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
		if(this.isCancelled(request)) {
			return mapping.findForward("cancel");
		}
        String personOid = request.getParameter("personOid");
		PbDeathInfoForm pbDeathInfoForm = (PbDeathInfoForm) form;
		try {
            if (StringUtils.isBlank(personOid)) {
				throw new ServiceException("error.pk.invalid", "pbDeathInfo personOid is null");
			}
//			if(StringUtils.isEmpty(${fkOid}))
//			{
//				throw new ServiceException("${fkOid} is null");
//			}
			PbDeathInfoDTO pbDeathInfoDto = new PbDeathInfoDTO();
			BeanHelper.copyProperties(pbDeathInfoForm, pbDeathInfoDto);
			pbDeathInfoFacade.update(pbDeathInfoDto);
			response.getWriter().write(JSONHelper.fromObject(true, null).toString());
		} catch (Exception se) {
			this.handleException(request, se, pbDeathInfoForm);
			response.getWriter().write(JSONHelper.fromObject(false, StringUtils.defaultIfEmpty(se.getMessage(), "修改失败")).toString());
		}

		return null;
	}



	/**
	 * 删除 PbDeathInfo信息
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
    public ActionForward delete(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
           String personOid = request.getParameter("personOid");
        try {
           if(StringUtils.isEmpty(personOid))
			{
				throw new ServiceException(null, "personOid is null");
			}
            pbDeathInfoFacade.delete(ObjectUtil.getValue(personOid, java.lang.Long.class));
            response.getWriter().write(JSONHelper.fromObject(true, null).toString());
        } catch (Exception se) {
            this.handleException(request, se, "personOid=" + personOid);
            return mapping.getInputForward();
        }
        return null;
    }

}
