<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="com.yh.platform.core.constant.Constant"%>
<%@ page import="com.yh.hr.res.dictionary.DicConstants"%>
<%@ include file="/include/jsp_headers.jsp"%>

<!--
 * @function    PbDeathInfo修改页面
 * @page name   /hrinfo/ver/unit/comm/pbDeathInfo/verpb_pbDeathInfo_update.jsp
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-14
-->




<!DOCTYPE html>
<html lang="cn">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>自然减员信息修改页面</title>
    <script type="text/javascript" src="hrinfo/ver/unit/comm/pbdeathinfo/check_pbDeathInfo_info.js"></script>
	<script type="text/javascript" src="js/comm/customJs.js"></script>
</head>

<body>
<form id="deathInfoForm" class="form-inline" action="updatePbDeathInfo.do?method=update" method="post" onsubmit="return false">
  <div id="transaction_modal_box" class="transaction_modal_box">
    <div class="modal-dialog-container">
        <div class="md-title"> 自然减员信息&gt;修改<a href="#" class="md-close close-popdown"></a></div>
        <div class="md-error" style="display: none">
	        <p>以下信息有误,请重新输入</p>
	      </div>
        <div class="md-main-content">
          <input type="hidden" id="personOid" name="personOid" value="${personOid}" />
          <input type="hidden" id="url_id" value="${urlId}" />
          <div class="md-units md-three-column clearfix">
            <dl class="updown-dl">
              <dt>
                <b class="Required">* </b>死亡时间：
              </dt>
              <dd>
                <label>
                  <input type="text" name="deathDateStr" class="modal_iput" value="${pbDeathInfoForm.deathDateStr}" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd'});" />
                </label>
              </dd>
            </dl>
            <dl class="updown-dl">
              <dt>
                <b class="Required">* </b>死亡原因类别：
              </dt>
              <dd>
                <label>
                  <dictionary:dicItemSelect name="deathType" styleClass="modal_select" selected="${pbDeathInfoForm.deathType}" dicTypeCode="<%=DicConstants.YHRS0103%>" emptyText="--请选择--" />
                </label>
              </dd>
            </dl>
            <dl class="updown-dl">
              <dt>
                <b class="Required">* </b>死亡原因：
              </dt>
              <dd>
                <label>
                  <dictionary:dicItemSelect name="deathReason" styleClass="modal_select" selected="${pbDeathInfoForm.deathReason}" dicTypeCode="<%=DicConstants.YHRS0104%>" emptyText="--请选择--" />
                </label>
              </dd>
            </dl>
            <dl class="updown-dl">
              <dt>抚恤金：</dt>
              <dd>
                <label>
                  <input type="text" name="smartMoney" class="modal_iput" maxlength="10" value="<fmt:formatNumber value="${pbDeathInfoForm.smartMoney}" pattern="#.##" minFractionDigits="2"></fmt:formatNumber>"/>
                </label>
              </dd>
            </dl>
            <dl class="updown-dl">
              <dt>丧葬费：</dt>
              <dd>
                <label>
                  <input type="text" name="funeralMoney" class="modal_iput" maxlength="10" value="<fmt:formatNumber value="${pbDeathInfoForm.funeralMoney}" pattern="#.##" minFractionDigits="2"></fmt:formatNumber>"/>
                </label>
              </dd>
            </dl>
            <div class="clear"></div>
          </div>
          <div class="md-btn">
            <button id="saveDeathInfo" type="button" class="md-btn-save">保  存</button>
            <button type="button" class="md-btn-cancel close-popdown" data-dismiss="modal">取 消</button>
          </div>
        </div>
    </div>
  </div>
</form>
<%-- <div id="showmodal" class="modal-content">
<form id="deathInfoForm" class="form-inline" action="updatePbDeathInfo.do?method=update" method="post" onsubmit="return false">

    <div class="modal-header">
        <button type="button" class="close close-popdown" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">自然减员&gt;修改</h4>
    </div>

    <div class="modal-body">

        	<input type="hidden" id="familyOid" name="familyOid" value="${pbDeathInfoForm.familyOid}" />
			<input type="hidden" id="personOid" name="personOid" value="${pbDeathInfoForm.personOid}" />
            <input type="hidden" id="url_id" value="${urlId}" />
			<div class="modal-wrong" style="display: none">
                <ol class="titwrong"><embed src="img/index/jg.svg" width="20" height="20" top="0" type="image/svg+xml" class="ico"/> 以下信息有误，请重新输入！</ol>
                <ol class="wroglist">
                    <logic:messagesPresent>
                        <html:messages id="error">
                            <li><bean:write name="error" /></li>
                        </html:messages>
                    </logic:messagesPresent>
                </ol>
                <ol class="back-error"></ol>
            </div>
            
        	<div class="modal-row03">   <!--三列 -->
        	<dl>   
                    <dt><b class="Required">* </b>死亡时间：</dt>
			<dd>
				<label><input type="text" id="deathDateStr" name="deathDateStr" class="modal_iput" value="${pbDeathInfoForm.deathDateStr}" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd'});"/></label>
			</dd>
                 </dl>
        	<dl>   
                    	<dt><b class="Required">* </b>死亡原因类别：</dt>
			<dd>
				<label><dictionary:dicItemSelect id="deathType" name="deathType" styleClass="modal_select" selected="${pbDeathInfoForm.deathType}"
									dicTypeCode="<%=DicConstants.YHRS0103%>" emptyText="--请选择--" /></label>
			</dd>
                 </dl>
        	<dl>   
                    	<dt><b class="Required">* </b>死亡原因：</dt>
			<dd>
				<label><dictionary:dicItemSelect id="deathReason" name="deathReason" styleClass="modal_select" selected="${pbDeathInfoForm.deathReason}"
									dicTypeCode="<%=DicConstants.YHRS0104%>" emptyText="--请选择--" />
				</label>
			</dd>
                 </dl>
                 </div>
        	<div class="modal-row03">   <!--三列 -->
        	<dl>   
                    	<dt>抚恤金：</dt>
			<dd>
				<label><input type="text" id="smartMoney" name="smartMoney" class="modal_iput" value="<fmt:formatNumber value="${pbDeathInfoForm.smartMoney}" pattern="#.##" minFractionDigits="2"></fmt:formatNumber>"/></label>
			</dd>
                 </dl>
        	<dl>   
                    	<dt>丧葬费：</dt>
			<dd>
				<label><input type="text" id="funeralMoney" name="funeralMoney" class="modal_iput" value="<fmt:formatNumber value="${pbDeathInfoForm.funeralMoney}" pattern="#.##" minFractionDigits="2"></fmt:formatNumber>"/></label>
			</dd>
                 </dl>
            </div>
    </div>
    <div class="modal-footer">
    	<button id="saveDeathInfo" type="button" class="btn btn-primary">保　存</button>
    	<button type="button" class="btn btn-default close-popdown" data-dismiss="modal">取　消</button>
    </div>
    
    <div style="clear: both"></div>
    
</form>
</div> --%>
</body>
</html>