/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2017-07-12
**/
package com.yh.hr.res.im.bo;

import com.yh.platform.core.bo.BaseBo;

public class ImCheckPersonUnusual extends BaseBo {
	private static final long serialVersionUID = 796333714526596444L;

	private java.lang.Long  	checkPersonUnusualOid;	//主键OID
	private java.lang.Long  	checkPersonInfoOid;	//校核人员OID
	private java.lang.Long  	importBatchOid;	//导入批次OID
	private java.lang.String	checkType;	//检查类型	4：字典项检查	5：关联性检查	6：完整性检查
	private java.lang.String	databaseColumnCode;	//数据库字段代码
	private java.lang.String	databaseColumnName;	//数据库字段名称
	private java.lang.String	databaseColumnValue;	//数据库字段值
	private java.lang.String	checkStatus;	//检查状态	1：通过	0：未通过
	private java.lang.String	effectiveFlag;	//生效标识	1：生效	0：失效
	private java.lang.String	remark;	//备注

	public ImCheckPersonUnusual() {
		
	}

	public void setCheckPersonUnusualOid(java.lang.Long checkPersonUnusualOid){
		this.checkPersonUnusualOid = checkPersonUnusualOid;
	}

	public java.lang.Long getCheckPersonUnusualOid(){
		return this.checkPersonUnusualOid;
	}

	public void setCheckPersonInfoOid(java.lang.Long checkPersonInfoOid){
		this.checkPersonInfoOid = checkPersonInfoOid;
	}

	public java.lang.Long getCheckPersonInfoOid(){
		return this.checkPersonInfoOid;
	}

	public void setImportBatchOid(java.lang.Long importBatchOid){
		this.importBatchOid = importBatchOid;
	}

	public java.lang.Long getImportBatchOid(){
		return this.importBatchOid;
	}

	public void setCheckType(java.lang.String checkType){
		this.checkType = checkType;
	}

	public java.lang.String getCheckType(){
		return this.checkType;
	}

	public void setDatabaseColumnCode(java.lang.String databaseColumnCode){
		this.databaseColumnCode = databaseColumnCode;
	}

	public java.lang.String getDatabaseColumnCode(){
		return this.databaseColumnCode;
	}

	public void setDatabaseColumnName(java.lang.String databaseColumnName){
		this.databaseColumnName = databaseColumnName;
	}

	public java.lang.String getDatabaseColumnName(){
		return this.databaseColumnName;
	}

	public void setDatabaseColumnValue(java.lang.String databaseColumnValue){
		this.databaseColumnValue = databaseColumnValue;
	}

	public java.lang.String getDatabaseColumnValue(){
		return this.databaseColumnValue;
	}

	public void setCheckStatus(java.lang.String checkStatus){
		this.checkStatus = checkStatus;
	}

	public java.lang.String getCheckStatus(){
		return this.checkStatus;
	}

	public void setEffectiveFlag(java.lang.String effectiveFlag){
		this.effectiveFlag = effectiveFlag;
	}

	public java.lang.String getEffectiveFlag(){
		return this.effectiveFlag;
	}

	public void setRemark(java.lang.String remark){
		this.remark = remark;
	}

	public java.lang.String getRemark(){
		return this.remark;
	}

}
