/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2017-07-11
**/
package com.yh.hr.res.im.bo;

import com.yh.platform.core.bo.BaseBo;

public class ImDataUnusualLog extends BaseBo {
	private static final long serialVersionUID = 2472820846453380972L;

	private java.lang.Long  	dataUnusualOid;	//主键OID
	private java.lang.Long  	importBatchOid;	//导入批次OID
	private java.lang.String	checkType;	//检查类型	1：必填项检查	2：数据项检查	3：数据格式检查	4：字典项检查	5：关联性检查	6：完整性检查
	private java.lang.String	checkStatus;	//检查状态	1：通过	0：未通过
	private java.lang.Integer	checkNopassedAmount;	//检查未通过数据量

	public ImDataUnusualLog() {
		
	}

	public void setDataUnusualOid(java.lang.Long dataUnusualOid){
		this.dataUnusualOid = dataUnusualOid;
	}

	public java.lang.Long getDataUnusualOid(){
		return this.dataUnusualOid;
	}

	public void setImportBatchOid(java.lang.Long importBatchOid){
		this.importBatchOid = importBatchOid;
	}

	public java.lang.Long getImportBatchOid(){
		return this.importBatchOid;
	}

	public void setCheckType(java.lang.String checkType){
		this.checkType = checkType;
	}

	public java.lang.String getCheckType(){
		return this.checkType;
	}

	public void setCheckStatus(java.lang.String checkStatus){
		this.checkStatus = checkStatus;
	}

	public java.lang.String getCheckStatus(){
		return this.checkStatus;
	}

	public void setCheckNopassedAmount(java.lang.Integer checkNopassedAmount){
		this.checkNopassedAmount = checkNopassedAmount;
	}

	public java.lang.Integer getCheckNopassedAmount(){
		return this.checkNopassedAmount;
	}

}
