SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for yhc_ut_org
-- ----------------------------
DROP TABLE IF EXISTS `yhc_ut_org`;
CREATE TABLE `yhc_ut_org` (
  `ORGANIZATION_OID` bigint(20) NOT NULL,
  `ORG_OID` bigint(20) DEFAULT NULL,
  `ORG_NAME` varchar(100) DEFAULT NULL,
  `ORG_TYPE` varchar(20) DEFAULT NULL COMMENT '内设机构类型YHRS0102',
  `ORG_STATUS` varchar(20) DEFAULT NULL COMMENT '内设机构状态YHRS0101',
  `ORDER_OF_ALL` varchar(100) DEFAULT NULL COMMENT '内设机构全局排序',
  `HIERARCHY_CODE` varchar(30) DEFAULT NULL COMMENT '层级编码',
  `org_category` VARCHAR(20) DEFAULT NULL COMMENT '科室类别',
  `CREATED_BY_CODE` varchar(20) DEFAULT NULL,
  `CREATED_BY_NAME` varchar(100) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `UPDATED_BY_CODE` varchar(20) DEFAULT NULL,
  `UPDATED_BY_NAME` varchar(100) DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ORGANIZATION_OID`),
  CONSTRAINT `YHC_UT_ORG_O` FOREIGN KEY (`ORGANIZATION_OID`) REFERENCES `yhc_ut_organization` (`ORGANIZATION_OID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='内设机构中间表';

-- ----------------------------
-- Table structure for yhc_ut_organization
-- ----------------------------
DROP TABLE IF EXISTS `yhc_ut_organization`;
CREATE TABLE `yhc_ut_organization` (
  `ORGANIZATION_OID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ORGANIZATION_NAME` varchar(200) DEFAULT NULL,
  `ORGANIZATION_TYPE` varchar(20) DEFAULT NULL COMMENT '组织类型:1单位；2内设机构',
  `CREATED_BY_CODE` varchar(20) DEFAULT NULL,
  `CREATED_BY_NAME` varchar(100) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `UPDATED_BY_CODE` varchar(20) DEFAULT NULL,
  `UPDATED_BY_NAME` varchar(100) DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ORGANIZATION_OID`)
) ENGINE=InnoDB AUTO_INCREMENT=2617 DEFAULT CHARSET=utf8 COMMENT='组织信息表';

-- ----------------------------
-- Table structure for yhc_ut_relation
-- ----------------------------
DROP TABLE IF EXISTS `yhc_ut_relation`;
CREATE TABLE `yhc_ut_relation` (
  `RELATION_OID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `PARENT_ORGANIZATION_OID` bigint(20) NOT NULL,
  `CHILD_ORGANIZATION_OID` bigint(20) NOT NULL,
  `RELATION_TYPE` varchar(20) DEFAULT NULL COMMENT '关系类型',
  `CREATED_BY_CODE` varchar(20) DEFAULT NULL,
  `CREATED_BY_NAME` varchar(100) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `UPDATED_BY_CODE` varchar(20) DEFAULT NULL,
  `UPDATED_BY_NAME` varchar(100) DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`RELATION_OID`),
  KEY `YHC_UT_RELATION_C` (`CHILD_ORGANIZATION_OID`),
  KEY `YHC_UT_RELATION_P` (`PARENT_ORGANIZATION_OID`),
  CONSTRAINT `YHC_UT_RELATION_C` FOREIGN KEY (`CHILD_ORGANIZATION_OID`) REFERENCES `yhc_ut_organization` (`ORGANIZATION_OID`),
  CONSTRAINT `YHC_UT_RELATION_P` FOREIGN KEY (`PARENT_ORGANIZATION_OID`) REFERENCES `yhc_ut_organization` (`ORGANIZATION_OID`)
) ENGINE=InnoDB AUTO_INCREMENT=3503 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for yhc_ut_unit
-- ----------------------------
DROP TABLE IF EXISTS `yhc_ut_unit`;
CREATE TABLE `yhc_ut_unit` (
  `ORGANIZATION_OID` bigint(20) NOT NULL,
  `UNIT_OID` bigint(20) DEFAULT NULL,
  `UNIT_NAME` varchar(100) DEFAULT NULL COMMENT '单位名称',
  `UNIT_KIND` varchar(20) DEFAULT NULL COMMENT '单位性质YHRS0090',
  `UNIT_CATEGORY_CODE` varchar(20) DEFAULT NULL COMMENT '系统类别YHRS0091',
  `UNIT_LEVEL_CODE` varchar(20) DEFAULT NULL COMMENT '机构级别YHRS0093',
  `UNIT_AREA_CODE` varchar(20) DEFAULT NULL COMMENT '区域代码YHRS0006',
  `UNIT_STATUS` varchar(20) DEFAULT NULL COMMENT '单位状态YHRS0101',
  `UNIT_CODE` varchar(50) DEFAULT NULL,
  `ORDER_OF_ALL` varchar(100) DEFAULT NULL COMMENT '单位全局排序',
  `CREATED_BY_CODE` varchar(20) DEFAULT NULL,
  `CREATED_BY_NAME` varchar(100) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `UPDATED_BY_CODE` varchar(20) DEFAULT NULL,
  `UPDATED_BY_NAME` varchar(100) DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ORGANIZATION_OID`),
  CONSTRAINT `YHC_UT_UNIT_O` FOREIGN KEY (`ORGANIZATION_OID`) REFERENCES `yhc_ut_organization` (`ORGANIZATION_OID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='单位中间表';
CREATE INDEX IDX_UT_UNIT ON yhc_ut_unit (UNIT_OID);
CREATE INDEX IDX_UT_ORG ON yhc_ut_org (ORG_OID);