/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-08-17
 **/
package com.yh.hr.res.pb.dto;

import com.yh.platform.core.bo.BaseBo;

public class PbDutyLevelMappingDTO extends BaseBo {

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -3987263554809189175L;
	private java.lang.Long		mappingOid;									// MappingOid
	private java.lang.String	dutyLevelCode;									// DutyLevelCode
	private java.lang.Long		mappingLevel;									// MappingLevel
	private java.lang.String	dutyLevelName;									// DutyLevelName
	private java.lang.String	dutyLevelType;									// DutyLevelType
	private java.lang.String	dutyLevelJdCode;								// DutyLevelJdCode

	public void setMappingOid(java.lang.Long mappingOid) {
		this.mappingOid = mappingOid;
	}

	public java.lang.Long getMappingOid() {
		return this.mappingOid;
	}

	public void setDutyLevelCode(java.lang.String dutyLevelCode) {
		this.dutyLevelCode = dutyLevelCode;
	}

	public java.lang.String getDutyLevelCode() {
		return this.dutyLevelCode;
	}

	public void setMappingLevel(java.lang.Long mappingLevel) {
		this.mappingLevel = mappingLevel;
	}

	public java.lang.Long getMappingLevel() {
		return this.mappingLevel;
	}

	public void setDutyLevelName(java.lang.String dutyLevelName) {
		this.dutyLevelName = dutyLevelName;
	}

	public java.lang.String getDutyLevelName() {
		return this.dutyLevelName;
	}

	public void setDutyLevelType(java.lang.String dutyLevelType) {
		this.dutyLevelType = dutyLevelType;
	}

	public java.lang.String getDutyLevelType() {
		return this.dutyLevelType;
	}

	public void setDutyLevelJdCode(java.lang.String dutyLevelJdCode) {
		this.dutyLevelJdCode = dutyLevelJdCode;
	}

	public java.lang.String getDutyLevelJdCode() {
		return this.dutyLevelJdCode;
	}

}
