/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-13 
 */
package com.yh.hr.res.pb.dto;


public class PbEngageConHistInfoDTO {

	private java.lang.Long engageContractHistOid;        //主键ID
	private java.lang.Long personOid;        //人员ID
	private java.lang.String contractNo;        //合同编号
	private java.lang.String contractType;        //合同签订方式
	private java.lang.String changeType;        //合同类型
	private java.util.Date contractBegin;        //合同开始时间
	private java.lang.String contractBeginStr;        //合同开始时间字符串
	private java.util.Date contractEnd;        //合同截止时间
	private java.util.Date contractEndActual;        //合同实际结束日期
	private java.lang.String addressPermanant;        //常住住址
	private java.lang.String addressCommunication;        //通信地址
	private java.lang.String contactPhone;        //联系电话
	private java.util.Date signDate;        //合同签订时间
	private java.lang.String contractJob;        //工作岗位
	private java.lang.String others;        //其它事项
	private java.lang.String createBy;        //创建人ID
	private java.lang.String createName;        //创建人名称
	private java.util.Date createDate;        //创建时间
	private java.lang.String updateBy;        //修改人ID
	private java.lang.String updateName;        //修改人名称
	private java.util.Date updateDate;        //修改时间

	public void setEngageContractHistOid(java.lang.Long engageContractHistOid){
		this.engageContractHistOid = engageContractHistOid;
	}

	public java.lang.Long getEngageContractHistOid(){
		return this.engageContractHistOid;
	}
	public void setPersonOid(java.lang.Long personOid){
		this.personOid = personOid;
	}

	public java.lang.Long getPersonOid(){
		return this.personOid;
	}
	public void setContractNo(java.lang.String contractNo){
		this.contractNo = contractNo;
	}

	public java.lang.String getContractNo(){
		return this.contractNo;
	}
	public void setContractType(java.lang.String contractType){
		this.contractType = contractType;
	}

	public java.lang.String getContractType(){
		return this.contractType;
	}
	public void setChangeType(java.lang.String changeType){
		this.changeType = changeType;
	}

	public java.lang.String getChangeType(){
		return this.changeType;
	}
	public void setContractBegin(java.util.Date contractBegin){
		this.contractBegin = contractBegin;
	}

	public java.util.Date getContractBegin(){
		return this.contractBegin;
	}
	
	public java.lang.String getContractBeginStr() {
		return contractBeginStr;
	}

	public void setContractBeginStr(java.lang.String contractBeginStr) {
		this.contractBeginStr = contractBeginStr;
	}

	public void setContractEnd(java.util.Date contractEnd){
		this.contractEnd = contractEnd;
	}

	public java.util.Date getContractEnd(){
		return this.contractEnd;
	}
	public void setContractEndActual(java.util.Date contractEndActual){
		this.contractEndActual = contractEndActual;
	}

	public java.util.Date getContractEndActual(){
		return this.contractEndActual;
	}
	public void setAddressPermanant(java.lang.String addressPermanant){
		this.addressPermanant = addressPermanant;
	}

	public java.lang.String getAddressPermanant(){
		return this.addressPermanant;
	}
	public void setAddressCommunication(java.lang.String addressCommunication){
		this.addressCommunication = addressCommunication;
	}

	public java.lang.String getAddressCommunication(){
		return this.addressCommunication;
	}
	public void setContactPhone(java.lang.String contactPhone){
		this.contactPhone = contactPhone;
	}

	public java.lang.String getContactPhone(){
		return this.contactPhone;
	}
	public void setSignDate(java.util.Date signDate){
		this.signDate = signDate;
	}

	public java.util.Date getSignDate(){
		return this.signDate;
	}
	public void setContractJob(java.lang.String contractJob){
		this.contractJob = contractJob;
	}

	public java.lang.String getContractJob(){
		return this.contractJob;
	}
	public void setOthers(java.lang.String others){
		this.others = others;
	}

	public java.lang.String getOthers(){
		return this.others;
	}
	public void setCreateBy(java.lang.String createBy){
		this.createBy = createBy;
	}

	public java.lang.String getCreateBy(){
		return this.createBy;
	}
	public void setCreateName(java.lang.String createName){
		this.createName = createName;
	}

	public java.lang.String getCreateName(){
		return this.createName;
	}
	public void setCreateDate(java.util.Date createDate){
		this.createDate = createDate;
	}

	public java.util.Date getCreateDate(){
		return this.createDate;
	}
	public void setUpdateBy(java.lang.String updateBy){
		this.updateBy = updateBy;
	}

	public java.lang.String getUpdateBy(){
		return this.updateBy;
	}
	public void setUpdateName(java.lang.String updateName){
		this.updateName = updateName;
	}

	public java.lang.String getUpdateName(){
		return this.updateName;
	}
	public void setUpdateDate(java.util.Date updateDate){
		this.updateDate = updateDate;
	}

	public java.util.Date getUpdateDate(){
		return this.updateDate;
	}
}