/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-13 
 */
package com.yh.hr.res.pb.dto;

import com.yh.platform.core.util.DateUtil;


public class PbPoliticInfoDTO {

	private java.lang.Long politicOid;        //PoliticOid
	private java.lang.Long personOid;        //PersonOid
	private java.lang.String politicStatusCode;        //政治面貌
	private java.util.Date joinPoliticDate;        //参加党派时间
	private java.lang.String joinPoliticDateStr;        //参加党派时间
	private java.lang.String unitOfJoinParty;        //参加党派时所在单位
	private java.lang.String introducer;        //介绍人
	private java.util.Date probationDate;        //转正时间
	private java.lang.String probationDateStr;        //转正时间
	private java.lang.String politicDutyCode;        //党内职务名称
	private java.util.Date outPartyDate;        //离党日期
	private java.lang.String outPartyDateStr;        //离党日期
	private java.lang.String abnormityType;        //异常事项类别
	private java.lang.String abnormityReason;        //异常事项原因
	private java.lang.String remark;        //备注
	private java.lang.String createBy;        //创建人ID
	private java.lang.String createName;        //创建人名称
	private java.util.Date createDate;        //创建时间
	private java.lang.String updateBy;        //修改人ID
	private java.lang.String updateName;        //修改人名称
	private java.util.Date updateDate;        //修改时间
	public java.lang.Long getPoliticOid() {
		return politicOid;
	}
	public void setPoliticOid(java.lang.Long politicOid) {
		this.politicOid = politicOid;
	}
	public java.lang.Long getPersonOid() {
		return personOid;
	}
	public void setPersonOid(java.lang.Long personOid) {
		this.personOid = personOid;
	}
	public java.lang.String getPoliticStatusCode() {
		return politicStatusCode;
	}
	public void setPoliticStatusCode(java.lang.String politicStatusCode) {
		this.politicStatusCode = politicStatusCode;
	}
	public java.util.Date getJoinPoliticDate() {
		return joinPoliticDate;
	}
	public void setJoinPoliticDate(java.util.Date joinPoliticDate) {
		this.joinPoliticDate = joinPoliticDate;
		if(joinPoliticDate!=null){
			this.joinPoliticDateStr = DateUtil.formatDate(joinPoliticDate);
		}
	}
	public java.lang.String getJoinPoliticDateStr() {
		return joinPoliticDateStr;
	}
	public void setJoinPoliticDateStr(java.lang.String joinPoliticDateStr) {
		this.joinPoliticDateStr = joinPoliticDateStr;
		if(joinPoliticDateStr!=null){
			this.joinPoliticDate = DateUtil.parseDate(joinPoliticDateStr);
		}
	}
	public java.lang.String getUnitOfJoinParty() {
		return unitOfJoinParty;
	}
	public void setUnitOfJoinParty(java.lang.String unitOfJoinParty) {
		this.unitOfJoinParty = unitOfJoinParty;
	}
	public java.lang.String getIntroducer() {
		return introducer;
	}
	public void setIntroducer(java.lang.String introducer) {
		this.introducer = introducer;
	}
	public java.util.Date getProbationDate() {
		return probationDate;
	}
	public void setProbationDate(java.util.Date probationDate) {
		this.probationDate = probationDate;
		if(probationDate!=null){
			this.probationDateStr = DateUtil.formatDate(probationDate);
		}
	}
	public java.lang.String getProbationDateStr() {
		return probationDateStr;
	}
	public void setProbationDateStr(java.lang.String probationDateStr) {
		this.probationDateStr = probationDateStr;
		if(probationDateStr!=null){
			this.probationDate = DateUtil.parseDate(probationDateStr);
		}
	}
	public java.lang.String getPoliticDutyCode() {
		return politicDutyCode;
	}
	public void setPoliticDutyCode(java.lang.String politicDutyCode) {
		this.politicDutyCode = politicDutyCode;
	}
	public java.util.Date getOutPartyDate() {
		return outPartyDate;
	}
	public void setOutPartyDate(java.util.Date outPartyDate) {
		this.outPartyDate = outPartyDate;
		if(outPartyDate!=null){
			this.outPartyDateStr = DateUtil.formatDate(outPartyDate);
		}
	}
	public java.lang.String getOutPartyDateStr() {
		return outPartyDateStr;
	}
	public void setOutPartyDateStr(java.lang.String outPartyDateStr) {
		this.outPartyDateStr = outPartyDateStr;
		if(outPartyDateStr!=null){
			this.outPartyDate = DateUtil.parseDate(outPartyDateStr);
		}
	}
	public java.lang.String getAbnormityType() {
		return abnormityType;
	}
	public void setAbnormityType(java.lang.String abnormityType) {
		this.abnormityType = abnormityType;
	}
	public java.lang.String getAbnormityReason() {
		return abnormityReason;
	}
	public void setAbnormityReason(java.lang.String abnormityReason) {
		this.abnormityReason = abnormityReason;
	}
	public java.lang.String getRemark() {
		return remark;
	}
	public void setRemark(java.lang.String remark) {
		this.remark = remark;
	}
	public java.lang.String getCreateBy() {
		return createBy;
	}
	public void setCreateBy(java.lang.String createBy) {
		this.createBy = createBy;
	}
	public java.lang.String getCreateName() {
		return createName;
	}
	public void setCreateName(java.lang.String createName) {
		this.createName = createName;
	}
	public java.util.Date getCreateDate() {
		return createDate;
	}
	public void setCreateDate(java.util.Date createDate) {
		this.createDate = createDate;
	}
	public java.lang.String getUpdateBy() {
		return updateBy;
	}
	public void setUpdateBy(java.lang.String updateBy) {
		this.updateBy = updateBy;
	}
	public java.lang.String getUpdateName() {
		return updateName;
	}
	public void setUpdateName(java.lang.String updateName) {
		this.updateName = updateName;
	}
	public java.util.Date getUpdateDate() {
		return updateDate;
	}
	public void setUpdateDate(java.util.Date updateDate) {
		this.updateDate = updateDate;
	}


}