/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-13 
 */
package com.yh.hr.res.pb.dto;

import org.apache.commons.lang.StringUtils;

import com.yh.platform.core.util.DateUtil;


public class PbResumeInfoDTO {

	private java.lang.Long resumeOid;        //工作简历OID
	private java.lang.Long personOid;        //PersonOid
	private java.util.Date startDate;        //开始时间
	private String startDateStr;
	private java.util.Date endDate;        //截止时间
	private String endDateStr;
	private java.lang.String unit;        //工作单位
	private java.lang.String duty;        //职务
	private java.lang.String remark;        //备注
	private java.lang.String createBy;        //创建人ID
	private java.lang.String createName;        //创建人名称
	private java.util.Date createDate;        //创建时间
	private String createDateStr;
	private java.lang.String updateBy;        //修改人ID
	private java.lang.String updateName;        //修改人名称
	private java.util.Date updateDate;        //修改时间
	private String updateDateStr;

	public void setResumeOid(java.lang.Long resumeOid){
		this.resumeOid = resumeOid;
	}

	public java.lang.Long getResumeOid(){
		return this.resumeOid;
	}
	public void setPersonOid(java.lang.Long personOid){
		this.personOid = personOid;
	}

	public java.lang.Long getPersonOid(){
		return this.personOid;
	}
	public void setStartDate(java.util.Date startDate){
		this.startDate = startDate;
		if(null != startDate){
			this.startDateStr = DateUtil.format(startDate, "yyyy-MM-dd");
         }
	}

	public java.util.Date getStartDate(){
		return this.startDate;
	}
    public void setStartDateStr(String startDateStr){
        this.startDateStr = startDateStr;
        if(StringUtils.isNotEmpty(startDateStr)){
               this.startDate = DateUtil.parse(startDateStr, "yyyy-MM-dd");
        }
    }

    public String getStartDateStr(){
        return this.startDateStr;
    }
    public void setEndDate(java.util.Date endDate){
		this.endDate = endDate;
		if(null != endDate){
			this.endDateStr = DateUtil.format(endDate, "yyyy-MM-dd");
         }
	}

	public java.util.Date getEndDate(){
		return this.endDate;
	}
    public void setEndDateStr(String endDateStr){
        this.endDateStr = endDateStr;
        if(StringUtils.isNotEmpty(endDateStr)){
               this.endDate = DateUtil.parse(endDateStr, "yyyy-MM-dd");
        }
    }

    public String getEndDateStr(){
        return this.endDateStr;
    }
	public void setUnit(java.lang.String unit){
		this.unit = unit;
	}

	public java.lang.String getUnit(){
		return this.unit;
	}
	public void setDuty(java.lang.String duty){
		this.duty = duty;
	}

	public java.lang.String getDuty(){
		return this.duty;
	}
	public void setRemark(java.lang.String remark){
		this.remark = remark;
	}

	public java.lang.String getRemark(){
		return this.remark;
	}
	public void setCreateBy(java.lang.String createBy){
		this.createBy = createBy;
	}

	public java.lang.String getCreateBy(){
		return this.createBy;
	}
	public void setCreateName(java.lang.String createName){
		this.createName = createName;
	}

	public java.lang.String getCreateName(){
		return this.createName;
	}
	public void setCreateDate(java.util.Date createDate){
		this.createDate = createDate;
		if(null != createDate){
			this.createDateStr = DateUtil.format(createDate, "yyyy-MM-dd");
         }
	}

	public java.util.Date getCreateDate(){
		return this.createDate;
	}
    public void setCreateDateStr(String createDateStr){
        this.createDateStr = createDateStr;
        if(StringUtils.isNotEmpty(createDateStr)){
               this.createDate = DateUtil.parse(createDateStr, "yyyy-MM-dd");
        }
    }

    public String getCreateDateStr(){
        return this.createDateStr;
    }
    public void setUpdateBy(java.lang.String updateBy){
		this.updateBy = updateBy;
	}

	public java.lang.String getUpdateBy(){
		return this.updateBy;
	}
    public void setUpdateName(java.lang.String updateName){
		this.updateName = updateName;
	}

	public java.lang.String getUpdateName(){
		return this.updateName;
	}
    public void setUpdateDate(java.util.Date updateDate){
		this.updateDate = updateDate;
		if(null != updateDate){
			this.updateDateStr = DateUtil.format(updateDate, "yyyy-MM-dd");
         }
	}

	public java.util.Date getUpdateDate(){
		return this.updateDate;
	}
    public void setUpdateDateStr(String updateDateStr){
        this.updateDateStr = updateDateStr;
        if(StringUtils.isNotEmpty(updateDateStr)){
               this.updateDate = DateUtil.parse(updateDateStr, "yyyy-MM-dd");
        }
    }

    public String getUpdateDateStr(){
        return this.updateDateStr;
    }
}