/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-08-15
 **/
package com.yh.hr.info.ver.unit.person.facade;

import com.yh.hr.info.ver.unit.person.dto.VerPbPersonInfoDTO;
import com.yh.hr.res.pb.dto.PbPersonInfoDTO;
import com.yh.hr.res.pb.service.PbImageService;
import com.yh.hr.res.pb.service.PbPersonInfoService;
import com.yh.hr.res.unit.service.UtOrgService;
import com.yh.hr.res.unit.service.UtUnitService;
import com.yh.platform.core.exception.ServiceException;
import com.yh.platform.core.util.BeanHelper;

/**
 * @desc 人员基础信息校核门面层，目前主要用于控制事务
 * @author luqy
 * @createDate 2016-8-15下午04:26:31
 */
public class VerPbPersonInfoFacade {
	private PbPersonInfoService	pbPersonInfoService;
	private UtUnitService	    utUnitService;
	private UtOrgService utOrgService;
	private PbImageService		pbImageService;

	public void setPbImageService(PbImageService pbImageService) {
		this.pbImageService = pbImageService;
	}

	public void setUtUnitService(UtUnitService utUnitService) {
		this.utUnitService = utUnitService;
	}
	
	public void setPbPersonInfoService(PbPersonInfoService pbPersonInfoService) {
		this.pbPersonInfoService = pbPersonInfoService;
	}
	public void setUtOrgService(UtOrgService utOrgService) {
		this.utOrgService = utOrgService;
	}
	/*
	 * 人员基础信息新增
	 */
	public void addVerPersonInfo(VerPbPersonInfoDTO verPbPersonInfoDTO) throws ServiceException {
		Long personOid=pbPersonInfoService.addPbPersonInfo(BeanHelper.copyProperties(verPbPersonInfoDTO,PbPersonInfoDTO.class));
		if(null!=verPbPersonInfoDTO.getImage()&&null!=personOid)
		{
			this.pbImageService.insertOrUpdateImage(verPbPersonInfoDTO.getImage(), personOid);
		}
	}
	
	/*
	 * 人员基础信息更新
	 */
	public void updateVerPersonInfo(VerPbPersonInfoDTO verPbPersonInfoDTO) throws ServiceException {
		this.pbPersonInfoService.updatePbPersonInfo(BeanHelper.copyProperties(verPbPersonInfoDTO, PbPersonInfoDTO.class));
		if(null!=verPbPersonInfoDTO.getImage())
		{
			this.pbImageService.insertOrUpdateImage(verPbPersonInfoDTO.getImage(), verPbPersonInfoDTO.getPersonOid());
		}
	}

	/*
	 * 人员基础信息删除
	 */
	public void deleteVerPbPersonInfoById(Long personOid) throws ServiceException {
		this.pbPersonInfoService.deletePbPersonInfoById(personOid);
	}

	/*
	 * 人员基础信息查询
	 */
	public VerPbPersonInfoDTO getVerPersonInfoById(Long personOid) throws ServiceException {
		VerPbPersonInfoDTO verPbPersonInfoDTO = BeanHelper.copyProperties(this.pbPersonInfoService.getPbPersonInfoDTOById(personOid), VerPbPersonInfoDTO.class);
		return verPbPersonInfoDTO;
	}

	/*
	 * 获取单位名称
	 */
	public String getUnitName(Long unitOid) throws ServiceException {
		return utUnitService.getUnitName(unitOid);
	}
    /**
     * 查询部门名称
     * @param deptOid
     * @return
     * @throws ServiceException 
     */
	public String getOrgName(Long deptOid) throws ServiceException {
		return utOrgService.getOrgName(deptOid);
	}
}
