/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-08-23
**/
package com.yh.admin.dto;

public class MenuItemDTO {
	
	private java.lang.Long	id;	//菜单主键
	private java.lang.String	name;	//菜单名称
	private java.lang.String	title;	//菜单KEY
	private java.lang.String	description;	//菜单描述
	private java.lang.String	location;	//菜单地址
	private java.lang.String	target;	//Target
	private java.lang.String	action;	//Action
	private java.lang.String	systemCode;	//菜单所属系统
	private java.lang.Long	parentId;	//上级菜单ID
	private java.lang.String	parentName;	//上级菜单名称
	private java.lang.Long	orderSeq;	//菜单显示序号
	private java.lang.String	image;	//菜单图片
	
	public MenuItemDTO() {
		
	}

	public void setId(java.lang.Long id){
		this.id = id;
	}

	public java.lang.Long getId(){
		return this.id;
	}

	public void setName(java.lang.String name){
		this.name = name;
	}

	public java.lang.String getName(){
		return this.name;
	}

	public void setTitle(java.lang.String title){
		this.title = title;
	}

	public java.lang.String getTitle(){
		return this.title;
	}

	public void setDescription(java.lang.String description){
		this.description = description;
	}

	public java.lang.String getDescription(){
		return this.description;
	}

	public void setLocation(java.lang.String location){
		this.location = location;
	}

	public java.lang.String getLocation(){
		return this.location;
	}

	public void setTarget(java.lang.String target){
		this.target = target;
	}

	public java.lang.String getTarget(){
		return this.target;
	}

	public void setAction(java.lang.String action){
		this.action = action;
	}

	public java.lang.String getAction(){
		return this.action;
	}

	public void setSystemCode(java.lang.String systemCode){
		this.systemCode = systemCode;
	}

	public java.lang.String getSystemCode(){
		return this.systemCode;
	}

	public void setParentId(java.lang.Long parentId){
		this.parentId = parentId;
	}

	public java.lang.Long getParentId(){
		return this.parentId;
	}

	public void setParentName(java.lang.String parentName){
		this.parentName = parentName;
	}

	public java.lang.String getParentName(){
		return this.parentName;
	}

	public void setOrderSeq(java.lang.Long orderSeq){
		this.orderSeq = orderSeq;
	}

	public java.lang.Long getOrderSeq(){
		return this.orderSeq;
	}

	public java.lang.String getImage() {
		return image;
	}

	public void setImage(java.lang.String image) {
		this.image = image;
	}

}
