/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-08-23
**/
package com.yh.admin.dto;

/**
 * 
 * @author	zhangqp
 * @version	1.0,	16/08/24
 */
public class ResourcesDTO {
	
	private java.lang.Long	resId;	//资源表主键
	private java.lang.String	resName;	//资源名称
	private java.lang.String	resType;	//资源类型
	private java.lang.String	resValue;	//资源值
	private java.lang.String	resDesc;	//资源描述
	private java.lang.String	systemCode;	//资源所属系统

	public void setResId(java.lang.Long resId){
		this.resId = resId;
	}

	public java.lang.Long getResId(){
		return this.resId;
	}

	public void setResName(java.lang.String resName){
		this.resName = resName;
	}

	public java.lang.String getResName(){
		return this.resName;
	}

	public void setResType(java.lang.String resType){
		this.resType = resType;
	}

	public java.lang.String getResType(){
		return this.resType;
	}

	public void setResValue(java.lang.String resValue){
		this.resValue = resValue;
	}

	public java.lang.String getResValue(){
		return this.resValue;
	}

	public void setResDesc(java.lang.String resDesc){
		this.resDesc = resDesc;
	}

	public java.lang.String getResDesc(){
		return this.resDesc;
	}

	public void setSystemCode(java.lang.String systemCode){
		this.systemCode = systemCode;
	}

	public java.lang.String getSystemCode(){
		return this.systemCode;
	}

}
