/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-08-31
**/
package com.yh.hr.component.infotemplate.dto;

public class ItLibraryGroupDTO {

	private java.lang.Long		libraryGroupOid;	//主键
	private java.lang.Long		parentGroupOid;	
	public java.lang.Long getParentGroupOid() {
		return parentGroupOid;
	}

	public void setParentGroupOid(java.lang.Long parentGroupOid) {
		this.parentGroupOid = parentGroupOid;
	}

	private java.lang.String	libraryGroupName;	//资源组名称
	private java.lang.String	createdByCode;	//CreatedByCode
	private java.lang.String	createdByName;	//CreatedByName
	private java.util.Date		createdDate;	//CreatedDate
	private java.lang.String	updatedByCode;	//UpdatedByCode
	private java.lang.String	updatedByName;	//UpdatedByName
	private java.util.Date		updatedDate;	//UpdatedDate

	public ItLibraryGroupDTO() {
		
	}

	public void setLibraryGroupOid(java.lang.Long libraryGroupOid){
		this.libraryGroupOid = libraryGroupOid;
	}

	public java.lang.Long getLibraryGroupOid(){
		return this.libraryGroupOid;
	}

	public void setLibraryGroupName(java.lang.String libraryGroupName){
		this.libraryGroupName = libraryGroupName;
	}

	public java.lang.String getLibraryGroupName(){
		return this.libraryGroupName;
	}

	public void setCreatedByCode(java.lang.String createdByCode){
		this.createdByCode = createdByCode;
	}

	public java.lang.String getCreatedByCode(){
		return this.createdByCode;
	}

	public void setCreatedByName(java.lang.String createdByName){
		this.createdByName = createdByName;
	}

	public java.lang.String getCreatedByName(){
		return this.createdByName;
	}

	public void setCreatedDate(java.util.Date createdDate){
		this.createdDate = createdDate;
	}

	public java.util.Date getCreatedDate(){
		return this.createdDate;
	}

	public void setUpdatedByCode(java.lang.String updatedByCode){
		this.updatedByCode = updatedByCode;
	}

	public java.lang.String getUpdatedByCode(){
		return this.updatedByCode;
	}

	public void setUpdatedByName(java.lang.String updatedByName){
		this.updatedByName = updatedByName;
	}

	public java.lang.String getUpdatedByName(){
		return this.updatedByName;
	}

	public void setUpdatedDate(java.util.Date updatedDate){
		this.updatedDate = updatedDate;
	}

	public java.util.Date getUpdatedDate(){
		return this.updatedDate;
	}

}
