<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="com.yh.platform.core.constant.Constant"%>
<%@ page import="com.yh.hr.res.dictionary.DicConstants"%>
<%@ include file="/include/jsp_headers.jsp"%>

<!--
 * @function    PbRetrieInfo新增页面
 * @page name   /hrinfo/ver/verPb_PbRetrieInfo_create.jsp
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-14
-->






<!DOCTYPE html>
<html lang="cn">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>离退休信息新增页面</title>
    <script type="text/javascript" src="hrinfo/ver/unit/comm/pbretrieinfo/check_retrie_info.js"></script>
	<script type="text/javascript" src="js/comm/customJs.js"></script>
</head>

<body>
<form id="retrieInfoForm" class="form-inline" action="createPbRetrieInfo.do?method=create" method="post" onsubmit="return false">
  <div id="transaction_modal_box" class="transaction_modal_box">
    <div class="modal-dialog-container">
      <div class="md-title">离退休信息&gt;新增<a href="#" class="md-close close-popdown"></a></div>
      <div class="md-error" style="display: none">
        <p>以下信息有误,请重新输入</p>
      </div>
      <div class="md-main-content">
        <input type="hidden" id="personOid" name="personOid" value="${personOid}" />
        <input type="hidden" id="url_id" value="${urlId}" />
        <div class="md-units md-three-column clearfix">
	        <dl class="updown-dl">
	          <dt><b class="Required">* </b>离退类别：</dt>
	          <dd>
	            <label>
	              <dictionary:dicItemSelect name="retrieTypeCode" styleClass="modal_select" dicTypeCode="<%=DicConstants.YHRS0057%>" emptyText="--请选择--" />
	            </label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>离退日期：</dt>
	          <dd>
	            <label><input type="text" name="retrieDateStr" class="modal_iput"  onfocus="WdatePicker({dateFmt:'yyyy-MM-dd'});" /></label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>提前退休原因：</dt>
	          <dd>
	            <label>
	              <dictionary:dicItemSelect name="retrieReason" styleClass="modal_select" dicTypeCode="<%=DicConstants.YHRS0058%>" emptyText="--请选择--" />
	            </label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>离退后享受待遇级别：</dt>
	          <dd>
	            <label>
	              <dictionary:dicItemSelect name="retireTreatmentLevelCode" styleClass="modal_select" dicTypeCode="<%=DicConstants.YHRS0015%>" emptyText="--请选择--" />
	            </label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>离退后享受待遇类别：</dt>
	          <dd>
	            <label>
	              <dictionary:dicItemSelect name="retireTreatmentTypeCode" styleClass="modal_select" dicTypeCode="<%=DicConstants.YHRS0109%>" emptyText="--请选择--" />
	            </label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>离退休费比例：</dt>
	          <dd>
	            <label><input type="text" name="retireFeeRatio" class="modal_iput" maxlength="10" /></label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>离退休补助比例：</dt>
	          <dd>
	            <label><input type="text" name="retireAllowanceRatio" class="modal_iput" maxlength="10" /></label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>离退休费支付单位：</dt>
	          <dd>
	            <label>
	              <dictionary:dicItemSelect name="retirtPaymentUnit" styleClass="modal_select" dicTypeCode="<%=DicConstants.YHRS0059%>" emptyText="--请选择--" />
	            </label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>离退休后管理单位：</dt>
	          <dd>
	            <label><input type="text" name="retireManageUnit" class="modal_iput" maxlength="100" /></label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>离退休批准机关：</dt>
	          <dd>
	            <label><input type="text" name="retritApproveUnit" class="modal_iput" maxlength="100" /></label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>离退休批准文号：</dt>
	          <dd>
							<label><input type="text" name="retrieApproveFileno" class="modal_iput" maxlength="50" /></label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>离退休证号：</dt>
	          <dd>
	            <label><input type="text" name="retireNo" class="modal_iput" maxlength="50" /></label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>有害工种增加工龄：</dt>
	          <dd>
	            <label><input type="number" name="serviceYearsAdded" class="modal_iput" maxlength="3"/></label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>特殊贡献比例：</dt>
	          <dd>
	            <label><input type="text" name="specialContributionRatio" class="modal_iput" maxlength="10" /></label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>特殊贡献标志：</dt>
	          <dd>
	            <label>
	              <dictionary:dicItemSelect name="specialContributionFlag" styleClass="modal_select" dicTypeCode="<%=DicConstants.YHRS0003%>" emptyText="--请选择--" />
	            </label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>归侨加发比例：</dt>
	          <dd>
	            <label><input type="text" name="returnedOverseasChiScale" class="modal_iput" maxlength="10" /></label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>归国华侨标志：</dt>
	          <dd>
	            <label>
	              <dictionary:dicItemSelect name="returnedOverseasFlag" styleClass="modal_select" dicTypeCode="<%=DicConstants.YHRS0003%>" emptyText="--请选择--" />
	            </label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>是否终身无子女：</dt>
	          <dd>
	            <label>
	              <dictionary:dicItemSelect name="isNoChildForLife" styleClass="modal_select" dicTypeCode="<%=DicConstants.YHRS0003%>" emptyText="--请选择--" />
	            </label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">
	          <dt>审批类型：</dt>
	          <dd>
	            <label>
	              <dictionary:dicItemSelect name="approvalType" styleClass="modal_select" dicTypeCode="<%=DicConstants.YHRS0060%>" emptyText="--请选择--" />
	            </label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>审查科室：</dt>
	          <dd>
	            <label><input type="text" name="approvalUnit" class="modal_iput" maxlength="100" /></label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>符合条例：</dt>
	          <dd>
	            <label>
	              <%-- <dictionary:dicItemSelect name="compliedClause" styleClass="modal_select" dicTypeCode="<%=DicConstants.YHRS0061%>" emptyText="--请选择--" /> --%>
	            	<input type="text" name="compliedClause" class="modal_iput" maxlength="100" />
	            </label>
	          </dd>
	        </dl>
	        <dl class="updown-dl">   
	          <dt>计生奖励：</dt>
	            <dd>
								<label><input type="text" name="familyPlanningAward" class="modal_iput" maxlength="50" /></label>
							</dd>
	        </dl>
	        <dl class="updown-remark">
	          <dt>备注：</dt>
							<dd style="width:83%;">
								<label><textarea rows="3" name="remark" maxlength="1000"></textarea></label>
							</dd>
	        </dl>
	        <div class="clear"></div>
        </div>
      </div>
    </div>
    <div class="md-btn">
      <button id="saveRetrieInfo" type="button" class="md-btn-save">保  存</button>
      <button type="button" class="md-btn-cancel close-popdown" data-dismiss="modal">取 消</button>
    </div>
  </div>
</form>
</body>
</html>