/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-09-01
 **/
package com.yh.hr.component.worktop.bo;

import com.yh.platform.core.bo.BaseBo;

public class WbTemplate extends BaseBo {
	/**
	 * 
	 */
	private static final long serialVersionUID = 3916781793201388080L;
	private java.lang.String templateCode; //
	private java.lang.String templateName; //
	private java.lang.String templateType; //
	private java.lang.String templateUrl;
	private java.lang.String createdByCode; // CreatedByCode
	private java.lang.String createdByName; // CreatedByName
	private java.util.Date createdDate; // CreatedDate
	private java.lang.String updatedByCode; // UpdatedByCode
	private java.lang.String updatedByName; // UpdatedByName
	private java.util.Date updatedDate; // UpdatedDate

	public WbTemplate() {

	}

	public java.lang.String getTemplateCode() {
		return templateCode;
	}

	public void setTemplateCode(java.lang.String templateCode) {
		this.templateCode = templateCode;
	}

	public java.lang.String getTemplateName() {
		return templateName;
	}

	public void setTemplateName(java.lang.String templateName) {
		this.templateName = templateName;
	}

	public java.lang.String getTemplateType() {
		return templateType;
	}

	public void setTemplateType(java.lang.String templateType) {
		this.templateType = templateType;
	}

	public java.lang.String getTemplateUrl() {
		return templateUrl;
	}

	public void setTemplateUrl(java.lang.String templateUrl) {
		this.templateUrl = templateUrl;
	}

	public void setCreatedByCode(java.lang.String createdByCode) {
		this.createdByCode = createdByCode;
	}

	public java.lang.String getCreatedByCode() {
		return this.createdByCode;
	}

	public void setCreatedByName(java.lang.String createdByName) {
		this.createdByName = createdByName;
	}

	public java.lang.String getCreatedByName() {
		return this.createdByName;
	}

	public void setCreatedDate(java.util.Date createdDate) {
		this.createdDate = createdDate;
	}

	public java.util.Date getCreatedDate() {
		return this.createdDate;
	}

	public void setUpdatedByCode(java.lang.String updatedByCode) {
		this.updatedByCode = updatedByCode;
	}

	public java.lang.String getUpdatedByCode() {
		return this.updatedByCode;
	}

	public void setUpdatedByName(java.lang.String updatedByName) {
		this.updatedByName = updatedByName;
	}

	public java.lang.String getUpdatedByName() {
		return this.updatedByName;
	}

	public void setUpdatedDate(java.util.Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public java.util.Date getUpdatedDate() {
		return this.updatedDate;
	}

}
