insert into YHB_SYSTEM_POSITION (SYSTEM_POSITION_OID, SYSTEM_POSITION_NAME, SYSTEM_POSITION_DESC, DATA_ROLE_ID, FUNCTION_ROLE_ID, DEPT_CODE, CREATED_BY_CODE, CREATED_BY_NAME, CREATED_DATE, UPDATED_BY_CODE, UPDATED_BY_NAME, UPDATED_DATE)
values (1, '超级管理员岗位', '超级管理员岗位', 3, 1, null, 'admin', '超级管理员', now(), 'admin', '超级管理员', now());
commit;