/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-13
 */
package com.yh.hr.res.pb.service;

import com.yh.component.taglib.TableTagBean;
import com.yh.hr.res.pb.dto.PbEngageConHistInfoDTO;
import com.yh.platform.core.exception.ServiceException;
import com.yh.platform.core.util.StringMap;

import java.util.HashMap;
import java.util.List;


public interface PbEngageConHistInfoService {
	/**
	 * 新增PbEngageConHistInfo信息
	 * @param 
	 * @throws ServiceException
	 */
	public void create(PbEngageConHistInfoDTO pbEngageConHistInfoDto) throws ServiceException;

	/**
	 * 获取PbEngageConHistInfo信息
	 * @param 
	 * @throws ServiceException
	 */
	public PbEngageConHistInfoDTO get(java.lang.Long pbEngageConHistInfoId) throws ServiceException;
    
	/**
	 * 修改PbEngageConHistInfo信息
	 * @param 
	 * @throws ServiceException
	 */    
	public void update(PbEngageConHistInfoDTO pbEngageConHistInfoDto) throws ServiceException;

	/**
	 * 删除PbEngageConHistInfo信息
	 * @param 
	 * @throws ServiceException
	 */    
	public void delete(java.lang.Long pbEngageConHistInfoId) throws ServiceException;
    
	/**
	 * 查询所有PbEngageConHistInfo信息
	 * @param 
	 * @throws ServiceException
	 */
	public List<PbEngageConHistInfoDTO> find(TableTagBean ttb) throws ServiceException; 

	/**
	 * HQL拼装
	 * @param 
	 * @throws ServiceException
	 */
    void buildHQL(StringMap params, StringBuilder hql, HashMap<String, Object> hqlParams) throws ServiceException;
    public boolean checkContractNo(PbEngageConHistInfoDTO pbEngageConHistInfoDto) throws ServiceException;

	/**
	 * 用人员id查找该人员的合同历史信息
	 * @param personOid
	 * @return
	 * @throws ServiceException
	 */
	public List<PbEngageConHistInfoDTO> listPbEngageConHistInfoByPersonOid(Long personOid) throws ServiceException;

	/**
	 * 删除该人员的所有合同历史信息
	 * @param personOid
	 * @throws ServiceException
	 */
	public void deleteByPersonOid(Long personOid) throws ServiceException;
}
