/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-03-20
 */
package com.yh.hr.res.pb.service;

import java.util.List;

import com.yh.hr.res.pb.dto.PbPersonOutDTO;
import com.yh.platform.core.exception.ServiceException;


public interface PbPersonOutService {
	/**
	 * 新增PbPersonOut信息
	 * @param 
	 * @throws ServiceException
	 */
	public void create(PbPersonOutDTO PbPersonOutDto) throws ServiceException;

	/**
	 * 获取PbPersonOut信息
	 * @param 
	 * @throws ServiceException
	 */
	public PbPersonOutDTO get(java.lang.Long PbPersonOutId) throws ServiceException;
    
	/**
	 * 修改PbPersonOut信息
	 * @param 
	 * @throws ServiceException
	 */    
	public void update(PbPersonOutDTO PbPersonOutDto) throws ServiceException;

	/**
	 * 删除PbPersonOut信息
	 * @param 
	 * @throws ServiceException
	 */    
	public void delete(java.lang.Long PbPersonOutId) throws ServiceException;

	public List<PbPersonOutDTO> listPbPersonOutByPersonOid(Long longValue) throws ServiceException;

	/**
	 * 根据人员ID查询人员离开信息
	 * @param personOid
	 * @return
	 * @throws ServiceException
	 */
	public PbPersonOutDTO findByPersonOid(Long personOid)throws ServiceException;

	/**
	 * 删除该人员的离开信息
	 * @param personOid
	 * @throws ServiceException
	 */
	public void deleteByPersonOid(Long personOid)throws ServiceException;
    

      
}
