/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-10
 */
package com.yh.hr.res.pb.service;

import java.util.List;

import com.yh.component.taglib.TableTagBean;
import com.yh.hr.res.pb.dto.PbQualificationsInfoDTO;
import com.yh.platform.core.exception.ServiceException;


public interface PbQualificationsInfoService {
	/**
	 * 新增PbQualificationsInfo信息
	 * @param 
	 * @throws ServiceException
	 */
	public void create(PbQualificationsInfoDTO pbQualificationsInfoDto) throws ServiceException;

	/**
	 * 获取PbQualificationsInfo信息
	 * @param 
	 * @throws ServiceException
	 */
	public PbQualificationsInfoDTO get(java.lang.Long pbQualificationsInfoId) throws ServiceException;
    
	/**
	 * 修改PbQualificationsInfo信息
	 * @param 
	 * @throws ServiceException
	 */    
	public void update(PbQualificationsInfoDTO pbQualificationsInfoDto) throws ServiceException;

	/**
	 * 删除PbQualificationsInfo信息
	 * @param 
	 * @throws ServiceException
	 */    
	public void delete(java.lang.Long pbQualificationsInfoId) throws ServiceException;
    
	/**
	 * 查询所有PbQualificationsInfo信息
	 * @param 
	 * @throws ServiceException
	 */
	public List<PbQualificationsInfoDTO> find(TableTagBean ttb) throws ServiceException; 
    
    /**
	 * 根据人员id查询执业（职业）资格信息
	 * @param longValue
	 * @return ServiceException
	 */
	public List<PbQualificationsInfoDTO> listQualificationsInfoByPersonOid(Long personOid) throws ServiceException;

	/**
	 * 删除该人员的所有职业资格信息
	 * @param personOid
	 * @throws ServiceException
	 */
	public void deleteByPersonOid(Long personOid) throws ServiceException;
      
}
