/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-10
 */
package com.yh.hr.res.pb.service;

import java.util.HashMap;
import java.util.List;

import com.yh.component.taglib.TableTagBean;
import com.yh.hr.res.pb.dto.PbSyGwEmployInfoDTO;
import com.yh.platform.core.exception.ServiceException;
import com.yh.platform.core.util.StringMap;


public interface PbSyGwEmployInfoService {
	/**
	 * 新增PbSyGwEmployInfo信息
	 * @param 
	 * @throws ServiceException
	 */
	public void create(PbSyGwEmployInfoDTO pbSyGwEmployInfoDto) throws ServiceException;

	/**
	 * 获取PbSyGwEmployInfo信息
	 * @param 
	 * @throws ServiceException
	 */
	public PbSyGwEmployInfoDTO get(java.lang.Long pbSyGwEmployInfoId) throws ServiceException;
    
	/**
	 * 修改PbSyGwEmployInfo信息
	 * @param 
	 * @throws ServiceException
	 */    
	public void update(PbSyGwEmployInfoDTO pbSyGwEmployInfoDto) throws ServiceException;

	/**
	 * 删除PbSyGwEmployInfo信息
	 * @param 
	 * @throws ServiceException
	 */    
	public void delete(java.lang.Long pbSyGwEmployInfoId) throws ServiceException;
    
	/**
	 * 查询所有PbSyGwEmployInfo信息
	 * @param 
	 * @throws ServiceException
	 */
	public List<PbSyGwEmployInfoDTO> find(TableTagBean ttb) throws ServiceException; 

	/**
	 * HQL拼装
	 * @param 
	 * @throws ServiceException
	 */
    void buildHQL(StringMap params, StringBuilder hql, HashMap<String, Object> hqlParams) throws ServiceException;
    /**
     * 验证
     * @param pbSyGwEmployInfoDTO
     * @return
     * @throws ServiceException
     */
    public String check(PbSyGwEmployInfoDTO pbSyGwEmployInfoDTO) throws ServiceException;
    /**
	 * 根据人员id查询该人员所有的事业岗位聘任信息
	 * @param personOid
	 * @return
	 * @throws ServiceException
	 */
	public List<PbSyGwEmployInfoDTO> listPbSyGwEmployInfoByPersonOid(Long personOid) throws ServiceException;

}
