/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-11-03
**/
package com.yh.hr.res.pt.bo;

import com.yh.platform.core.bo.BaseBo;

public class PtPersonAttach extends BaseBo {
	private static final long serialVersionUID = 3870012131022346171L;

	private java.lang.Long  	bizPersonOid;	//业务信息附属同步信息，查询使用
	private java.lang.String	administrativeDutyType;	//职务类别YHRS0027
	private java.lang.String	administrativeDuty;	//职务
	private java.lang.String	administrativeDutyLevel;	//职务级别YHRS0015
	private java.util.Date  	administrativeDutyDate;	//现任最高职务开始时间
	private java.util.Date  	administrativeStartDate;	//职务级别起始时间
	private java.lang.String	administrativeDutyAttribute;	//现任最高职务的职务属性YHRS0028
	private java.lang.String	administrativeIsMajorDuty;	//是否领导职务YHRS0003
	private java.lang.String	sDuty;	//辅职务名称
	private java.lang.String	sDutyLevel;	//辅职务级别YHRS0015
	private java.util.Date  	sDutyDate;	//辅职务开始时间
	private java.util.Date  	sStartDate;	//辅职务级别起始时间
	private java.lang.String	sDutyAttribute;	//辅职务属性
	private java.lang.String	sPositionName;	//辅岗位名称
	private java.lang.String	isTwoDuty;	//是否双肩挑YHRS0003
	private java.lang.String	mPositionName;	//主岗位名称
	private java.lang.String	ftSchoolName;	//全日制最高学校名称
	private java.lang.String	mPositionType;	//现聘岗位类别（主）YHRS0022
	private java.lang.String	mPositionLevel;	//现聘岗位级别（主）YHRS0023
	private java.lang.String	ftMajorName;	//全日制最高专业名称
	private java.util.Date  	mPositionLevelDate;	//现聘岗位级别起始时间（主）
	private java.lang.String	ftEducationLevelCode;	//全日制最高学历代码YHRS0039
	private java.lang.String	sPositionType;	//现聘岗位类别（副）YHRS0022
	private java.lang.String	sPositionLevel;	//现聘岗位级别（副）YHRS0023
	private java.lang.String	ftDegreeCode;	//全日制最高学位代码YHRS0040
	private java.util.Date  	sPositionLevelDate;	//现聘岗位级别起始时间（副）
	private java.lang.String	ojSchoolName;	//在职最高学校名称
	private java.lang.String	ojMajorName;	//在职最高专业名称
	private java.lang.String	ojEducationLevelCode;	//在职最高学历代码YHRS0039
	private java.lang.String	ojDegreeCode;	//在职最高学位代码YHRS0040
	
	private java.lang.String	ftAcademyName;	//全日制最高所在院系
	private java.lang.String	ojAcademyName;	//在职最高所在院系
	
	public java.lang.Long getBizPersonOid() {
		return bizPersonOid;
	}

	public void setBizPersonOid(java.lang.Long bizPersonOid) {
		this.bizPersonOid = bizPersonOid;
	}

	public java.lang.String getAdministrativeDutyType() {
		return administrativeDutyType;
	}

	public void setAdministrativeDutyType(
			java.lang.String administrativeDutyType) {
		this.administrativeDutyType = administrativeDutyType;
	}

	public java.lang.String getAdministrativeDuty() {
		return administrativeDuty;
	}

	public void setAdministrativeDuty(java.lang.String administrativeDuty) {
		this.administrativeDuty = administrativeDuty;
	}

	public java.lang.String getAdministrativeDutyLevel() {
		return administrativeDutyLevel;
	}

	public void setAdministrativeDutyLevel(
			java.lang.String administrativeDutyLevel) {
		this.administrativeDutyLevel = administrativeDutyLevel;
	}

	public java.util.Date getAdministrativeDutyDate() {
		return administrativeDutyDate;
	}

	public void setAdministrativeDutyDate(java.util.Date administrativeDutyDate) {
		this.administrativeDutyDate = administrativeDutyDate;
	}

	public java.util.Date getAdministrativeStartDate() {
		return administrativeStartDate;
	}

	public void setAdministrativeStartDate(
			java.util.Date administrativeStartDate) {
		this.administrativeStartDate = administrativeStartDate;
	}

	public java.lang.String getAdministrativeDutyAttribute() {
		return administrativeDutyAttribute;
	}

	public void setAdministrativeDutyAttribute(
			java.lang.String administrativeDutyAttribute) {
		this.administrativeDutyAttribute = administrativeDutyAttribute;
	}

	public java.lang.String getAdministrativeIsMajorDuty() {
		return administrativeIsMajorDuty;
	}

	public void setAdministrativeIsMajorDuty(
			java.lang.String administrativeIsMajorDuty) {
		this.administrativeIsMajorDuty = administrativeIsMajorDuty;
	}

	public java.lang.String getsDuty() {
		return sDuty;
	}

	public void setsDuty(java.lang.String sDuty) {
		this.sDuty = sDuty;
	}

	public java.lang.String getsDutyLevel() {
		return sDutyLevel;
	}

	public void setsDutyLevel(java.lang.String sDutyLevel) {
		this.sDutyLevel = sDutyLevel;
	}

	public java.util.Date getsDutyDate() {
		return sDutyDate;
	}

	public void setsDutyDate(java.util.Date sDutyDate) {
		this.sDutyDate = sDutyDate;
	}

	public java.util.Date getsStartDate() {
		return sStartDate;
	}

	public void setsStartDate(java.util.Date sStartDate) {
		this.sStartDate = sStartDate;
	}

	public java.lang.String getsDutyAttribute() {
		return sDutyAttribute;
	}

	public void setsDutyAttribute(java.lang.String sDutyAttribute) {
		this.sDutyAttribute = sDutyAttribute;
	}

	public java.lang.String getsPositionName() {
		return sPositionName;
	}

	public void setsPositionName(java.lang.String sPositionName) {
		this.sPositionName = sPositionName;
	}

	public java.lang.String getIsTwoDuty() {
		return isTwoDuty;
	}

	public void setIsTwoDuty(java.lang.String isTwoDuty) {
		this.isTwoDuty = isTwoDuty;
	}

	public java.lang.String getmPositionName() {
		return mPositionName;
	}

	public void setmPositionName(java.lang.String mPositionName) {
		this.mPositionName = mPositionName;
	}

	public java.lang.String getFtSchoolName() {
		return ftSchoolName;
	}

	public void setFtSchoolName(java.lang.String ftSchoolName) {
		this.ftSchoolName = ftSchoolName;
	}

	public java.lang.String getmPositionType() {
		return mPositionType;
	}

	public void setmPositionType(java.lang.String mPositionType) {
		this.mPositionType = mPositionType;
	}

	public java.lang.String getmPositionLevel() {
		return mPositionLevel;
	}

	public void setmPositionLevel(java.lang.String mPositionLevel) {
		this.mPositionLevel = mPositionLevel;
	}

	public java.lang.String getFtMajorName() {
		return ftMajorName;
	}

	public void setFtMajorName(java.lang.String ftMajorName) {
		this.ftMajorName = ftMajorName;
	}

	public java.util.Date getmPositionLevelDate() {
		return mPositionLevelDate;
	}

	public void setmPositionLevelDate(java.util.Date mPositionLevelDate) {
		this.mPositionLevelDate = mPositionLevelDate;
	}

	public java.lang.String getFtEducationLevelCode() {
		return ftEducationLevelCode;
	}

	public void setFtEducationLevelCode(java.lang.String ftEducationLevelCode) {
		this.ftEducationLevelCode = ftEducationLevelCode;
	}

	public java.lang.String getsPositionType() {
		return sPositionType;
	}

	public void setsPositionType(java.lang.String sPositionType) {
		this.sPositionType = sPositionType;
	}

	public java.lang.String getsPositionLevel() {
		return sPositionLevel;
	}

	public void setsPositionLevel(java.lang.String sPositionLevel) {
		this.sPositionLevel = sPositionLevel;
	}

	public java.lang.String getFtDegreeCode() {
		return ftDegreeCode;
	}

	public void setFtDegreeCode(java.lang.String ftDegreeCode) {
		this.ftDegreeCode = ftDegreeCode;
	}

	public java.util.Date getsPositionLevelDate() {
		return sPositionLevelDate;
	}

	public void setsPositionLevelDate(java.util.Date sPositionLevelDate) {
		this.sPositionLevelDate = sPositionLevelDate;
	}

	public java.lang.String getOjSchoolName() {
		return ojSchoolName;
	}

	public void setOjSchoolName(java.lang.String ojSchoolName) {
		this.ojSchoolName = ojSchoolName;
	}

	public java.lang.String getOjMajorName() {
		return ojMajorName;
	}

	public void setOjMajorName(java.lang.String ojMajorName) {
		this.ojMajorName = ojMajorName;
	}

	public java.lang.String getOjEducationLevelCode() {
		return ojEducationLevelCode;
	}

	public void setOjEducationLevelCode(java.lang.String ojEducationLevelCode) {
		this.ojEducationLevelCode = ojEducationLevelCode;
	}

	public java.lang.String getOjDegreeCode() {
		return ojDegreeCode;
	}

	public void setOjDegreeCode(java.lang.String ojDegreeCode) {
		this.ojDegreeCode = ojDegreeCode;
	}

	public java.lang.String getFtAcademyName() {
		return ftAcademyName;
	}

	public void setFtAcademyName(java.lang.String ftAcademyName) {
		this.ftAcademyName = ftAcademyName;
	}

	public java.lang.String getOjAcademyName() {
		return ojAcademyName;
	}

	public void setOjAcademyName(java.lang.String ojAcademyName) {
		this.ojAcademyName = ojAcademyName;
	}
	
}
