/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-11-16
**/
package com.yh.hr.res.pt.bo;

import com.yh.platform.core.bo.BaseBo;

public class PtRecruitment extends BaseBo {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7122586319741387958L;
	private java.lang.Long  	bizPersonOid;	//BizPersonOid
	private java.lang.String	jobName;		//招考职位名称
	private java.lang.String	examineeType;		//考生类型
	private java.lang.String	writtenRecord;		//笔试成绩
	private java.lang.String	interviewResult;	//面试成绩
	private java.lang.String	inspectionResult;	//考察结果
	private java.lang.String	createdByCode;	//CreatedByCode
	private java.lang.String	createdByName;	//CreatedByName
	private java.util.Date  	createdDate;	//CreatedDate
	private java.lang.String	updatedByCode;	//UpdatedByCode
	private java.lang.String	updatedByName;	//UpdatedByName
	private java.util.Date  	updatedDate;	//UpdatedDate

	public PtRecruitment() {
		
	}

	public java.lang.String getJobName() {
		return jobName;
	}

	public void setJobName(java.lang.String jobName) {
		this.jobName = jobName;
	}

	public java.lang.String getExamineeType() {
		return examineeType;
	}

	public void setExamineeType(java.lang.String examineeType) {
		this.examineeType = examineeType;
	}

	public java.lang.String getWrittenRecord() {
		return writtenRecord;
	}

	public void setWrittenRecord(java.lang.String writtenRecord) {
		this.writtenRecord = writtenRecord;
	}

	public java.lang.String getInterviewResult() {
		return interviewResult;
	}

	public void setInterviewResult(java.lang.String interviewResult) {
		this.interviewResult = interviewResult;
	}

	public java.lang.String getInspectionResult() {
		return inspectionResult;
	}

	public void setInspectionResult(java.lang.String inspectionResult) {
		this.inspectionResult = inspectionResult;
	}

	public void setBizPersonOid(java.lang.Long bizPersonOid){
		this.bizPersonOid = bizPersonOid;
	}

	public java.lang.Long getBizPersonOid(){
		return this.bizPersonOid;
	}

	
	public void setCreatedByCode(java.lang.String createdByCode){
		this.createdByCode = createdByCode;
	}

	public java.lang.String getCreatedByCode(){
		return this.createdByCode;
	}

	public void setCreatedByName(java.lang.String createdByName){
		this.createdByName = createdByName;
	}

	public java.lang.String getCreatedByName(){
		return this.createdByName;
	}

	public void setCreatedDate(java.util.Date createdDate){
		this.createdDate = createdDate;
	}

	public java.util.Date getCreatedDate(){
		return this.createdDate;
	}

	public void setUpdatedByCode(java.lang.String updatedByCode){
		this.updatedByCode = updatedByCode;
	}

	public java.lang.String getUpdatedByCode(){
		return this.updatedByCode;
	}

	public void setUpdatedByName(java.lang.String updatedByName){
		this.updatedByName = updatedByName;
	}

	public java.lang.String getUpdatedByName(){
		return this.updatedByName;
	}

	public void setUpdatedDate(java.util.Date updatedDate){
		this.updatedDate = updatedDate;
	}

	public java.util.Date getUpdatedDate(){
		return this.updatedDate;
	}

}
