<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="com.yh.platform.core.constant.Constant"%>
<%@ page import="com.yh.hr.res.dictionary.DicConstants"%>
<%@ include file="/include/jsp_headers.jsp"%>

<!--
 * @function    特殊授权信息查看页面
 * @page name   /hrinfo/view/view_ver_pbSpeciaAuth_show.jsp
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-14
-->



<!DOCTYPE html>
<html lang="cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>特殊授权情况查看页面</title>
<style type="text/css">
dd {
	white-space: nowrap;
	overflow: hidden;
	text-overflow: ellipsis;
}
</style>
</head>

<body>
	<form id="pbSpeciaAuthForm" action="#" method="post">
		<div id="transaction_modal_box" class="transaction_modal_box">
			<div class="modal-dialog-container">
				<div class="md-title">
					特殊授权情况&gt;查看<a href="#" class="md-close close-popdown"></a>
				</div>
				<div class="md-main-content">
					<div class="md-units md-three-column clearfix">
						<dl class="data-unit-dl">
							<dt>权限类型：</dt>
							<dd>
								<label title='<dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0120%>" dicItemCode="${pbSpeciaAuthForm.authType}" />'><dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0120%>" dicItemCode="${pbSpeciaAuthForm.authType}" />&nbsp;</label> 
<%-- 								<label title='<bean:write name="pbSpeciaAuthForm" property="authType" />'><bean:write name="pbSpeciaAuthForm" property="authType" />&nbsp;</label> --%>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>授权级别：</dt>
							<dd>
								<label title='<dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0119%>" dicItemCode="${pbSpeciaAuthForm.authLevel}" />'><dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0119%>" dicItemCode="${pbSpeciaAuthForm.authLevel}" />&nbsp;</label> 
<%-- 								<label title='<bean:write name="pbSpeciaAuthForm" property="authLevel" />'><bean:write name="pbSpeciaAuthForm" property="authLevel" />&nbsp;</label> --%>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>授权状态：</dt>
							<dd>
								<label title='<dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0121%>" dicItemCode="${pbSpeciaAuthForm.authStatus}" />'><dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0121%>" dicItemCode="${pbSpeciaAuthForm.authStatus}" />&nbsp;</label> 
<%-- 								<label title='<bean:write name="pbSpeciaAuthForm" property="authStatus" />'><bean:write name="pbSpeciaAuthForm" property="authStatus" />&nbsp;</label> --%>
							</dd>
						</dl>
						<%-- <dl class="data-unit-dl">
							<dt>创建人ID：</dt>
							<dd>
								<label title='<bean:write name="pbSpeciaAuthForm" property="createBy" />'><bean:write name="pbSpeciaAuthForm" property="createBy" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>创建人名称：</dt>
							<dd>
								<label title='<bean:write name="pbSpeciaAuthForm" property="createName" />'><bean:write name="pbSpeciaAuthForm" property="createName" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>创建时间：</dt>
							<dd>
								<label title='<bean:write name="pbSpeciaAuthForm" property="createDateStr" />'><bean:write name="pbSpeciaAuthForm" property="createDateStr" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>修改人ID：</dt>
							<dd>
								<label title='<bean:write name="pbSpeciaAuthForm" property="updateBy" />'><bean:write name="pbSpeciaAuthForm" property="updateBy" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>修改人名称：</dt>
							<dd>
								<label title='<bean:write name="pbSpeciaAuthForm" property="updateName" />'><bean:write name="pbSpeciaAuthForm" property="updateName" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>修改时间：</dt>
							<dd>
								<label title='<bean:write name="pbSpeciaAuthForm" property="updateDateStr" />'><bean:write name="pbSpeciaAuthForm" property="updateDateStr" />&nbsp;</label>
							</dd>
						</dl> --%>
						
						<dl class="data-unit-dl"> 
	                    	<dt>授权时间：</dt>
							<dd>
								<label title="<bean:write name="pbSpeciaAuthForm" property="authDateStr" />"><bean:write name="pbSpeciaAuthForm" property="authDateStr" />&nbsp;</label>
							</dd>
                 		</dl>
			        	<dl class="data-unit-dl"> 
				            <dt>取消授权时间：</dt>
							<dd>
								<label title="<bean:write name="pbSpeciaAuthForm" property="cancelAuthDateStr" />"><bean:write name="pbSpeciaAuthForm" property="cancelAuthDateStr" />&nbsp;</label>
							</dd>
	                    </dl>
		                <dl class="data-unit-dl updown-remark">
	                     	<dt>备注：</dt>
							<dd>
								<label title="<bean:write name="pbSpeciaAuthForm" property="cancelAuthDateStr" />"><bean:write name="pbSpeciaAuthForm" property="cancelAuthDateStr" />&nbsp;</label>
							</dd>
                 		</dl>
					</div>
				</div>
				<div class="md-btn">
					<button type="button" class="md-btn-cancel close-popdown" data-dismiss="modal" button-click="widget-close">关 闭</button>
				</div>
			</div>
		</div>
	</form>
</body>
</html>