/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-08-15
**/
package com.yh.hr.info.ver.unit.comm.dto;


public class VerPbPunishmentInfoDTO {
	
	/**
     *主键
     **/
	private java.lang.Long punishmentOid;
    /**
     *PersonOid
     **/
	private java.lang.Long personOid;
    /**
     *处分名称YHRS0081
     **/
	private java.lang.String punishmentCode;
	/**
	 * 奖惩情况
	 */
	private java.lang.String jcqk;

	/**
     *处分原因YHRS0082
     **/
	private java.lang.String punishmentReasonCode;
    /**
     *处分批准日期
     **/
	private java.util.Date punishmentDate;
	//private String punishmentDateStr;
    /*public String getPunishmentDateStr() {
		return punishmentDateStr;
	}

	public void setPunishmentDateStr(String punishmentDateStr) throws DateParseException {
		if(!StringUtils.isEmpty(punishmentDateStr)){
			this.punishmentDate = DateUtil.parseDate(punishmentDateStr);
			this.punishmentDateStr = punishmentDateStr;
		}
		else
			punishmentDateStr ="";
	}
*/
	/**
     *处分原因类别YHRS0083
     **/
	private java.lang.String punishmentReasonType;
    /**
     *处分原因描述
     **/
	private java.lang.String punishmentReasonDesc;
    /**
     *处分批准机关名称
     **/
	private java.lang.String punishmentApprovalUnit;
    /**
     *处分批准机关类别YHRS0084
     **/
	private java.lang.String punishmentApprovalType;
    /**
     *处分文号
     **/
	private java.lang.String punishmentFileno;
    /**
     *处分是否撤销标识YHRS0003
     **/
	private java.lang.String isCancalPunishment;
    /**
     *处分撤销机关
     **/
	private java.lang.String cancalPunishmentUnit;
    /**
     *处分撤销文号
     **/
	private java.lang.String cancalPunishmentFileno;
    /**
     *处分撤销日期
     **/
	private java.util.Date cancalPunishmentDate;
	//private String cancalPunishmentDateStr;
    

	/**
     *处分撤销原因
     **/
	private java.lang.String cancalPunishmentReason;
    /**
     *是否影响工资标志YHRS0003
     **/
	private java.lang.String isInfectionWage;
    /**
     *备注
     **/
	private java.lang.String remark;
    /**
     *降级后薪级
     **/
	private java.lang.Long salaryLevel;
    /**
     *处分期限（月）
     **/
	private java.lang.Long punishmentMonth;
    /**
     *处分截止日期
     **/
	private java.util.Date punishmentEndDate;
	//private String punishmentEndDateStr;
   

	/**
     *解除处分日期
     **/
	private java.util.Date unchainPunishmentDate;
	//private String unchainPunishmentDateStr;
  

	/**
     *解除处分文号
     **/
	private java.lang.String unchainPunishmentFileno;
    /**
     *解除处分批准机关名称
     **/
	private java.lang.String endApprovalUnit;
    /**
     *解除处分批准机关类别YHRS0084
     **/
	private java.lang.String endApprovalType;
    /**
     *处分实际截止日期
     **/
	private java.util.Date endPunishmentDateActual;
	//private String endPunishmentDateActualStr;
   

	/**
     *CreatedByCode
     **/
	private java.lang.String createdByCode;
    /**
     *CreatedByName
     **/
	private java.lang.String createdByName;
    /**
     *CreatedDate
     **/
	private java.util.Date createdDate;
    /**
     *UpdatedByCode
     **/
	private java.lang.String updatedByCode;
    /**
     *UpdatedByName
     **/
	private java.lang.String updatedByName;
    /**
     *UpdatedDate
     **/
	private java.util.Date updatedDate;


/**
* public JhcPbPunishmentInfo(java.lang.Long punishmentOid) {
*  *       this.punishmentOid = punishmentOid;
**   }
**/
	public void setPunishmentOid(java.lang.Long punishmentOid){
		this.punishmentOid = punishmentOid;
	}

	public java.lang.Long getPunishmentOid(){
		return this.punishmentOid;
	}

	public void setPersonOid(java.lang.Long personOid){
		this.personOid = personOid;
	}

	public java.lang.String getJcqk() {
		return jcqk;
	}
	
	public void setJcqk(java.lang.String jcqk) {
		this.jcqk = jcqk;
	}
	public java.lang.Long getPersonOid(){
		return this.personOid;
	}
	/*public String getCancalPunishmentDateStr() {
		return cancalPunishmentDateStr;
	}

	public void setCancalPunishmentDateStr(String cancalPunishmentDateStr) throws DateParseException {
		if(!StringUtils.isEmpty(cancalPunishmentDateStr)){
			this.cancalPunishmentDate = DateUtil.parseDate(cancalPunishmentDateStr);
			this.cancalPunishmentDateStr = cancalPunishmentDateStr;
		}
		else
			cancalPunishmentDateStr = "";
	}*/
	public void setPunishmentCode(java.lang.String punishmentCode){
		this.punishmentCode = punishmentCode;
	}

	public java.lang.String getPunishmentCode(){
		return this.punishmentCode;
	}

	public void setPunishmentReasonCode(java.lang.String punishmentReasonCode){
		this.punishmentReasonCode = punishmentReasonCode;
	}

	public java.lang.String getPunishmentReasonCode(){
		return this.punishmentReasonCode;
	}

	public void setPunishmentDate(java.util.Date punishmentDate){
		this.punishmentDate = punishmentDate;
	}

	public java.util.Date getPunishmentDate(){
		return this.punishmentDate;
	}

	public void setPunishmentReasonType(java.lang.String punishmentReasonType){
		this.punishmentReasonType = punishmentReasonType;
	}

	public java.lang.String getPunishmentReasonType(){
		return this.punishmentReasonType;
	}

	public void setPunishmentReasonDesc(java.lang.String punishmentReasonDesc){
		this.punishmentReasonDesc = punishmentReasonDesc;
	}

	public java.lang.String getPunishmentReasonDesc(){
		return this.punishmentReasonDesc;
	}

	public void setPunishmentApprovalUnit(java.lang.String punishmentApprovalUnit){
		this.punishmentApprovalUnit = punishmentApprovalUnit;
	}

	public java.lang.String getPunishmentApprovalUnit(){
		return this.punishmentApprovalUnit;
	}

	public void setPunishmentApprovalType(java.lang.String punishmentApprovalType){
		this.punishmentApprovalType = punishmentApprovalType;
	}

	public java.lang.String getPunishmentApprovalType(){
		return this.punishmentApprovalType;
	}

	public void setPunishmentFileno(java.lang.String punishmentFileno){
		this.punishmentFileno = punishmentFileno;
	}

	public java.lang.String getPunishmentFileno(){
		return this.punishmentFileno;
	}

	public void setIsCancalPunishment(java.lang.String isCancalPunishment){
		this.isCancalPunishment = isCancalPunishment;
	}

	public java.lang.String getIsCancalPunishment(){
		return this.isCancalPunishment;
	}

	public void setCancalPunishmentUnit(java.lang.String cancalPunishmentUnit){
		this.cancalPunishmentUnit = cancalPunishmentUnit;
	}

	public java.lang.String getCancalPunishmentUnit(){
		return this.cancalPunishmentUnit;
	}

	public void setCancalPunishmentFileno(java.lang.String cancalPunishmentFileno){
		this.cancalPunishmentFileno = cancalPunishmentFileno;
	}

	public java.lang.String getCancalPunishmentFileno(){
		return this.cancalPunishmentFileno;
	}

	public void setCancalPunishmentDate(java.util.Date cancalPunishmentDate){
		this.cancalPunishmentDate = cancalPunishmentDate;
	}

	public java.util.Date getCancalPunishmentDate(){
		return this.cancalPunishmentDate;
	}

	public void setCancalPunishmentReason(java.lang.String cancalPunishmentReason){
		this.cancalPunishmentReason = cancalPunishmentReason;
	}

	public java.lang.String getCancalPunishmentReason(){
		return this.cancalPunishmentReason;
	}

	public void setIsInfectionWage(java.lang.String isInfectionWage){
		this.isInfectionWage = isInfectionWage;
	}

	public java.lang.String getIsInfectionWage(){
		return this.isInfectionWage;
	}

	public void setRemark(java.lang.String remark){
		this.remark = remark;
	}

	public java.lang.String getRemark(){
		return this.remark;
	}

	public void setSalaryLevel(java.lang.Long salaryLevel){
		this.salaryLevel = salaryLevel;
	}

	public java.lang.Long getSalaryLevel(){
		return this.salaryLevel;
	}

	public void setPunishmentMonth(java.lang.Long punishmentMonth){
		this.punishmentMonth = punishmentMonth;
	}

	public java.lang.Long getPunishmentMonth(){
		return this.punishmentMonth;
	}

	public void setPunishmentEndDate(java.util.Date punishmentEndDate){
		this.punishmentEndDate = punishmentEndDate;
	}

	public java.util.Date getPunishmentEndDate(){
		return this.punishmentEndDate;
	}
	/* public String getPunishmentEndDateStr() {
			return punishmentEndDateStr;
		}

		public void setPunishmentEndDateStr(String punishmentEndDateStr) throws DateParseException {
			if(!StringUtils.isEmpty(punishmentEndDateStr)){
				this.punishmentEndDate = DateUtil.parseDate(punishmentEndDateStr);
				this.punishmentEndDateStr = punishmentEndDateStr;
			}
			else
				punishmentEndDateStr = "";
		}*/
	public void setUnchainPunishmentDate(java.util.Date unchainPunishmentDate){
		this.unchainPunishmentDate = unchainPunishmentDate;
	}

	public java.util.Date getUnchainPunishmentDate(){
		return this.unchainPunishmentDate;
	}
	  /*public String getUnchainPunishmentDateStr() {
			return unchainPunishmentDateStr;
		}

		public void setUnchainPunishmentDateStr(String unchainPunishmentDateStr) throws DateParseException {
			if(!StringUtils.isEmpty(unchainPunishmentDateStr)){
				this.unchainPunishmentDate = DateUtil.parseDate(unchainPunishmentDateStr);
				this.unchainPunishmentDateStr = unchainPunishmentDateStr;
			}
			else
				unchainPunishmentDateStr = "";
		}*/
	public void setUnchainPunishmentFileno(java.lang.String unchainPunishmentFileno){
		this.unchainPunishmentFileno = unchainPunishmentFileno;
	}

	public java.lang.String getUnchainPunishmentFileno(){
		return this.unchainPunishmentFileno;
	}

	public void setEndApprovalUnit(java.lang.String endApprovalUnit){
		this.endApprovalUnit = endApprovalUnit;
	}

	public java.lang.String getEndApprovalUnit(){
		return this.endApprovalUnit;
	}

	public void setEndApprovalType(java.lang.String endApprovalType){
		this.endApprovalType = endApprovalType;
	}

	public java.lang.String getEndApprovalType(){
		return this.endApprovalType;
	}

	public void setEndPunishmentDateActual(java.util.Date endPunishmentDateActual){
		this.endPunishmentDateActual = endPunishmentDateActual;
	}

	public java.util.Date getEndPunishmentDateActual(){
		return this.endPunishmentDateActual;
	}
	/* public String getEndPunishmentDateActualStr() {
			return endPunishmentDateActualStr;
		}

		public void setEndPunishmentDateActualStr(String endPunishmentDateActualStr) throws DateParseException {
			if(!StringUtils.isEmpty(unchainPunishmentDateStr)){
				this.endPunishmentDateActual = DateUtil.parseDate(endPunishmentDateActualStr);
				this.endPunishmentDateActualStr = endPunishmentDateActualStr;
			}
			else
				endPunishmentDateActualStr = "";
		}*/
	public void setCreatedByCode(java.lang.String createdByCode){
		this.createdByCode = createdByCode;
	}

	public java.lang.String getCreatedByCode(){
		return this.createdByCode;
	}

	public void setCreatedByName(java.lang.String createdByName){
		this.createdByName = createdByName;
	}

	public java.lang.String getCreatedByName(){
		return this.createdByName;
	}

	public void setCreatedDate(java.util.Date createdDate){
		this.createdDate = createdDate;
	}

	public java.util.Date getCreatedDate(){
		return this.createdDate;
	}

	public void setUpdatedByCode(java.lang.String updatedByCode){
		this.updatedByCode = updatedByCode;
	}

	public java.lang.String getUpdatedByCode(){
		return this.updatedByCode;
	}

	public void setUpdatedByName(java.lang.String updatedByName){
		this.updatedByName = updatedByName;
	}

	public java.lang.String getUpdatedByName(){
		return this.updatedByName;
	}

	public void setUpdatedDate(java.util.Date updatedDate){
		this.updatedDate = updatedDate;
	}

	public java.util.Date getUpdatedDate(){
		return this.updatedDate;
	}

}
