/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-09-01
**/
package com.yh.hr.component.mtree.dto;

import com.yh.platform.core.bo.BaseBo;

public class MtNodeDto extends BaseBo {
	private static final long serialVersionUID = 3749559777932061683L;
	
	private java.lang.String	menuCode;	//菜单代码
	private java.lang.String	flowNodeCode;	//业务环节代码
	private java.lang.String	createdByCode;	//CreatedByCode
	private java.lang.String	createdByName;	//CreatedByName
	private java.util.Date	createdDate;	//CreatedDate
	private java.lang.String	updatedByCode;	//UpdatedByCode
	private java.lang.String	updatedByName;	//UpdatedByName
	private java.util.Date	updatedDate;	//UpdatedDate
	
	
	public java.lang.String getMenuCode() {
		return menuCode;
	}
	public void setMenuCode(java.lang.String menuCode) {
		this.menuCode = menuCode;
	}
	public java.lang.String getFlowNodeCode() {
		return flowNodeCode;
	}
	public void setFlowNodeCode(java.lang.String flowNodeCode) {
		this.flowNodeCode = flowNodeCode;
	}
	public java.lang.String getCreatedByCode() {
		return createdByCode;
	}
	public void setCreatedByCode(java.lang.String createdByCode) {
		this.createdByCode = createdByCode;
	}
	public java.lang.String getCreatedByName() {
		return createdByName;
	}
	public void setCreatedByName(java.lang.String createdByName) {
		this.createdByName = createdByName;
	}
	public java.util.Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(java.util.Date createdDate) {
		this.createdDate = createdDate;
	}
	public java.lang.String getUpdatedByCode() {
		return updatedByCode;
	}
	public void setUpdatedByCode(java.lang.String updatedByCode) {
		this.updatedByCode = updatedByCode;
	}
	public java.lang.String getUpdatedByName() {
		return updatedByName;
	}
	public void setUpdatedByName(java.lang.String updatedByName) {
		this.updatedByName = updatedByName;
	}
	public java.util.Date getUpdatedDate() {
		return updatedDate;
	}
	public void setUpdatedDate(java.util.Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
