<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="com.yh.platform.core.constant.Constant"%>
<%@ page import="com.yh.hr.res.dictionary.DicConstants"%>
<%@ include file="/include/jsp_headers.jsp"%>

<!--
 * @function    政治面貌与党派信息信息查看页面
 * @page name   /hrinfo/view/view_ver_pbPoliticInfo_show.jsp
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-14
-->



<!DOCTYPE html>
<html lang="cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>政治面貌与党派信息信息页面</title>
<style type="text/css">
dd {
	white-space: nowrap;
	overflow: hidden;
	text-overflow: ellipsis;
}
</style>
</head>

<body>
	<form id="pbPoliticInfoForm" action="#" method="post">
		<div id="transaction_modal_box" class="transaction_modal_box">
			<div class="modal-dialog-container">
				<div class="md-title">
					政治面貌与党派信息信息&gt;查看<a href="#" class="md-close close-popdown"></a>
				</div>
				<div class="md-main-content">
					<div class="md-units md-three-column clearfix">
						<dl class="data-unit-dl">
							<dt>政治面貌：</dt>
							<dd>
								<label title='<dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0025%>" dicItemCode="${pbPoliticInfoForm.politicStatusCode}" />'><dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0025%>" dicItemCode="${pbPoliticInfoForm.politicStatusCode}" />&nbsp;</label> <label title='<bean:write name="pbPoliticInfoForm" property="politicStatusCode" />'><bean:write name="pbPoliticInfoForm" property="politicStatusCode" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>介绍人：</dt>
							<dd>
								<label title='<bean:write name="pbPoliticInfoForm" property="introducer" />'><bean:write name="pbPoliticInfoForm" property="introducer" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>离党日期：</dt>
							<dd>
								<label title='<bean:write name="pbPoliticInfoForm" property="outPartyDateStr" />'><bean:write name="pbPoliticInfoForm" property="outPartyDateStr" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>备注：</dt>
							<dd>
								<label title='<bean:write name="pbPoliticInfoForm" property="remark" />'><bean:write name="pbPoliticInfoForm" property="remark" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>参加党派时间：</dt>
							<dd>
								<label title='<bean:write name="pbPoliticInfoForm" property="joinPoliticDateStr" />'><bean:write name="pbPoliticInfoForm" property="joinPoliticDateStr" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>转正时间：</dt>
							<dd>
								<label title='<bean:write name="pbPoliticInfoForm" property="probationDateStr" />'><bean:write name="pbPoliticInfoForm" property="probationDateStr" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>异常事项类别：</dt>
							<dd>
								<label title='<dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0075%>" dicItemCode="${pbPoliticInfoForm.abnormityType}" />'><dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0075%>" dicItemCode="${pbPoliticInfoForm.abnormityType}" />&nbsp;</label> <label title='<bean:write name="pbPoliticInfoForm" property="abnormityType" />'><bean:write name="pbPoliticInfoForm" property="abnormityType" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>参加党派时所在单位：</dt>
							<dd>
								<label title='<bean:write name="pbPoliticInfoForm" property="unitOfJoinParty" />'><bean:write name="pbPoliticInfoForm" property="unitOfJoinParty" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>党内职务名称：</dt>
							<dd>
								<label title='<dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0074%>" dicItemCode="${pbPoliticInfoForm.politicDutyCode}" />'><dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0074%>" dicItemCode="${pbPoliticInfoForm.politicDutyCode}" />&nbsp;</label> <label title='<bean:write name="pbPoliticInfoForm" property="politicDutyCode" />'><bean:write name="pbPoliticInfoForm" property="politicDutyCode" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>异常事项原因：</dt>
							<dd>
								<label title='<bean:write name="pbPoliticInfoForm" property="abnormityReason" />'><bean:write name="pbPoliticInfoForm" property="abnormityReason" />&nbsp;</label>
							</dd>
						</dl>
					</div>
				</div>
				<div class="md-btn">
					<button type="button" class="md-btn-cancel close-popdown" data-dismiss="modal" button-click="widget-close">关 闭</button>
				</div>
			</div>
		</div>
	</form>
</body>
</html>