<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="com.yh.platform.core.constant.Constant"%>
<%@ page import="com.yh.hr.res.dictionary.DicConstants"%>
<%@ include file="/include/jsp_headers.jsp"%>

<!--
 * @function    JhcPbRetrieInfo信息查看页面
 * @page name   /hrinfo/view/view_ver_jhcPbRetrieInfo_show.jsp
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-14
-->



<!DOCTYPE html>
<html lang="cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>离退休信息查看页面</title>
<style type="text/css">
dd {
	white-space: nowrap;
	overflow: hidden;
	text-overflow: ellipsis;
}
</style>
</head>

<body>
	<form id="pbRetrieInfoForm" action="#" method="post">
		<div id="transaction_modal_box" class="transaction_modal_box">
			<div class="modal-dialog-container">
				<div class="md-title">
					离退休信息&gt;查看 <a href="#" class="md-close close-popdown"></a>
				</div>
				<div class="md-main-content">
					<div class="md-units md-three-column clearfix">
						<dl class="data-unit-dl">
							<dt>离退类别：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="retrieTypeCode" />'><bean:write name="pbRetrieInfoForm" property="retrieTypeCode" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>离退日期：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="retrieDateStr" />'><bean:write name="pbRetrieInfoForm" property="retrieDateStr" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>提前退休原因：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="retrieReason" />'><bean:write name="pbRetrieInfoForm" property="retrieReason" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>离退后享受待遇级别：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="retireTreatmentLevelCode" />'><bean:write name="pbRetrieInfoForm" property="retireTreatmentLevelCode" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>离退后享受待遇类别：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="retireTreatmentTypeCode" />'><bean:write name="pbRetrieInfoForm" property="retireTreatmentTypeCode" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>离退休费比例：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="retireFeeRatio" />'><bean:write name="pbRetrieInfoForm" property="retireFeeRatio" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>离退休补助比例：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="retireAllowanceRatio" />'><bean:write name="pbRetrieInfoForm" property="retireAllowanceRatio" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>离退休费支付单位：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="retirtPaymentUnit" />'><bean:write name="pbRetrieInfoForm" property="retirtPaymentUnit" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>离退休后管理单位：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="retireManageUnit" />'><bean:write name="pbRetrieInfoForm" property="retireManageUnit" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>离退休批准机关：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="retritApproveUnit" />'><bean:write name="pbRetrieInfoForm" property="retritApproveUnit" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>离退休批准文号：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="retrieApproveFileno" />'><bean:write name="pbRetrieInfoForm" property="retrieApproveFileno" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>离退休证号：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="retireNo" />'><bean:write name="pbRetrieInfoForm" property="retireNo" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>有害工种增加工龄：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="serviceYearsAdded" />'><bean:write name="pbRetrieInfoForm" property="serviceYearsAdded" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>特殊贡献比例：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="specialContributionRatio" />'><bean:write name="pbRetrieInfoForm" property="specialContributionRatio" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>特殊贡献标志：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="specialContributionFlag" />'><bean:write name="pbRetrieInfoForm" property="specialContributionFlag" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>归侨加发比例：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="returnedOverseasChiScale" />'><bean:write name="pbRetrieInfoForm" property="returnedOverseasChiScale" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>归国华侨标志：</dt>
							<dd>
								<label title='<dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0003%>" dicItemCode="${pbRetrieInfoForm.returnedOverseasFlag}" />'>
								<dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0003%>" dicItemCode="${pbRetrieInfoForm.returnedOverseasFlag}" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>是否终身无子女：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="isNoChildForLife" />'><bean:write name="pbRetrieInfoForm" property="isNoChildForLife" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>审批类型：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="approvalType" />'><bean:write name="pbRetrieInfoForm" property="approvalType" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>审查科室：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="approvalUnit" />'><bean:write name="pbRetrieInfoForm" property="approvalUnit" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>符合条例：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="compliedClause" />'><bean:write name="pbRetrieInfoForm" property="compliedClause" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>计生奖励：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="familyPlanningAward" />'><bean:write name="pbRetrieInfoForm" property="familyPlanningAward" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl updown-remark">
							<dt>备注：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="remark" />'><bean:write name="pbRetrieInfoForm" property="remark" />&nbsp;</label>
							</dd>
						</dl>
						<%-- <dl class="data-unit-dl">
							<dt>创建时间：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="createDateStr" />'><bean:write name="pbRetrieInfoForm" property="createDateStr" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>修改时间：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="updateDateStr" />'><bean:write name="pbRetrieInfoForm" property="updateDateStr" />&nbsp;</label>
							</dd>
						</dl> --%>
						<%-- <dl class="data-unit-dl">
							<dt>创建人ID：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="createBy" />'><bean:write name="pbRetrieInfoForm" property="createBy" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>修改人ID：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="updateBy" />'><bean:write name="pbRetrieInfoForm" property="updateBy" />&nbsp;</label>
							</dd>
						</dl> --%>
						<%-- <dl class="data-unit-dl">
							<dt>创建人名称：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="createName" />'><bean:write name="pbRetrieInfoForm" property="createName" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>修改人名称：</dt>
							<dd>
								<label title='<bean:write name="pbRetrieInfoForm" property="updateName" />'><bean:write name="pbRetrieInfoForm" property="updateName" />&nbsp;</label>
							</dd>
						</dl> --%>
					</div>
				</div>
				<div class="md-btn">
					<button type="button" class="md-btn-cancel close-popdown" data-dismiss="modal" button-click="widget-close">关 闭</button>
				</div>
			</div>
		</div>
	</form>
</body>
</html>