<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="com.yh.platform.core.constant.Constant"%>
<%@ page import="com.yh.hr.res.dictionary.DicConstants"%>
<%@ include file="/include/jsp_headers.jsp"%>

<!--
 * @function    JhcPbQualificationsInfo信息查看页面
 * @page name   /hrinfo/view/view_ver_jhcPbQualificationsInfo_show.jsp
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-14
-->



<!DOCTYPE html>
<html lang="cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>职业资格信息查看页面</title>
<style type="text/css">
dd {
	white-space: nowrap;
	overflow: hidden;
	text-overflow: ellipsis;
}
</style>
</head>

<body>
	<form id="pbQualificationsInfoForm" action="#" method="post">
		<div id="transaction_modal_box" class="transaction_modal_box">
			<div class="modal-dialog-container">
				<div class="md-title">
					职业资格信息&gt;查看 <a href="#" class="md-close close-popdown"></a>
				</div>
				<div class="md-main-content">
					<div class="md-units md-three-column clearfix">
						<dl class="data-unit-dl">
							<dt>职业资格证书编号：</dt>
							<dd>
								<label title='<bean:write name="pbQualificationsInfoForm" property="certificateNo" />'><bean:write name="pbQualificationsInfoForm" property="certificateNo" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
              <dt>职业资格类型：</dt>
              <dd>
                <label title='<dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0127%>" dicItemCode="${pbQualificationsInfoForm.qualificationsType}" />'><dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0127%>" dicItemCode="${pbQualificationsInfoForm.qualificationsType}" />&nbsp;</label>
              </dd>
            </dl>
						<dl class="data-unit-dl">
							<dt>取得日期：</dt>
							<dd>
								<label title='<bean:write name="pbQualificationsInfoForm" property="procureDateStr" />'><bean:write name="pbQualificationsInfoForm" property="procureDateStr" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>发证机构：</dt>
							<dd>
								<label title='<bean:write name="pbQualificationsInfoForm" property="issueOrgan" />'><bean:write name="pbQualificationsInfoForm" property="issueOrgan" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>职业资格名称：</dt>
							<dd>
								<label title='<dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS9004%>" dicItemCode="${pbQualificationsInfoForm.qualificationsCode}" />'><dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS9004%>" dicItemCode="${pbQualificationsInfoForm.qualificationsCode}" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>有效期：</dt>
							<dd>
								<label title='<bean:write name="pbQualificationsInfoForm" property="validityDateStr" />'><bean:write name="pbQualificationsInfoForm" property="validityDateStr" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>是否本人最高资格：</dt>
							<dd>
								<label title='<dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0003%>" dicItemCode="${pbQualificationsInfoForm.isHighestLevel}" />'><dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0003%>" dicItemCode="${pbQualificationsInfoForm.isHighestLevel}" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>职业资格等级：</dt>
							<dd>
								<label title='<dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0049%>" dicItemCode="${pbQualificationsInfoForm.qualificationsLevelCode}" />'><dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0049%>" dicItemCode="${pbQualificationsInfoForm.qualificationsLevelCode}" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>取得途径：</dt>
							<dd>
								<label title='<dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0048%>" dicItemCode="${pbQualificationsInfoForm.acquireApproachCode}" />'><dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0048%>" dicItemCode="${pbQualificationsInfoForm.acquireApproachCode}" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl updown-remark">
			        <dt>备注：</dt>
			        <dd>
			          <label title='<bean:write name="pbQualificationsInfoForm" property="remark" />'>
			          <bean:write name="pbQualificationsInfoForm" property="remark" />&nbsp;</label>
			        </dd>
			      </dl>
					</div>
				</div>
				<div class="md-btn">
					<button type="button" class="md-btn-cancel close-popdown" data-dismiss="modal" button-click="widget-close">关 闭</button>
				</div>
			</div>
		</div>
	</form>
</body>
</html>