<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="com.yh.platform.core.constant.Constant"%>
<%@ page import="com.yh.hr.res.dictionary.DicConstants"%>
<%@ include file="/include/jsp_headers.jsp"%>

<!--
 * @function    人员离开信息查看页面
 * @page name   /hrinfo/view/view_ver_jhcPbDeathInfo_show.jsp
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-14
-->



<!DOCTYPE html>
<html lang="cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>人员离开信息查看页面</title>
<style type="text/css">
dd {
	white-space: nowrap;
	overflow: hidden;
	text-overflow: ellipsis;
}
</style>
</head>

<body>
	<form id="pbPersonOutForm" action="#" method="post">
		<div id="transaction_modal_box" class="transaction_modal_box">
			<div class="modal-dialog-container">
				<div class="md-title">
					人员离开信息&gt;查看 <a href="#" class="md-close close-popdown"></a>
				</div>
				<div class="md-main-content">
					<div class="md-units md-three-column clearfix">
						<dl class="data-unit-dl">
							<dt>减员类型：</dt>
							<dd>
								<label title='<dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0128%>" dicItemCode="${pbPersonOutForm.personOutType}" />'>
								<dictionary:viewDicItemName dicTypeCode="<%=DicConstants.YHRS0128%>" dicItemCode="${pbPersonOutForm.personOutType}" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>离开日期：</dt>
							<dd>
								<label title='<bean:write name="pbPersonOutForm" property="outDateStr" />'>
								<bean:write name="pbPersonOutForm" property="outDateStr" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl">
							<dt>离开后去向：</dt>
							<dd>
								<label title='<bean:write name="pbPersonOutForm" property="personOutTo" />'>
								<bean:write name="pbPersonOutForm" property="personOutTo" />&nbsp;</label>
							</dd>
						</dl>
						<dl class="data-unit-dl updown-remark">
							<dt>备注：</dt>
							<dd>
								<label title='<bean:write name="pbPersonOutForm" property="remark" />'>
								<bean:write name="pbPersonOutForm" property="remark" />&nbsp;</label>
							</dd>
						</dl>

					</div>
				</div>
				<div class="md-btn">
					<button type="button" class="md-btn-cancel close-popdown" data-dismiss="modal" button-click="widget-close">关 闭</button>
				</div>
			</div>
		</div>
	</form>
</body>
</html>