/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-10
**/
package com.yh.hr.res.pb.service.impl;

import java.util.List;

import com.yh.component.taglib.TableTagBean;
import com.yh.hr.res.pb.bo.PbEducationTrainingInfo;
import com.yh.hr.res.pb.dto.PbEducationTrainingInfoDTO;
import com.yh.hr.res.pb.queryhelper.PbEducationTrainingInfoQueryHelper;
import com.yh.hr.res.pb.service.PbEducationTrainingInfoService;
import com.yh.platform.core.dao.DaoUtil;
import com.yh.platform.core.exception.ServiceException;
import com.yh.platform.core.util.BeanHelper;

public class PbEducationTrainingInfoServiceImpl implements PbEducationTrainingInfoService {
	public void create(PbEducationTrainingInfoDTO pbEducationTrainingInfoDto) throws ServiceException {
		PbEducationTrainingInfo pbEducationTrainingInfo = new PbEducationTrainingInfo();
		BeanHelper.copyProperties(pbEducationTrainingInfoDto, pbEducationTrainingInfo);
        pbEducationTrainingInfo.save();

	}

	public PbEducationTrainingInfoDTO get(java.lang.Long pbEducationTrainingInfoId) throws ServiceException {
        return BeanHelper.copyProperties(DaoUtil.get(PbEducationTrainingInfo.class, pbEducationTrainingInfoId),PbEducationTrainingInfoDTO.class);
	}
    
	public void update(PbEducationTrainingInfoDTO pbEducationTrainingInfoDto) throws ServiceException {

		PbEducationTrainingInfo pbEducationTrainingInfo = new PbEducationTrainingInfo();
		BeanHelper.copyProperties(pbEducationTrainingInfoDto, pbEducationTrainingInfo);
		pbEducationTrainingInfo.update();
	}
    
	public void delete(java.lang.Long pbEducationTrainingInfoId) throws ServiceException {
      DaoUtil.get(PbEducationTrainingInfo.class, pbEducationTrainingInfoId).delete();
	}
    
	public List<PbEducationTrainingInfoDTO> find(TableTagBean ttb) throws ServiceException {
        return PbEducationTrainingInfoQueryHelper.find(ttb);
	}

	public List<PbEducationTrainingInfoDTO> listPbEducationTrainingInfoByPersonOid(Long personOid) throws ServiceException {
		return PbEducationTrainingInfoQueryHelper.listPbEducationTrainingInfoByPersonOid(personOid);
	}
}