/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-03-20
**/
package com.yh.hr.res.pb.service.impl;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.yh.hr.res.pb.bo.PbPersonOut;
import com.yh.hr.res.pb.dto.PbPersonOutDTO;
import com.yh.hr.res.pb.service.PbPersonOutService;
import org.springframework.util.CollectionUtils;

import com.yh.platform.core.dao.DaoUtil;
import com.yh.platform.core.exception.ServiceException;
import com.yh.platform.core.util.BeanHelper;

public class PbPersonOutServiceImpl implements PbPersonOutService {
	public void create(PbPersonOutDTO jhcPbPersonOutDto) throws ServiceException {
		PbPersonOut jhcPbPersonOut = new PbPersonOut();
		BeanHelper.copyProperties(jhcPbPersonOutDto, jhcPbPersonOut);
        jhcPbPersonOut.save();
        PersonAttachInfoServiceUtil.sysPbOutInfo(jhcPbPersonOutDto.getPersonOid());
	}

	public PbPersonOutDTO get(java.lang.Long jhcPbPersonOutId) throws ServiceException {
        return BeanHelper.copyProperties(DaoUtil.get(PbPersonOut.class, jhcPbPersonOutId),PbPersonOutDTO.class);
	}
    
	public void update(PbPersonOutDTO jhcPbPersonOutDto) throws ServiceException {

		PbPersonOut jhcPbPersonOut = new PbPersonOut();
		BeanHelper.copyProperties(jhcPbPersonOutDto, jhcPbPersonOut);
		jhcPbPersonOut.update();
		PersonAttachInfoServiceUtil.sysPbOutInfo(jhcPbPersonOutDto.getPersonOid());
	}
    
	public void delete(java.lang.Long jhcPbPersonOutId) throws ServiceException {
      PbPersonOut bo = DaoUtil.get(PbPersonOut.class, jhcPbPersonOutId);
	  if(null != bo)
	  {
		  bo.delete();
	      PersonAttachInfoServiceUtil.sysPbOutInfo(bo.getPersonOid());
	  }
	}

	public List<PbPersonOutDTO> listPbPersonOutByPersonOid(Long personOid)
			throws ServiceException {
		String hql = "from PbPersonOut fi where fi.personOid = :personOid";
		Map<String, Object> params = new HashMap<String, Object>();
		params.put("personOid", personOid);
		List<PbPersonOut> boList = DaoUtil.find(hql, params);
		List<PbPersonOutDTO> dtoList = new ArrayList<PbPersonOutDTO>();
		
		if(!CollectionUtils.isEmpty(boList))
		{
			for(PbPersonOut bo : boList)
			{
				PbPersonOutDTO dto = new PbPersonOutDTO();
				BeanHelper.copyProperties(bo, dto);
				dtoList.add(dto);
			}
		}
		return dtoList;
	}

	/*
	 * (non-Javadoc)
	 * @see PbPersonOutService#findByPersonOid(java.lang.Long)
	 */
	public PbPersonOutDTO findByPersonOid(Long personOid)
			throws ServiceException 
    {
		List<PbPersonOutDTO> dtoList = this.listPbPersonOutByPersonOid(personOid);
		if(!CollectionUtils.isEmpty(dtoList))
		{
			return dtoList.get(0);
		}
		return null;
	}

	public void deleteByPersonOid(Long personOid) throws ServiceException {
		DaoUtil.executeUpdate("delete from PbPersonOut where personOid='"+personOid+"'");
	}
}