/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-13
**/
package com.yh.hr.res.pb.service.impl;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import com.yh.hr.res.pb.bo.PbPunishmentInfo;
import com.yh.hr.res.pb.queryhelper.PbPunishmentInfoQueryHelper;
import org.springframework.util.CollectionUtils;

import com.yh.hr.res.pb.dto.PbPunishmentInfoDTO;
import com.yh.hr.res.pb.service.PbPunishmentInfoService;
import com.yh.component.taglib.TableTagBean;
import com.yh.platform.core.dao.DaoUtil;
import com.yh.platform.core.util.BeanHelper;
import com.yh.platform.core.exception.ServiceException;

public class PbPunishmentInfoServiceImpl implements PbPunishmentInfoService{
	public void create(PbPunishmentInfoDTO pbPunishmentInfoDto) throws ServiceException {
		PbPunishmentInfo pbPunishmentInfo = new PbPunishmentInfo();
		BeanHelper.copyProperties(pbPunishmentInfoDto, pbPunishmentInfo);
        pbPunishmentInfo.save();
	}

	public PbPunishmentInfoDTO get(java.lang.Long pbPunishmentInfoId) throws ServiceException {
        return BeanHelper.copyProperties(DaoUtil.get(PbPunishmentInfo.class, pbPunishmentInfoId),PbPunishmentInfoDTO.class);
	}
    
	public void update(PbPunishmentInfoDTO pbPunishmentInfoDto) throws ServiceException {

		PbPunishmentInfo pbPunishmentInfo = new PbPunishmentInfo();
		BeanHelper.copyProperties(pbPunishmentInfoDto, pbPunishmentInfo);
		pbPunishmentInfo.update();
	}
    
	public void delete(java.lang.Long pbPunishmentInfoId) throws ServiceException {
      DaoUtil.get(PbPunishmentInfo.class, pbPunishmentInfoId).delete();
	}
    
	public List<PbPunishmentInfoDTO> find(TableTagBean ttb) throws ServiceException {
        StringBuilder hql = new StringBuilder();
        HashMap<String, Object> hqlParams = new HashMap<String, Object>();
        PbPunishmentInfoQueryHelper.buildHQL(ttb.getCondition(), hql, hqlParams);
        String order = ttb.getOrderBy();
        if (order != null) {
            if (ttb.getAsc()) {
                hql.append(" order by " + order + " asc");
            } else {
                hql.append(" order by " + order + " desc");
            }
        }
        List<PbPunishmentInfoDTO> list = new ArrayList<PbPunishmentInfoDTO>();
        List<PbPunishmentInfo> boList = DaoUtil.listByCondition(hql.toString(), hqlParams, ttb.getPage() * ttb.getPageSize(), ttb.getPageSize());
		if(!CollectionUtils.isEmpty(boList))
		{
			for(PbPunishmentInfo bo : boList)
			{
				PbPunishmentInfoDTO dto = new PbPunishmentInfoDTO();
				BeanHelper.copyProperties(bo, dto);
				list.add(dto);
			}
		}
        ttb.setList(list);
        ttb.setTotal(DaoUtil.countByCondition("select count(*) "+hql, hqlParams));
        return list;
	}

	public List<PbPunishmentInfoDTO> getPunishmentInfoByPersonOid(Long personOid)
			throws ServiceException {
		return PbPunishmentInfoQueryHelper.getPunishmentInfoByPersonOid(personOid);
	}


}