/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-10
**/
package com.yh.hr.info.ver.unit.comm.web.form;

import org.apache.commons.lang.StringUtils;
import org.apache.struts.validator.ValidatorForm;

import com.yh.platform.core.util.DateUtil;

public class PbEngageContractInfoForm extends ValidatorForm {
	private static final long serialVersionUID = 110119120L;

	private java.lang.Long engageContractOid;
	private java.lang.Long personOid;
	private java.lang.String contractNo;
	private java.lang.String contractType;
	private java.lang.String changeType;
	private java.util.Date contractBegin;
    private String contractBeginStr;
	private java.util.Date contractEnd;
    private String contractEndStr;
	private java.util.Date contractEndActual;
    private String contractEndActualStr;
	private java.lang.String probationFlag;
	private java.util.Date probationBegin;
    private String probationBeginStr;
	private java.util.Date probationEnd;
    private String probationEndStr;
	private java.lang.String status;
	private java.lang.String addressPermanant;
	private java.lang.String addressCommunication;
	private java.lang.String contactPhone;
	private java.util.Date signDate;
    private String signDateStr;
	private java.lang.String contractJob;
	private java.lang.String others;
	private java.lang.Long unitOid;
	private java.lang.String unitName;
	private java.lang.String unitMaster;
	private java.lang.String unitAddress;
	private java.lang.String unitPhone;
	private java.lang.String createBy;
	private java.lang.String createName;
	private java.util.Date createDate;
    private String createDateStr;
	private java.lang.String updateBy;
	private java.lang.String updateName;
	private java.util.Date updateDate;
    private String updateDateStr;

	public PbEngageContractInfoForm() {}

    public void setEngageContractOid(java.lang.Long engageContractOid){
		this.engageContractOid = engageContractOid;
	}

	public java.lang.Long getEngageContractOid(){
		return this.engageContractOid;
	}
    public void setPersonOid(java.lang.Long personOid){
		this.personOid = personOid;
	}

	public java.lang.Long getPersonOid(){
		return this.personOid;
	}
    public void setContractNo(java.lang.String contractNo){
		this.contractNo = contractNo;
	}

	public java.lang.String getContractNo(){
		return this.contractNo;
	}
    public void setContractType(java.lang.String contractType){
		this.contractType = contractType;
	}

	public java.lang.String getContractType(){
		return this.contractType;
	}
    public void setChangeType(java.lang.String changeType){
		this.changeType = changeType;
	}

	public java.lang.String getChangeType(){
		return this.changeType;
	}
    public void setContractBegin(java.util.Date contractBegin){
		this.contractBegin = contractBegin;
		if(null != contractBegin){
			this.contractBeginStr = DateUtil.format(contractBegin, "yyyy-MM-dd");
         }
	}

	public java.util.Date getContractBegin(){
		return this.contractBegin;
	}
    public void setContractBeginStr(String contractBeginStr){
        this.contractBeginStr = contractBeginStr;
        if(StringUtils.isNotEmpty(contractBeginStr)){
               this.contractBegin = DateUtil.parse(contractBeginStr, "yyyy-MM-dd");
        }
    }

    public String getContractBeginStr(){
        return this.contractBeginStr;
    }
    public void setContractEnd(java.util.Date contractEnd){
		this.contractEnd = contractEnd;
		if(null != contractEnd){
			this.contractEndStr = DateUtil.format(contractEnd, "yyyy-MM-dd");
         }
	}

	public java.util.Date getContractEnd(){
		return this.contractEnd;
	}
    public void setContractEndStr(String contractEndStr){
        this.contractEndStr = contractEndStr;
        if(StringUtils.isNotEmpty(contractEndStr)){
               this.contractEnd = DateUtil.parse(contractEndStr, "yyyy-MM-dd");
        }
    }

    public String getContractEndStr(){
        return this.contractEndStr;
    }
    public void setContractEndActual(java.util.Date contractEndActual){
		this.contractEndActual = contractEndActual;
		if(null != contractEndActual){
			this.contractEndActualStr = DateUtil.format(contractEndActual, "yyyy-MM-dd");
         }
	}

	public java.util.Date getContractEndActual(){
		return this.contractEndActual;
	}
    public void setContractEndActualStr(String contractEndActualStr){
        this.contractEndActualStr = contractEndActualStr;
        if(StringUtils.isNotEmpty(contractEndActualStr)){
               this.contractEndActual = DateUtil.parse(contractEndActualStr, "yyyy-MM-dd");
        }
    }

    public String getContractEndActualStr(){
        return this.contractEndActualStr;
    }
    public void setProbationFlag(java.lang.String probationFlag){
		this.probationFlag = probationFlag;
	}

	public java.lang.String getProbationFlag(){
		return this.probationFlag;
	}
    public void setProbationBegin(java.util.Date probationBegin){
		this.probationBegin = probationBegin;
		if(null != probationBegin){
			this.probationBeginStr = DateUtil.format(probationBegin, "yyyy-MM-dd");
         }
	}

	public java.util.Date getProbationBegin(){
		return this.probationBegin;
	}
    public void setProbationBeginStr(String probationBeginStr){
        this.probationBeginStr = probationBeginStr;
        if(StringUtils.isNotEmpty(probationBeginStr)){
               this.probationBegin = DateUtil.parse(probationBeginStr, "yyyy-MM-dd");
        }
    }

    public String getProbationBeginStr(){
        return this.probationBeginStr;
    }
    public void setProbationEnd(java.util.Date probationEnd){
		this.probationEnd = probationEnd;
		if(null != probationEnd){
			this.probationEndStr = DateUtil.format(probationEnd, "yyyy-MM-dd");
         }
	}

	public java.util.Date getProbationEnd(){
		return this.probationEnd;
	}
    public void setProbationEndStr(String probationEndStr){
        this.probationEndStr = probationEndStr;
        if(StringUtils.isNotEmpty(probationEndStr)){
               this.probationEnd = DateUtil.parse(probationEndStr, "yyyy-MM-dd");
        }
    }

    public String getProbationEndStr(){
        return this.probationEndStr;
    }
    public void setStatus(java.lang.String status){
		this.status = status;
	}

	public java.lang.String getStatus(){
		return this.status;
	}
    public void setAddressPermanant(java.lang.String addressPermanant){
		this.addressPermanant = addressPermanant;
	}

	public java.lang.String getAddressPermanant(){
		return this.addressPermanant;
	}
    public void setAddressCommunication(java.lang.String addressCommunication){
		this.addressCommunication = addressCommunication;
	}

	public java.lang.String getAddressCommunication(){
		return this.addressCommunication;
	}
    public void setContactPhone(java.lang.String contactPhone){
		this.contactPhone = contactPhone;
	}

	public java.lang.String getContactPhone(){
		return this.contactPhone;
	}
    public void setSignDate(java.util.Date signDate){
		this.signDate = signDate;
		if(null != signDate){
			this.signDateStr = DateUtil.format(signDate, "yyyy-MM-dd");
         }
	}

	public java.util.Date getSignDate(){
		return this.signDate;
	}
    public void setSignDateStr(String signDateStr){
        this.signDateStr = signDateStr;
        if(StringUtils.isNotEmpty(signDateStr)){
               this.signDate = DateUtil.parse(signDateStr, "yyyy-MM-dd");
        }
    }

    public String getSignDateStr(){
        return this.signDateStr;
    }
    public void setContractJob(java.lang.String contractJob){
		this.contractJob = contractJob;
	}

	public java.lang.String getContractJob(){
		return this.contractJob;
	}
    public void setOthers(java.lang.String others){
		this.others = others;
	}

	public java.lang.String getOthers(){
		return this.others;
	}
    public void setUnitOid(java.lang.Long unitOid){
		this.unitOid = unitOid;
	}

	public java.lang.Long getUnitOid(){
		return this.unitOid;
	}
    public void setUnitName(java.lang.String unitName){
		this.unitName = unitName;
	}

	public java.lang.String getUnitName(){
		return this.unitName;
	}
    public void setUnitMaster(java.lang.String unitMaster){
		this.unitMaster = unitMaster;
	}

	public java.lang.String getUnitMaster(){
		return this.unitMaster;
	}
    public void setUnitAddress(java.lang.String unitAddress){
		this.unitAddress = unitAddress;
	}

	public java.lang.String getUnitAddress(){
		return this.unitAddress;
	}
    public void setUnitPhone(java.lang.String unitPhone){
		this.unitPhone = unitPhone;
	}

	public java.lang.String getUnitPhone(){
		return this.unitPhone;
	}
    public void setCreateBy(java.lang.String createBy){
		this.createBy = createBy;
	}

	public java.lang.String getCreateBy(){
		return this.createBy;
	}
    public void setCreateName(java.lang.String createName){
		this.createName = createName;
	}

	public java.lang.String getCreateName(){
		return this.createName;
	}
    public void setCreateDate(java.util.Date createDate){
		this.createDate = createDate;
		if(null != createDate){
			this.createDateStr = DateUtil.format(createDate, "yyyy-MM-dd");
         }
	}

	public java.util.Date getCreateDate(){
		return this.createDate;
	}
    public void setCreateDateStr(String createDateStr){
        this.createDateStr = createDateStr;
        if(StringUtils.isNotEmpty(createDateStr)){
               this.createDate = DateUtil.parse(createDateStr, "yyyy-MM-dd");
        }
    }

    public String getCreateDateStr(){
        return this.createDateStr;
    }
    public void setUpdateBy(java.lang.String updateBy){
		this.updateBy = updateBy;
	}

	public java.lang.String getUpdateBy(){
		return this.updateBy;
	}
    public void setUpdateName(java.lang.String updateName){
		this.updateName = updateName;
	}

	public java.lang.String getUpdateName(){
		return this.updateName;
	}
    public void setUpdateDate(java.util.Date updateDate){
		this.updateDate = updateDate;
		if(null != updateDate){
			this.updateDateStr = DateUtil.format(updateDate, "yyyy-MM-dd");
         }
	}

	public java.util.Date getUpdateDate(){
		return this.updateDate;
	}
    public void setUpdateDateStr(String updateDateStr){
        this.updateDateStr = updateDateStr;
        if(StringUtils.isNotEmpty(updateDateStr)){
               this.updateDate = DateUtil.parse(updateDateStr, "yyyy-MM-dd");
        }
    }

    public String getUpdateDateStr(){
        return this.updateDateStr;
    }
	public void resetForm() {
		this.engageContractOid = null;
		this.personOid = null;
		this.contractNo = null;
		this.contractType = null;
		this.changeType = null;
		this.contractBegin = null;
        this.contractBeginStr = null;
		this.contractEnd = null;
        this.contractEndStr = null;
		this.contractEndActual = null;
        this.contractEndActualStr = null;
		this.probationFlag = null;
		this.probationBegin = null;
        this.probationBeginStr = null;
		this.probationEnd = null;
        this.probationEndStr = null;
		this.status = null;
		this.addressPermanant = null;
		this.addressCommunication = null;
		this.contactPhone = null;
		this.signDate = null;
        this.signDateStr = null;
		this.contractJob = null;
		this.others = null;
		this.unitOid = null;
		this.unitName = null;
		this.unitMaster = null;
		this.unitAddress = null;
		this.unitPhone = null;
		this.createBy = null;
		this.createName = null;
		this.createDate = null;
        this.createDateStr = null;
		this.updateBy = null;
		this.updateName = null;
		this.updateDate = null;
        this.updateDateStr = null;
	}

}
