/**
 * @desctiption   This file is generated by  code generation tool version 0.2 ^_^
 * @Created   2017-02-13
**/
package com.yh.hr.info.ver.unit.comm.web.form;

import org.apache.commons.lang.StringUtils;
import org.apache.struts.validator.ValidatorForm;

import com.yh.platform.core.util.DateUtil;

public class PbRewardInfoForm extends ValidatorForm {
	private static final long serialVersionUID = 110119120L;

	private java.lang.Long rewardOid;
	private java.lang.Long personOid;
	private java.lang.String rewardName;
	private java.lang.String rewardTypeCode;
	private java.lang.String honourLevel;
	private java.lang.String encouragementReason;
	private java.lang.String rewardUnit;
	private java.util.Date rewardDate;
    private String rewardDateStr;
	private java.lang.String remark;
	private java.lang.String createBy;
	private java.lang.String createName;
	private java.util.Date createDate;
    private String createDateStr;
	private java.lang.String updateBy;
	private java.lang.String updateName;
	private java.util.Date updateDate;
    private String updateDateStr;

	public PbRewardInfoForm() {}

    public void setRewardOid(java.lang.Long rewardOid){
		this.rewardOid = rewardOid;
	}

	public java.lang.Long getRewardOid(){
		return this.rewardOid;
	}
    public void setPersonOid(java.lang.Long personOid){
		this.personOid = personOid;
	}

	public java.lang.Long getPersonOid(){
		return this.personOid;
	}
    public void setRewardName(java.lang.String rewardName){
		this.rewardName = rewardName;
	}

	public java.lang.String getRewardName(){
		return this.rewardName;
	}
    public void setRewardTypeCode(java.lang.String rewardTypeCode){
		this.rewardTypeCode = rewardTypeCode;
	}

	public java.lang.String getRewardTypeCode(){
		return this.rewardTypeCode;
	}
    public void setHonourLevel(java.lang.String honourLevel){
		this.honourLevel = honourLevel;
	}

	public java.lang.String getHonourLevel(){
		return this.honourLevel;
	}
    public void setEncouragementReason(java.lang.String encouragementReason){
		this.encouragementReason = encouragementReason;
	}

	public java.lang.String getEncouragementReason(){
		return this.encouragementReason;
	}
    public void setRewardUnit(java.lang.String rewardUnit){
		this.rewardUnit = rewardUnit;
	}

	public java.lang.String getRewardUnit(){
		return this.rewardUnit;
	}
    public void setRewardDate(java.util.Date rewardDate){
		this.rewardDate = rewardDate;
		if(null != rewardDate){
			this.rewardDateStr = DateUtil.format(rewardDate, "yyyy-MM");
         }
	}

	public java.util.Date getRewardDate(){
		return this.rewardDate;
	}
    public void setRewardDateStr(String rewardDateStr){
        this.rewardDateStr = rewardDateStr;
        if(StringUtils.isNotEmpty(rewardDateStr)){
               this.rewardDate = DateUtil.parse(rewardDateStr, "yyyy-MM");
        }
    }

    public String getRewardDateStr(){
        return this.rewardDateStr;
    }
    public void setRemark(java.lang.String remark){
		this.remark = remark;
	}

	public java.lang.String getRemark(){
		return this.remark;
	}
    public void setCreateBy(java.lang.String createBy){
		this.createBy = createBy;
	}

	public java.lang.String getCreateBy(){
		return this.createBy;
	}
    public void setCreateName(java.lang.String createName){
		this.createName = createName;
	}

	public java.lang.String getCreateName(){
		return this.createName;
	}
    public void setCreateDate(java.util.Date createDate){
		this.createDate = createDate;
		if(null != createDate){
			this.createDateStr = DateUtil.format(createDate, "yyyy-MM");
         }
	}

	public java.util.Date getCreateDate(){
		return this.createDate;
	}
    public void setCreateDateStr(String createDateStr){
        this.createDateStr = createDateStr;
        if(StringUtils.isNotEmpty(createDateStr)){
               this.createDate = DateUtil.parse(createDateStr, "yyyy-MM");
        }
    }

    public String getCreateDateStr(){
        return this.createDateStr;
    }
    public void setUpdateBy(java.lang.String updateBy){
		this.updateBy = updateBy;
	}

	public java.lang.String getUpdateBy(){
		return this.updateBy;
	}
    public void setUpdateName(java.lang.String updateName){
		this.updateName = updateName;
	}

	public java.lang.String getUpdateName(){
		return this.updateName;
	}
    public void setUpdateDate(java.util.Date updateDate){
		this.updateDate = updateDate;
		if(null != updateDate){
			this.updateDateStr = DateUtil.format(updateDate, "yyyy-MM");
         }
	}

	public java.util.Date getUpdateDate(){
		return this.updateDate;
	}
    public void setUpdateDateStr(String updateDateStr){
        this.updateDateStr = updateDateStr;
        if(StringUtils.isNotEmpty(updateDateStr)){
               this.updateDate = DateUtil.parse(updateDateStr, "yyyy-MM");
        }
    }

    public String getUpdateDateStr(){
        return this.updateDateStr;
    }
	public void resetForm() {
		this.rewardOid = null;
		this.personOid = null;
		this.rewardName = null;
		this.rewardTypeCode = null;
		this.honourLevel = null;
		this.encouragementReason = null;
		this.rewardUnit = null;
		this.rewardDate = null;
        this.rewardDateStr = null;
		this.remark = null;
		this.createBy = null;
		this.createName = null;
		this.createDate = null;
        this.createDateStr = null;
		this.updateBy = null;
		this.updateName = null;
		this.updateDate = null;
        this.updateDateStr = null;
	}

}
