/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-09-02
**/
package com.yh.hr.res.unit.dto;

public class UtOrgDTO {

	private java.lang.Long  	organizationOid;	//OrganizationOid
	private java.lang.Long  	orgOid;	//OrgOid
	private java.lang.Long  	unitOid;	//所属单位
	private java.lang.Long  	parentOrgOid; //隶属内设机构
	private java.lang.String  	parentOrgName; //隶属内设机构
	private boolean isleaf;//是否有下设内设机构
	private java.lang.String	orgName;	//OrgName
	private java.lang.String	orgType;	//内设机构类型YHRS0102
	private java.lang.String	orgStatus;	//内设机构状态YHRS0101
	private java.lang.String	orderOfAll;	//内设机构全局排序
	private java.lang.String	createdByCode;	//CreatedByCode
	private java.lang.String	createdByName;	//CreatedByName
	private java.util.Date  	createdDate;	//CreatedDate
	private java.lang.String	updatedByCode;	//UpdatedByCode
	private java.lang.String	updatedByName;	//UpdatedByName
	private java.util.Date  	updatedDate;	//UpdatedDate
	private boolean isUnit;//是否是单位节点
	
	private java.lang.String	hierarchyCode;	//层级编码
	private java.lang.String    orgCategory;//所属科室类型YHRS0102

	public boolean isUnit() {
		return isUnit;
	}

	public void setUnit(boolean isUnit) {
		this.isUnit = isUnit;
	}

	public UtOrgDTO() {
		
	}

	public void setOrganizationOid(java.lang.Long organizationOid){
		this.organizationOid = organizationOid;
	}

	public java.lang.Long getOrganizationOid(){
		return this.organizationOid;
	}

	public void setOrgOid(java.lang.Long orgOid){
		this.orgOid = orgOid;
	}

	public java.lang.Long getOrgOid(){
		return this.orgOid;
	}

	public void setOrgName(java.lang.String orgName){
		this.orgName = orgName;
	}

	public java.lang.String getOrgName(){
		return this.orgName;
	}

	public void setOrgType(java.lang.String orgType){
		this.orgType = orgType;
	}

	public java.lang.String getOrgType(){
		return this.orgType;
	}

	public void setOrgStatus(java.lang.String orgStatus){
		this.orgStatus = orgStatus;
	}

	public java.lang.String getOrgStatus(){
		return this.orgStatus;
	}

	public void setOrderOfAll(java.lang.String orderOfAll){
		this.orderOfAll = orderOfAll;
	}

	public java.lang.String getOrderOfAll(){
		return this.orderOfAll;
	}

	public void setCreatedByCode(java.lang.String createdByCode){
		this.createdByCode = createdByCode;
	}

	public java.lang.String getCreatedByCode(){
		return this.createdByCode;
	}

	public void setCreatedByName(java.lang.String createdByName){
		this.createdByName = createdByName;
	}

	public java.lang.String getCreatedByName(){
		return this.createdByName;
	}

	public void setCreatedDate(java.util.Date createdDate){
		this.createdDate = createdDate;
	}

	public java.util.Date getCreatedDate(){
		return this.createdDate;
	}

	public void setUpdatedByCode(java.lang.String updatedByCode){
		this.updatedByCode = updatedByCode;
	}

	public java.lang.String getUpdatedByCode(){
		return this.updatedByCode;
	}

	public void setUpdatedByName(java.lang.String updatedByName){
		this.updatedByName = updatedByName;
	}

	public java.lang.String getUpdatedByName(){
		return this.updatedByName;
	}

	public void setUpdatedDate(java.util.Date updatedDate){
		this.updatedDate = updatedDate;
	}

	public java.util.Date getUpdatedDate(){
		return this.updatedDate;
	}

	public java.lang.Long getUnitOid() {
		return unitOid;
	}

	public void setUnitOid(java.lang.Long unitOid) {
		this.unitOid = unitOid;
	}

	public java.lang.Long getParentOrgOid() {
		return parentOrgOid;
	}

	public void setParentOrgOid(java.lang.Long parentOrgOid) {
		this.parentOrgOid = parentOrgOid;
	}

	public java.lang.String getParentOrgName() {
		return parentOrgName;
	}

	public void setParentOrgName(java.lang.String parentOrgName) {
		this.parentOrgName = parentOrgName;
	}

	public boolean getIsleaf() {
		return isleaf;
	}

	public void setIsleaf(boolean isleaf) {
		this.isleaf = isleaf;
	}

	public java.lang.String getHierarchyCode() {
		return hierarchyCode;
	}

	public void setHierarchyCode(java.lang.String hierarchyCode) {
		this.hierarchyCode = hierarchyCode;
	}

	public java.lang.String getOrgCategory() {
		return orgCategory;
	}

	public void setOrgCategory(java.lang.String orgCategory) {
		this.orgCategory = orgCategory;
	}
}
