/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-11-09
**/
package com.yh.component.upload.bo;

import com.yh.platform.core.bo.BaseBo;

public class UploadStatus extends BaseBo {
	private static final long serialVersionUID = -6903083616010873303L;

	private java.lang.String	uuid;	//文件唯一名称
	private java.lang.String	fileNameLocal;	//用户本地文件名称（上传文件名称）
	private java.lang.String	fileNameRemote;	//保存在服务器的文件名称
	private java.lang.String	filePathLocal;	//用户本地的文件路径
	private java.lang.String	filePathRemote;	//文件在服务器的路径
	private java.lang.String	fileMd5;	//文件的MD5值
	private java.lang.Long  	fileLength;	//文件总字节长度
	private java.lang.String	fileSize;	//文件大小描述
	private java.lang.Long  	filePos;	//文件已上传的位置
	private java.lang.Long  	postedLength;	//文件已上传的长度？
	private java.lang.String	postedPercent;	//已上传的百分比
	private java.util.Date  	postedTime;	//上传完成时间
	
	private int  	postComplete;	//是否完成 0：未完成，1：已完成

	public UploadStatus() {
		
	}

	public void setUuid(java.lang.String uuid){
		this.uuid = uuid;
	}

	public java.lang.String getUuid(){
		return this.uuid;
	}

	public void setFileNameLocal(java.lang.String fileNameLocal){
		this.fileNameLocal = fileNameLocal;
	}

	public java.lang.String getFileNameLocal(){
		return this.fileNameLocal;
	}

	public void setFileNameRemote(java.lang.String fileNameRemote){
		this.fileNameRemote = fileNameRemote;
	}

	public java.lang.String getFileNameRemote(){
		return this.fileNameRemote;
	}

	public void setFilePathLocal(java.lang.String filePathLocal){
		this.filePathLocal = filePathLocal;
	}

	public java.lang.String getFilePathLocal(){
		return this.filePathLocal;
	}

	public void setFilePathRemote(java.lang.String filePathRemote){
		this.filePathRemote = filePathRemote;
	}

	public java.lang.String getFilePathRemote(){
		return this.filePathRemote;
	}

	public void setFileMd5(java.lang.String fileMd5){
		this.fileMd5 = fileMd5;
	}

	public java.lang.String getFileMd5(){
		return this.fileMd5;
	}

	public void setFileLength(java.lang.Long fileLength){
		this.fileLength = fileLength;
	}

	public java.lang.Long getFileLength(){
		return this.fileLength;
	}

	public void setFileSize(java.lang.String fileSize){
		this.fileSize = fileSize;
	}

	public java.lang.String getFileSize(){
		return this.fileSize;
	}

	public void setFilePos(java.lang.Long filePos){
		this.filePos = filePos;
	}

	public java.lang.Long getFilePos(){
		return this.filePos;
	}

	public void setPostedLength(java.lang.Long postedLength){
		this.postedLength = postedLength;
	}

	public java.lang.Long getPostedLength(){
		return this.postedLength;
	}

	public void setPostedPercent(java.lang.String postedPercent){
		this.postedPercent = postedPercent;
	}

	public java.lang.String getPostedPercent(){
		return this.postedPercent;
	}

	public void setPostComplete(int postComplete){
		this.postComplete = postComplete;
	}

	public int getPostComplete(){
		return this.postComplete;
	}

	public void setPostedTime(java.util.Date postedTime){
		this.postedTime = postedTime;
	}

	public java.util.Date getPostedTime(){
		return this.postedTime;
	}

}
