/**
 * This file is generated by  code generation tool version 0.2 ^_^
 * Created at 2016-08-23
**/
package com.yh.admin.bo;

import com.yh.platform.core.bo.BaseBo;

public class Roles extends BaseBo {
	private static final long serialVersionUID = 4195919642397835724L;
	
	private java.lang.Long	roleId;	//角色主键
	private java.lang.String	roleName;	//角色名称
	private java.lang.String	roleDesc;	//角色描述
	private java.lang.String	roleType;	//角色类型
	private java.lang.String	createdByCode;	//创建人代码
	private java.util.Date	createdDate;	//创建时间
	private java.lang.String	updatedByCode;	//修改人代码
	private java.util.Date	updatedDate;	//修改时间

	public Roles() {
		
	}

	public void setRoleId(java.lang.Long roleId){
		this.roleId = roleId;
	}

	public java.lang.Long getRoleId(){
		return this.roleId;
	}

	public void setRoleName(java.lang.String roleName){
		this.roleName = roleName;
	}

	public java.lang.String getRoleName(){
		return this.roleName;
	}

	public void setRoleDesc(java.lang.String roleDesc){
		this.roleDesc = roleDesc;
	}

	public java.lang.String getRoleDesc(){
		return this.roleDesc;
	}

	public void setRoleType(java.lang.String roleType){
		this.roleType = roleType;
	}

	public java.lang.String getRoleType(){
		return this.roleType;
	}

	public void setCreatedByCode(java.lang.String createdByCode){
		this.createdByCode = createdByCode;
	}

	public java.lang.String getCreatedByCode(){
		return this.createdByCode;
	}

	public void setCreatedDate(java.util.Date createdDate){
		this.createdDate = createdDate;
	}

	public java.util.Date getCreatedDate(){
		return this.createdDate;
	}

	public void setUpdatedByCode(java.lang.String updatedByCode){
		this.updatedByCode = updatedByCode;
	}

	public java.lang.String getUpdatedByCode(){
		return this.updatedByCode;
	}

	public void setUpdatedDate(java.util.Date updatedDate){
		this.updatedDate = updatedDate;
	}

	public java.util.Date getUpdatedDate(){
		return this.updatedDate;
	}

}
